### ISSUE TITLE
Error and crash when exiting Torch staging #44

### ISSUE THREAD

**Issue by Basti91le** [TorchAPI/Torch#171]
- [ ] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [ ] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:** 1.2.0.12232 **SE Version:** 1.184.801

### Expected Behavior
After shutting down the server over the GUI, the server saves the world and you can close the program. 

### Observed Behavior
After stopping the server over the GUI the server saves the world just fine, but throws an error as seen below. After the error there is an "exiting in 5 seconds". After that the Torch GUI closes but the command line window is still there. 

### Steps to Reproduce
1. Starting the server with GUI and after starting, stop it in the GUI. 

### Other Information
Crash Log:
16:38:55.2893 [INFO]   Torch: Stopping server.
16:38:55.2933 [INFO]   Torch: Server stopped.
16:38:57.3751 [INFO]   Torch.Session.TorchSessionManager: Unloading torch session for Miners Playground
16:38:57.3907 [INFO]   Torch.Server.Managers.MultiplayerManagerDedicated: Removed steam authentication intercept
16:38:57.7188 [FATAL]  Initializer: System.ObjectDisposedException: Cannot access a disposed object.
   at System.Threading.TimerQueueTimer.Change(UInt32 dueTime, UInt32 period)
   at Torch.Collections.MtObservableCollection`2.OnCollectionChanged(NotifyCollectionChangedEventArgs e) in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch\Collections\MtObservableCollection.cs:line 211
   at Torch.Collections.MtObservableCollection`2.Remove(TV item) in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch\Collections\MtObservableCollection.cs:line 120
   at Torch.Server.Managers.EntityControlManager.UnregisterModelFactory[TEntityBaseModel](Func`2 modelFactory) in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch.Server\Managers\EntityControlManager.cs:line 143
   at Profiler.Impl.ProfilerManager.Detach() in C:\Program Files (x86)\Jenkins\workspace\Torch_Profiler_staging-TFHHHSHIKLBYTXNPPA7D35FSTIIHXHSAOSISW6SANGC4TTYB4WBA\Profiler\Impl\ProfilerManager.cs:line 81
   at Torch.Managers.DependencyManager.Detach() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch\Managers\DependencyManager.cs:line 263
   at Torch.TorchBase.Dispose() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch\TorchBase.cs:line 401
   at VRage.Plugins.MyPlugins.Unload()
   at Dispose_0(Object )
   at VRage.Dedicated.DedicatedServer.RunInternal()
   at Torch.Server.TorchServer.Start() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch.Server\TorchServer.cs:line 175
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
System.ObjectDisposedException: Cannot access a disposed object.
   at System.Threading.TimerQueueTimer.Change(UInt32 dueTime, UInt32 period)
   at Torch.Collections.MtObservableCollection`2.OnCollectionChanged(NotifyCollectionChangedEventArgs e) in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch\Collections\MtObservableCollection.cs:line 211
   at Torch.Collections.MtObservableCollection`2.Remove(TV item) in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch\Collections\MtObservableCollection.cs:line 120
   at Torch.Server.Managers.EntityControlManager.UnregisterModelFactory[TEntityBaseModel](Func`2 modelFactory) in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch.Server\Managers\EntityControlManager.cs:line 143
   at Profiler.Impl.ProfilerManager.Detach() in C:\Program Files (x86)\Jenkins\workspace\Torch_Profiler_staging-TFHHHSHIKLBYTXNPPA7D35FSTIIHXHSAOSISW6SANGC4TTYB4WBA\Profiler\Impl\ProfilerManager.cs:line 81
   at Torch.Managers.DependencyManager.Detach() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch\Managers\DependencyManager.cs:line 263
   at Torch.TorchBase.Dispose() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch\TorchBase.cs:line 401
   at VRage.Plugins.MyPlugins.Unload()
   at Dispose_0(Object )
   at VRage.Dedicated.DedicatedServer.RunInternal()
   at Torch.Server.TorchServer.Start() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch.Server\TorchServer.cs:line 175
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by Equinox-** [comment]
Should be fixed since https://github.com/TorchAPI/Torch/commit/c188367749fec7cd64766ee28b6ce749583f0f33
