### ISSUE TITLE
Start-up bug from Initializer.

### ISSUE THREAD

**Issue by Khornath** [TorchAPI/Torch#174]
**- [ ] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game**
It's happens when first starting the Torch.Server.Exe, I asume this is related to torch as there are no plugins yet.
**- [ ] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)**
I tried it twice, it gave the same error on both occasions.
**- [ ] Is this a suggestion?**
No.

**Torch Version:** 1.2.0 **SE Version:** 1.185.017

### Expected Behavior
What did you expect to happen?
After unzipping the .zip file and installing the game through SteamCMD it should have started the server.client.

### Observed Behavior
What actually happened?
It gave a fatal crash regarding the Initializer having a System.MissingFieldException. More info in the log below.

### Steps to Reproduce
1. Download latest torch.server.zip
2. Unzip into a new directory
3. Run "Torch.Server.Exe" as administrator

### Other Information

> Log
```
23:19:46.9736 [INFO] SteamCMD: Downloading SteamCMD.
23:19:51.5672 [INFO] SteamCMD: SteamCMD downloaded successfully!
23:19:51.5828 [INFO] SteamCMD: Checking for DS updates.
23:20:17.7364 [INFO] SteamCMD: Steam Console Client (c) Valve Corporation
23:20:17.8614 [INFO] SteamCMD: -- type 'quit' to exit --
23:20:17.9864 [INFO] SteamCMD: Loading Steam API...OK.
23:20:18.1114 [INFO] SteamCMD: 
23:20:23.0360 [INFO] SteamCMD: Connecting anonymously to Steam Public...Logged in OK
23:20:29.2433 [INFO] SteamCMD: Waiting for user info...OK
23:20:29.7746 [INFO] SteamCMD:  Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
23:20:31.0247 [INFO] SteamCMD:  Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
23:20:33.0248 [INFO] SteamCMD:  Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
23:20:35.0249 [INFO] SteamCMD:  Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
23:20:37.0094 [INFO] SteamCMD:  Update state (0x5) validating, progress: 84.32 (1593894829 / 1890327357)
23:20:39.0253 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 0.06 (1048576 / 1890327357)
23:20:41.0255 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 0.06 (1048576 / 1890327357)
23:20:43.0014 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 1.56 (29410784 / 1890327357)
23:20:45.0172 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 4.18 (79014307 / 1890327357)
23:20:47.0017 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 7.73 (146215296 / 1890327357)
23:20:49.0018 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 11.11 (210075180 / 1890327357)
23:20:51.0020 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 12.03 (227389124 / 1890327357)
23:20:53.0086 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 13.48 (254908117 / 1890327357)
23:20:55.0018 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 17.00 (321334980 / 1890327357)
23:20:57.0053 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 19.58 (370112736 / 1890327357)
23:20:59.0055 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 20.14 (380655398 / 1890327357)
23:21:01.0056 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 20.21 (382083130 / 1890327357)
23:21:03.0083 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 20.75 (392156910 / 1890327357)
23:21:05.0084 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 23.39 (442201211 / 1890327357)
23:21:07.0086 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 24.47 (462533989 / 1890327357)
23:21:09.0087 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 24.73 (467468367 / 1890327357)
23:21:11.0088 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 25.16 (475624096 / 1890327357)
23:21:13.0019 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 28.50 (538701100 / 1890327357)
23:21:15.0176 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 35.61 (673075284 / 1890327357)
23:21:17.0178 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 38.00 (718293763 / 1890327357)
23:21:19.0179 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 42.29 (799397443 / 1890327357)
23:21:21.0180 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 44.79 (846596433 / 1890327357)
23:21:23.0182 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 45.39 (858074455 / 1890327357)
23:21:25.0163 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 46.42 (877548489 / 1890327357)
23:21:27.0165 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 48.15 (910230399 / 1890327357)
23:21:29.0166 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 49.09 (927879676 / 1890327357)
23:21:31.0168 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 49.76 (940562713 / 1890327357)
23:21:33.0169 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 50.47 (954110296 / 1890327357)
23:21:35.0171 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 51.06 (965166431 / 1890327357)
23:21:37.0172 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 52.39 (990388623 / 1890327357)
23:21:39.0174 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 52.67 (995655389 / 1890327357)
23:21:41.0175 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 52.72 (996486217 / 1890327357)
23:21:43.0189 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 52.83 (998605641 / 1890327357)
23:21:45.0146 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 52.91 (1000177266 / 1890327357)
23:21:47.0136 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 52.99 (1001762163 / 1890327357)
23:21:49.0137 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 54.01 (1020992285 / 1890327357)
23:21:51.0149 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 54.84 (1036650292 / 1890327357)
23:21:53.0158 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 55.35 (1046327152 / 1890327357)
23:21:55.0227 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 56.02 (1058927347 / 1890327357)
23:21:57.0267 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 57.17 (1080670878 / 1890327357)
23:21:59.0268 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 57.99 (1096201139 / 1890327357)
23:22:01.0269 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 58.80 (1111551201 / 1890327357)
23:22:03.0271 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 59.69 (1128376862 / 1890327357)
23:22:05.0272 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 60.81 (1149414214 / 1890327357)
23:22:07.0274 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 61.61 (1164567171 / 1890327357)
23:22:09.0275 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 62.75 (1186092557 / 1890327357)
23:22:11.0276 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 63.92 (1208216612 / 1890327357)
23:22:13.0278 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 64.24 (1214363479 / 1890327357)
23:22:15.0012 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 64.35 (1216417431 / 1890327357)
23:22:17.0013 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 64.42 (1217816427 / 1890327357)
23:22:19.0015 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 64.50 (1219236219 / 1890327357)
23:22:21.0016 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 65.01 (1228848656 / 1890327357)
23:22:23.0018 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 65.83 (1244397094 / 1890327357)
23:22:25.0019 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 66.85 (1263750024 / 1890327357)
23:22:27.0020 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 67.74 (1280564073 / 1890327357)
23:22:29.0022 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 68.49 (1294634590 / 1890327357)
23:22:31.0023 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 70.88 (1339903172 / 1890327357)
23:22:33.0025 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 71.94 (1359915441 / 1890327357)
23:22:35.0026 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 72.42 (1369042940 / 1890327357)
23:22:37.0085 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 73.27 (1384982463 / 1890327357)
23:22:39.0087 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 74.15 (1401675441 / 1890327357)
23:22:41.0088 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 78.29 (1479963288 / 1890327357)
23:22:43.0090 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 78.86 (1490656044 / 1890327357)
23:22:45.0091 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 78.89 (1491340719 / 1890327357)
23:22:47.0092 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 78.93 (1492024328 / 1890327357)
23:22:49.0094 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 78.96 (1492683771 / 1890327357)
23:22:51.0095 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 79.00 (1493274236 / 1890327357)
23:22:53.0096 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 79.04 (1494201633 / 1890327357)
23:22:55.0098 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 79.08 (1494934759 / 1890327357)
23:22:57.0101 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 79.13 (1495877936 / 1890327357)
23:22:59.0194 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 79.17 (1496514940 / 1890327357)
23:23:01.0196 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 79.21 (1497322697 / 1890327357)
23:23:03.0197 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 79.25 (1498110413 / 1890327357)
23:23:05.0199 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 79.30 (1499041589 / 1890327357)
23:23:07.0200 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 79.35 (1499993887 / 1890327357)
23:23:09.0201 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 79.39 (1500737327 / 1890327357)
23:23:11.0203 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 79.44 (1501641485 / 1890327357)
23:23:13.0204 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 79.47 (1502269799 / 1890327357)
23:23:15.0206 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 79.51 (1502939801 / 1890327357)
23:23:17.0207 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 79.55 (1503844001 / 1890327357)
23:23:19.0208 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 79.59 (1504525022 / 1890327357)
23:23:21.0210 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 79.63 (1505230282 / 1890327357)
23:23:23.0211 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 79.66 (1505905527 / 1890327357)
23:23:25.0212 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 79.69 (1506478501 / 1890327357)
23:23:27.0282 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 79.75 (1507617727 / 1890327357)
23:23:29.0207 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 79.79 (1508291122 / 1890327357)
23:23:31.0208 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 79.85 (1509472928 / 1890327357)
23:23:33.0209 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 79.91 (1510477585 / 1890327357)
23:23:35.0211 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 79.96 (1511485907 / 1890327357)
23:23:37.0212 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 80.03 (1512855328 / 1890327357)
23:23:39.0214 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 80.13 (1514637522 / 1890327357)
23:23:41.0215 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 80.18 (1515673082 / 1890327357)
23:23:43.0207 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 80.46 (1521006348 / 1890327357)
23:23:45.0209 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 81.89 (1548008206 / 1890327357)
23:23:47.0210 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 82.13 (1552473125 / 1890327357)
23:23:49.0212 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 82.65 (1562264014 / 1890327357)
23:23:51.0213 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 83.47 (1577921901 / 1890327357)
23:23:53.0214 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 83.89 (1585750405 / 1890327357)
23:23:55.0216 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 84.32 (1593977064 / 1890327357)
23:23:57.0217 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 84.38 (1595026853 / 1890327357)
23:23:59.0213 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 84.41 (1595643887 / 1890327357)
23:24:01.0214 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 84.44 (1596119175 / 1890327357)
23:24:03.0215 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 84.49 (1597062053 / 1890327357)
23:24:05.0219 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 84.54 (1598013113 / 1890327357)
23:24:07.0132 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 84.97 (1606223307 / 1890327357)
23:24:09.0144 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 85.02 (1607158606 / 1890327357)
23:24:11.0168 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 85.06 (1607947346 / 1890327357)
23:24:13.0212 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 85.30 (1612498459 / 1890327357)
23:24:15.0216 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 86.11 (1627672877 / 1890327357)
23:24:17.0309 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 88.11 (1665641684 / 1890327357)
23:24:19.0311 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 88.48 (1672614820 / 1890327357)
23:24:21.0000 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 89.39 (1689826349 / 1890327357)
23:24:23.0001 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 89.79 (1697352894 / 1890327357)
23:24:25.0003 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 89.82 (1697981942 / 1890327357)
23:24:27.0160 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 90.16 (1704298368 / 1890327357)
23:24:29.0220 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 90.36 (1708130957 / 1890327357)
23:24:31.0221 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 90.44 (1709652012 / 1890327357)
23:24:33.0223 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 90.62 (1713020549 / 1890327357)
23:24:35.0224 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 90.77 (1715902072 / 1890327357)
23:24:37.0226 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 91.07 (1721507801 / 1890327357)
23:24:39.0227 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 92.41 (1746844910 / 1890327357)
23:24:41.0228 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 94.09 (1778544664 / 1890327357)
23:24:43.0309 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 95.58 (1806800524 / 1890327357)
23:24:45.0078 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 96.42 (1822644864 / 1890327357)
23:24:47.0235 [INFO] SteamCMD:  Update state (0x101) committing, progress: 39.05 (738219369 / 1890327357)
23:24:49.0237 [INFO] SteamCMD:  Update state (0x101) committing, progress: 70.33 (1329414694 / 1890327357)
23:24:51.0219 [INFO] SteamCMD:  Update state (0x101) committing, progress: 84.56 (1598534037 / 1890327357)
23:24:52.7877 [INFO] SteamCMD: Success! App '298740' fully installed.
23:24:53.2408 [INFO] SteamCMD: Redirecting stderr to 'C:\Servers\torch-server\steamcmd\logs\stderr.txt'
23:24:53.3658 [INFO] Initializer: Generating default config at C:\Servers\torch-server\Torch.cfg
23:24:53.8815 [FATAL] Initializer: System.MissingFieldException: Field not found: 'Sandbox.Engine.Utils.MyFakes.ENABLE_INFINARIO'.
   at Torch.Server.TorchServer..ctor(TorchConfig config)
   at Torch.Server.Initializer.Run() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch.Server\Initializer.cs:line 85
   at Torch.Server.Program.Main(String[] args) in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch.Server\Program.cs:line 62
23:27:44.1161 [INFO] SteamCMD: Checking for DS updates.
23:27:49.0539 [INFO] SteamCMD: Steam Console Client (c) Valve Corporation
23:27:49.1945 [INFO] SteamCMD: -- type 'quit' to exit --
23:27:49.3195 [INFO] SteamCMD: Loading Steam API...OK.
23:27:49.4445 [INFO] SteamCMD: 
23:27:50.9147 [INFO] SteamCMD: Connecting anonymously to Steam Public...Logged in OK
23:27:51.0397 [INFO] SteamCMD: Waiting for user info...OK
23:27:51.9185 [INFO] SteamCMD: Success! App '298740' already up to date.
23:27:52.2310 [INFO] SteamCMD: 
23:27:52.3717 [INFO] Initializer: Loading config C:\Servers\torch-server\Torch.cfg
23:27:52.8560 [FATAL] Initializer: System.MissingFieldException: Field not found: 'Sandbox.Engine.Utils.MyFakes.ENABLE_INFINARIO'.
   at Torch.Server.TorchServer..ctor(TorchConfig config)
   at Torch.Server.Initializer.Run() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch.Server\Initializer.cs:line 85
   at Torch.Server.Program.Main(String[] args) in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch.Server\Program.cs:line 62
23:28:01.8216 [INFO] SteamCMD: Checking for DS updates.
23:28:05.4156 [INFO] SteamCMD: Steam Console Client (c) Valve Corporation
23:28:05.5407 [INFO] SteamCMD: -- type 'quit' to exit --
23:28:05.6656 [INFO] SteamCMD: Loading Steam API...OK.
23:28:05.7906 [INFO] SteamCMD: 
23:28:24.4688 [INFO] SteamCMD: Connecting anonymously to Steam Public...Logged in OK
23:28:34.0164 [INFO] SteamCMD: Checking for DS updates.
23:28:37.4867 [INFO] SteamCMD: Steam Console Client (c) Valve Corporation
23:28:37.6117 [INFO] SteamCMD: -- type 'quit' to exit --
23:28:37.7367 [INFO] SteamCMD: Loading Steam API...OK.
23:28:37.8617 [INFO] SteamCMD: 
23:28:38.7273 [INFO] SteamCMD: Connecting anonymously to Steam Public...Logged in OK
23:28:38.8523 [INFO] SteamCMD: Waiting for user info...OK
23:28:39.6743 [INFO] SteamCMD: Success! App '298740' already up to date.
23:28:40.6744 [INFO] SteamCMD: 
23:28:40.8150 [INFO] Initializer: Loading config C:\Servers\torch-server\Torch.cfg
23:28:41.2838 [FATAL] Initializer: System.MissingFieldException: Field not found: 'Sandbox.Engine.Utils.MyFakes.ENABLE_INFINARIO'.
   at Torch.Server.TorchServer..ctor(TorchConfig config)
   at Torch.Server.Initializer.Run() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch.Server\Initializer.cs:line 85
   at Torch.Server.Program.Main(String[] args) in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch.Server\Program.cs:line 62
23:33:01.4714 [INFO] SteamCMD: Checking for DS updates.
23:33:03.7741 [INFO] SteamCMD: 
23:33:11.4088 [INFO] SteamCMD: Checking for DS updates.
23:33:14.9513 [INFO] SteamCMD: Steam Console Client (c) Valve Corporation
23:33:15.0684 [INFO] SteamCMD: -- type 'quit' to exit --
23:33:15.1845 [INFO] SteamCMD: Loading Steam API...OK.
23:33:15.3016 [INFO] SteamCMD: 
23:33:16.2892 [INFO] SteamCMD: Connecting anonymously to Steam Public...Logged in OK
23:33:16.4053 [INFO] SteamCMD: Waiting for user info...OK
23:33:17.1922 [INFO] SteamCMD: Success! App '298740' already up to date.
23:33:18.1257 [INFO] SteamCMD: 
23:33:18.2444 [INFO] Initializer: Loading config C:\Servers\torch-server\Torch.cfg
23:33:18.7279 [FATAL] Initializer: System.MissingFieldException: Field not found: 'Sandbox.Engine.Utils.MyFakes.ENABLE_INFINARIO'.
   at Torch.Server.TorchServer..ctor(TorchConfig config)
   at Torch.Server.Initializer.Run() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch.Server\Initializer.cs:line 85
   at Torch.Server.Program.Main(String[] args) in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch.Server\Program.cs:line 62
23:33:28.1286 [INFO] SteamCMD: Checking for DS updates.
23:33:28.8069 [INFO] SteamCMD: Steam Console Client (c) Valve Corporation
23:33:28.9241 [INFO] SteamCMD: -- type 'quit' to exit --
23:33:29.0402 [INFO] SteamCMD: Loading Steam API...OK.
23:33:29.1573 [INFO] SteamCMD: 
23:33:30.0617 [INFO] SteamCMD: Connecting anonymously to Steam Public...Logged in OK
23:33:30.1788 [INFO] SteamCMD: Waiting for user info...OK
23:33:30.9456 [INFO] SteamCMD: Success! App '298740' already up to date.
23:33:31.9718 [INFO] SteamCMD: 
23:33:32.0900 [INFO] Initializer: Loading config C:\Servers\torch-server\Torch.cfg
23:33:32.5544 [FATAL] Initializer: System.MissingFieldException: Field not found: 'Sandbox.Engine.Utils.MyFakes.ENABLE_INFINARIO'.
   at Torch.Server.TorchServer..ctor(TorchConfig config)
   at Torch.Server.Initializer.Run() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch.Server\Initializer.cs:line 85
   at Torch.Server.Program.Main(String[] args) in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_staging-ZNS7FN4RGURQGN7YDLUHQ3UMYIBPHQSIJWKCAY6N7MCURWHGXRKA\Torch.Server\Program.cs:line 62
```

**Comment by Jimmacle** [comment]
Download the latest staging version from Jenkins.

**Comment by Khornath** [comment]
Not to be an ass, but

**Installation**

- Getthe latest Torch release here: https://github.com/TorchAPI/Torch/releases
- Unzip the Torch release into its own directory and run the executable. It will automatically download the SE DS and **generate the other necessary files**.
- If you already have a DS installed you can unzip the Torch files into the folder that contains the DedicatedServer64 folder.

Please change this line and preferably provide a link for Jenkins.

**Comment by Jimmacle** [comment]
We have some leftovers from trying different release schemes, we'll work on cleaning it up so it's more clear where/how to find the proper versions.

**Comment by Khornath** [comment]
Thanks for the respond. Kind of salty from testing issues on SE. Trying to narrow down some bug which is pretty hard to narrow down. As the evirement keeps changing.
