### ISSUE TITLE
[Issue] Plugins fail to run/crash to desktop

### ISSUE THREAD

**Issue by Alcohealix** [TorchAPI/Torch#184]
- [ ] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [ ] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:** 1.3.0.8 **SE Version:** 1.185.601

### Expected Behavior
Attempting the three plugins Essential, Profiler, Concealment

### Observed Behavior
When attempting to run i first get error: 

`12:56:58.9811 [INFO]   PluginManager: Checking for plugin updates...
12:56:58.9981 [WARN]   PluginManager: Item 'C:\Users\Admin\Desktop\Torch-Server Admin Tools\Plugins\Profiler' is missing a manifest, skipping update check.
12:56:59.0071 [INFO]   PluginManager: Updated 0 plugins.`

After adding manifest from the profiler-staging (or any of the plugins) i get the following error:

`17:53:29.8711 [INFO]   PluginManager: Checking for plugin updates...
17:53:30.1861 [INFO]   PluginManager: Updated 0 plugins.
17:53:30.1861 [INFO]   PluginManager: Loading plugins...
17:53:31.3721 [ERROR]  PluginManager: Unable to find archive for the latest release of 'TorchAPI/Concealment.'
17:53:31.3721 [ERROR]  PluginManager: Error parsing version from manifest or GitHub for plugin 'Concealment.'
17:53:40.1200 [FATAL]  Initializer: System.BadImageFormatException: Bad IL format.
System.BadImageFormatException: Bad IL format.
17:53:40.1200 [FATAL]  Initializer: System.BadImageFormatException: Could not load file or assembly '161792 bytes loaded from Torch, Version=1.3.0.8, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format.
File name: '161792 bytes loaded from Torch, Version=1.3.0.8, Culture=neutral, PublicKeyToken=null' ---> System.BadImageFormatException: Bad IL format.
   at System.Reflection.RuntimeAssembly.nLoadImage(Byte[] rawAssembly, Byte[] rawSymbolStore, Evidence evidence, StackCrawlMark& stackMark, Boolean fIntrospection, SecurityContextSource securityContextSource)
   at System.Reflection.Assembly.Load(Byte[] rawAssembly)
   at Torch.Managers.PluginManager.LoadPluginFromFolder(String directory)
   at Torch.Managers.PluginManager.LoadPlugins()
   at Torch.TorchBase.Init()
   at Torch.Server.TorchServer.Init()
   at Torch.Server.Initializer.Run()
   at Torch.Server.Program.Main(String[] args)
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssemblyByName(String assemblyName, String[] args)
   at Torch.Utils.TorchLauncher.Launch(String entryPoint, String[] args, String[] binaryPaths)
   at Torch.Server.Program.Main(String[] args)`

`System.BadImageFormatException: Could not load file or assembly '161792 bytes loaded from Torch, Version=1.3.0.8, Culture=neutral, PublicKeyToken=null' or one of its dependencies. An attempt was made to load a program with an incorrect format.
File name: '161792 bytes loaded from Torch, Version=1.3.0.8, Culture=neutral, PublicKeyToken=null' ---> System.BadImageFormatException: Bad IL format.
   at System.Reflection.RuntimeAssembly.nLoadImage(Byte[] rawAssembly, Byte[] rawSymbolStore, Evidence evidence, StackCrawlMark& stackMark, Boolean fIntrospection, SecurityContextSource securityContextSource)
   at System.Reflection.Assembly.Load(Byte[] rawAssembly)
   at Torch.Managers.PluginManager.LoadPluginFromFolder(String directory)
   at Torch.Managers.PluginManager.LoadPlugins()
   at Torch.TorchBase.Init()
   at Torch.Server.TorchServer.Init()
   at Torch.Server.Initializer.Run()
   at Torch.Server.Program.Main(String[] args)
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssemblyByName(String assemblyName, String[] args)
   at Torch.Utils.TorchLauncher.Launch(String entryPoint, String[] args, String[] binaryPaths)
   at Torch.Server.Program.Main(String[] args)`

### Other Information
Attached is copy of the logs.
[Torch-2017-12-31.log](https://github.com/TorchAPI/Torch/files/1595528/Torch-2017-12-31.log)

**Comment by Jimmacle** [comment]
Did you download releases from GitHub? You'll want to read the release text very carefully.

**Comment by Alcohealix** [comment]
Well that's embarrassing. Thanks!

**Comment by Jimmacle** [comment]
Understandable, once I have time to finish the website everything will be moved there so it isn't confusing.
