### ISSUE TITLE
PrivateMods plugin doesn't work.

### ISSUE THREAD

**Issue by dstruct2k** [TorchAPI/Torch#217]
Hello, I have been trying to set up Torch with a new world I generated using the vanilla DS, but am getting the following error:

```
12:00:10.8273 [INFO]   Torch: Initializing server
12:00:11.6234 [INFO]   Torch: RELEASE
12:00:11.6474 [INFO]   Torch: Torch Version: v1.3.0.29-51-gaeb29d9
12:00:11.6654 [INFO]   Torch: Game Version: 1.186.500
12:00:11.6824 [INFO]   Torch: Executing assembly: Torch.Server, Version=1.3.0.29, Culture=neutral, PublicKeyToken=null
12:00:11.7144 [INFO]   Torch: Executing directory: C:\DedicatedServers\SpaceEngineers\
12:00:11.7725 [WARN]   PluginManager: Automatic plugin updates are disabled in this build of Torch while the system is reworked.
12:00:11.7955 [INFO]   PluginManager: Loading plugins...
12:00:11.9235 [INFO]   PluginManager: Loading plugin 'Concealment' (v1.4.0.10)
12:00:11.9675 [INFO]   PluginManager: Loading plugin 'Essentials' (v1.7.0.13-4-g83ada5b)
12:00:11.9975 [INFO]   PluginManager: Loading plugin 'Private Mods' (1.1.3)
12:00:12.0865 [ERROR]  Initializer: Error initializing server.
12:00:12.1055 [ERROR]  Initializer: System.InvalidOperationException: Paths are not initialized, call 'Init'
   at VRage.FileSystem.MyFileSystem.CheckInitialized()
   at VRage.FileSystem.MyFileSystem.get_ModsPath()
   at Phoenix.Torch.Plugin.PrivateMods.MySteamWorkshopReplacement..cctor()
System.InvalidOperationException: Paths are not initialized, call 'Init'
   at VRage.FileSystem.MyFileSystem.CheckInitialized()
   at VRage.FileSystem.MyFileSystem.get_ModsPath()
   at Phoenix.Torch.Plugin.PrivateMods.MySteamWorkshopReplacement..cctor()

```

I created the world, copied everything from ProgramData to \Instance\, and launched Torch. What have I missed?

**Comment by Jimmacle** [comment]
It looks like the PrivateMods plugin is broken.

**Comment by dstruct2k** [comment]
Aha, thanks. I should have tried removing those plugins first... x.x
