### ISSUE TITLE
Torch doesn't load mod list from sandbox.sbc

### ISSUE THREAD

**Issue by mccorkle** [TorchAPI/Torch#25]
How to reproduce:
* open torch, pointed at a save file created with SEDS
* start server
* gracefully stop server
* edit mods list (via double click) 
* click "save config" button below mods list
* close torch
* open torch again -- old mods list will be listed in the mods box

NOTE: it does look like Sandbox.sbc is getting written when I click "save Config" and it does have the proper mods.  The part that is failing is when I load torch again, it appears to have the old mod list.

What did I expect to happen?
* mods list should have been saved

Versions:
* Torch: Torch 1.0.136.343
* SE 1.180.503

**Comment by mccorkle** [comment]
This appears to have been resolved as of newest torch (or perhaps just because I used stock SEDS, not sure). Either way, I will retest as soon as we get 181 working.

**Comment by mccorkle** [comment]
I'm getting this when I attempted to change the mod list from the Torch UI:

2017-06-18 11:15:23.3344 [INFO] Config: Saved DS config.
2017-06-18 11:15:23.3494 [ERROR] Config: Failed to write sandbox config, changes will not appear on server
2017-06-18 11:15:23.3494 [ERROR] Config: System.NullReferenceException: Object reference not set to an instance of an object.
   at Torch.Server.Views.ConfigControl.SaveConfig()

Torch 1.0.168.389
se 1.181.202
Windows server 2012 R2

**Comment by Jimmacle** [comment]
That usually happens when it can't find the world that you set in the config. Sometimes it's right, sometimes it's magic keen issues.

**Comment by mccorkle** [comment]
I figured out what the reproduce case is:
* load torch, start world, realize you are missing a mod
* stop server, try to add the mod
* no save

```
2017-06-23 11:47:54.5451 [INFO] Config: Saved DS config.
2017-06-23 11:47:54.5471 [ERROR] Config: Failed to write sandbox config, changes
 will not appear on server
2017-06-23 11:47:54.5471 [ERROR] Config: System.NullReferenceException: Object r
eference not set to an instance of an object.
   at Torch.Server.Views.ConfigControl.SaveConfig()
```

But this is a user error (I should exit Torch after I stop server), so I'm closing this bug :-)
