### ISSUE TITLE
Torch Crash, Handle is not initialized.

### ISSUE THREAD

**Issue by PotatoPotata** [TorchAPI/Torch#250]
- [Don't know ] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [Can't really do that] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [No] Is this a suggestion?

We hope that you can get sth interesting out of the log, at least provide us with info about what's causing the crash.

**Torch Version:** 1.3.0.61 **SE Version:** 1.187.101

### Expected Behavior
What did you expect to happen?
We expected server to run normally.

### Observed Behavior
A seemingly random crash of Torch. Log provided.

### Steps to Reproduce
1. Run the server,(Torch, Concealment, Essentials, Profiler)
2. Get around 10 people in, doing stuff.
3. Wait?

### Other Information

20:16:10.2472 [INFO]   Keen: OnConnectedClient ARO attempt
20:16:10.3052 [FATAL]  Initializer: System.InvalidOperationException: Handle is not initialized.
   at System.Runtime.InteropServices.GCHandle.FromIntPtr(IntPtr value)
   at gcroot<Havok::HkConstraint ^>..PE$AAVHkConstraint@Havok@@(gcroot<Havok::HkConstraint ^>* )
   at Havok.HkConstraint.GetAttachedConstraints(HkRigidBody rigidBody, List`1 constraintsOut)
   at Sandbox.Engine.Physics.MyPhysicsBody.NotifyConstraintsRemovedFromWorld()
   at Sandbox.Game.Entities.Cube.MyGridPhysics.ConvertToStatic()
   at Sandbox.Game.Entities.MyCubeGrid.UpdateBeforeSimulation()
   at <UpdateBeforeSimulation>b__7_0(MyEntity )
   at VRage.Collections.MyDistributedUpdater`2.Iterate(Action`1 p)
   at Sandbox.Game.Entities.MyEntities.UpdateBeforeSimulation()
   at Sandbox.Game.World.MySector.UpdateBeforeSimulation()
   at UpdateComponents_0(Object )
   at Sandbox.Game.World.MySession.Update

**Comment by Jimmacle** [comment]
This is an issue related to Concealment, we have a test version here that should fix the issue: https://build.torchapi.net/job/Torch/job/Concealment/job/nophys/

**Comment by PotatoPotata** [comment]
Thank you very much, we will test the fix today, then come back and share the results.
