### ISSUE TITLE
[ERROR]  EntityTreeViewModel: System.ArgumentException: Source array was not long 

### ISSUE THREAD

**Issue by Fank** [TorchAPI/Torch#258]
- [X] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [ ] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:** 1.3.0.68-143-g0ff715a **SE Version:** 1.187.205

### Expected Behavior
No fancy yellow error message in console

### Observed Behavior
```
21:57:07.9125 [ERROR]  EntityTreeViewModel: System.ArgumentException: Source array was not long enough. Check srcIndex and length, and the array's lower bounds.
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Collections.Generic.Queue`1.SetCapacity(Int32 capacity)
   at System.Collections.Generic.Queue`1.Enqueue(T item)
   at Torch.Collections.MtObservableCollectionBase`1.OnPropertyChanged(String propName)
   at Torch.Collections.MtObservableSortedDictionary`2.ProxyCollection`1.ParentChanged(NotifyCollectionChangedEventArgs args)
   at Torch.Collections.MtObservableSortedDictionary`2.RaiseAllChanged(NotifyCollectionChangedEventArgs evt)
   at Torch.Collections.MtObservableSortedDictionary`2.Remove(TK key)
   at Torch.Server.ViewModels.EntityTreeViewModel.MyEntities_OnEntityRemove(MyEntity obj)
System.ArgumentException: Source array was not long enough. Check srcIndex and length, and the array's lower bounds.
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Collections.Generic.Queue`1.SetCapacity(Int32 capacity)
   at System.Collections.Generic.Queue`1.Enqueue(T item)
   at Torch.Collections.MtObservableCollectionBase`1.OnPropertyChanged(String propName)
   at Torch.Collections.MtObservableSortedDictionary`2.ProxyCollection`1.ParentChanged(NotifyCollectionChangedEventArgs args)
   at Torch.Collections.MtObservableSortedDictionary`2.RaiseAllChanged(NotifyCollectionChangedEventArgs evt)
   at Torch.Collections.MtObservableSortedDictionary`2.Remove(TK key)
   at Torch.Server.ViewModels.EntityTreeViewModel.MyEntities_OnEntityRemove(MyEntity obj)
```

### Steps to Reproduce
1. Nope?

### Other Information
Provide links to game logs or saves here if necessary.

**Comment by Jimmacle** [comment]
Known issue with thread safety in "thread safe" collections.

**Comment by Jimmacle** [comment]
Should be fixed by https://github.com/TorchAPI/Torch/commit/6d29bce267790b7179665b082a3ab6e24deea186
