### ISSUE TITLE
Torch.Managers.NetworkManager: Error processing network event!

### ISSUE THREAD

**Issue by Fank** [TorchAPI/Torch#259]
- [X] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [ ] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:** 1.3.0.69 **SE Version:** 1.187.208

### Expected Behavior
No issues

### Observed Behavior
Some `ERROR` log entries i wanted to report.
And report that joining server caused it, with no progress.

### Steps to Reproduce
N/A

### Other Information
```
20:28:52.2504 [INFO]   Torch.Managers.MultiplayerManagerBase: Player evgenevih joined (76561198369879056
20:52:51.7116 [ERROR]  Torch.Managers.NetworkManager: Error processing network event!
System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.Game.SessionComponents.MySessionComponentContainerDropSystem.RemoveContainerDropComponent(Int64 entityId)
   at VRage.Network.CallSite`7.Invoke(BitStream stream, Object obj, Boolean validate)
   at VRage.Network.MyReplicationLayer.Invoke(CallSite callSite, BitStream stream, Object obj, EndpointId source, MyClientStateBase clientState, Boolean validate)
   at VRage.Network.MyReplicationServer.OnEvent(MyPacketDataBitStreamBase data, CallSite site, Object obj, IMyNetObject sendAs, EndpointId source)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacketDataBitStreamBase data, NetworkId networkId, NetworkId blockedNetId, UInt32 eventId, EndpointId sender)
   at VRage.Network.MyReplicationLayer.ProcessEvent(MyPacketDataBitStreamBase data, EndpointId sender)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacket packet)
   at Torch.Managers.NetworkManager.OnEvent(MyPacket packet)
20:52:51.7187 [ERROR]  Torch.Managers.NetworkManager: System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.Game.SessionComponents.MySessionComponentContainerDropSystem.RemoveContainerDropComponent(Int64 entityId)
   at VRage.Network.CallSite`7.Invoke(BitStream stream, Object obj, Boolean validate)
   at VRage.Network.MyReplicationLayer.Invoke(CallSite callSite, BitStream stream, Object obj, EndpointId source, MyClientStateBase clientState, Boolean validate)
   at VRage.Network.MyReplicationServer.OnEvent(MyPacketDataBitStreamBase data, CallSite site, Object obj, IMyNetObject sendAs, EndpointId source)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacketDataBitStreamBase data, NetworkId networkId, NetworkId blockedNetId, UInt32 eventId, EndpointId sender)
   at VRage.Network.MyReplicationLayer.ProcessEvent(MyPacketDataBitStreamBase data, EndpointId sender)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacket packet)
   at Torch.Managers.NetworkManager.OnEvent(MyPacket packet)
System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.Game.SessionComponents.MySessionComponentContainerDropSystem.RemoveContainerDropComponent(Int64 entityId)
   at VRage.Network.CallSite`7.Invoke(BitStream stream, Object obj, Boolean validate)
   at VRage.Network.MyReplicationLayer.Invoke(CallSite callSite, BitStream stream, Object obj, EndpointId source, MyClientStateBase clientState, Boolean validate)
   at VRage.Network.MyReplicationServer.OnEvent(MyPacketDataBitStreamBase data, CallSite site, Object obj, IMyNetObject sendAs, EndpointId source)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacketDataBitStreamBase data, NetworkId networkId, NetworkId blockedNetId, UInt32 eventId, EndpointId sender)
   at VRage.Network.MyReplicationLayer.ProcessEvent(MyPacketDataBitStreamBase data, EndpointId sender)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacket packet)
   at Torch.Managers.NetworkManager.OnEvent(MyPacket packet)
20:52:51.7187 [ERROR]  Keen: System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.Game.SessionComponents.MySessionComponentContainerDropSystem.RemoveContainerDropComponent(Int64 entityId)
   at VRage.Network.CallSite`7.Invoke(BitStream stream, Object obj, Boolean validate)
   at VRage.Network.MyReplicationLayer.Invoke(CallSite callSite, BitStream stream, Object obj, EndpointId source, MyClientStateBase clientState, Boolean validate)
   at VRage.Network.MyReplicationServer.OnEvent(MyPacketDataBitStreamBase data, CallSite site, Object obj, IMyNetObject sendAs, EndpointId source)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacketDataBitStreamBase data, NetworkId networkId, NetworkId blockedNetId, UInt32 eventId, EndpointId sender)
   at VRage.Network.MyReplicationLayer.ProcessEvent(MyPacketDataBitStreamBase data, EndpointId sender)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacket packet)
   at Torch.Managers.NetworkManager.OnEvent(MyPacket packet)
   at Sandbox.Engine.Multiplayer.MyTransportLayer.ProcessMessage(MyPacket p)
   at Sandbox.Engine.Multiplayer.MyTransportLayer.HandleMessage(MyPacket p)
   at Sandbox.Engine.Networking.MyReceiveQueue.Process(NetworkMessageDelegate handler)
System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.Game.SessionComponents.MySessionComponentContainerDropSystem.RemoveContainerDropComponent(Int64 entityId)
   at VRage.Network.CallSite`7.Invoke(BitStream stream, Object obj, Boolean validate)
   at VRage.Network.MyReplicationLayer.Invoke(CallSite callSite, BitStream stream, Object obj, EndpointId source, MyClientStateBase clientState, Boolean validate)
   at VRage.Network.MyReplicationServer.OnEvent(MyPacketDataBitStreamBase data, CallSite site, Object obj, IMyNetObject sendAs, EndpointId source)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacketDataBitStreamBase data, NetworkId networkId, NetworkId blockedNetId, UInt32 eventId, EndpointId sender)
   at VRage.Network.MyReplicationLayer.ProcessEvent(MyPacketDataBitStreamBase data, EndpointId sender)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacket packet)
   at Torch.Managers.NetworkManager.OnEvent(MyPacket packet)
   at Sandbox.Engine.Multiplayer.MyTransportLayer.ProcessMessage(MyPacket p)
   at Sandbox.Engine.Multiplayer.MyTransportLayer.HandleMessage(MyPacket p)
   at Sandbox.Engine.Networking.MyReceiveQueue.Process(NetworkMessageDelegate handler)
20:52:51.7457 [INFO]   Torch.Managers.MultiplayerManagerBase: evgenevih (76561198369879056) Disconnected.
```

![image](https://user-images.githubusercontent.com/1900106/46169722-2e2a2200-c29c-11e8-99b3-a26d74aea434.png)

He reported that the had long loading times while joining, with no progress. A reconnect after some time, worked.

**Comment by Fowlplaychiken** [comment]
Same issue for my DS

**Comment by rexxar-tc** [comment]
This looks like a Keen crash, not related to Torch.

**Comment by Fowlplaychiken** [comment]
It only started after the Torch + Essentials update. Not seen it prior, seen it regularly since immediately after update.

**Comment by Fank** [comment]
Can confirm it happend since the last update

**Comment by Fank** [comment]
I saw today that this issue prevents people from joining the server.
Is there any solution to fix this?
