### ISSUE TITLE
Torch throwing exception in vrage on startup

### ISSUE THREAD

**Issue by mccorkle** [TorchAPI/Torch#26]
How to reproduce:
* Load torch 1.0.136.343 with my space engineers world and torch config (I can provide both if needed to reproduce)
* Click start button
* watch text console.  The error will appear in red after ~ 2 minutes. 

What do I expect to happen?:
* server to launch without exception

**versions:**
Windows Server 2012 R2
Torch 1.0.136.343
SE 1.181.58 (with June 2nd hotfixes)

**Error:**
2017-06-02 17:44:34.3697 [INFO] Torch: Loading config C:\Program Files (x86)\Steam\steamapps\common\SpaceEngineers\DedicatedServer64\TorchConfig.xml
2017-06-02 17:44:34.7397 [INFO] Torch: RELEASE
2017-06-02 17:44:34.7397 [INFO] Torch: Torch 1.0.136.343, SE 1.181.58
2017-06-02 17:44:34.7397 [INFO] Torch: Executing assembly: Torch.Server, Version=1.0.136.343, Culture=neutral, PublicKeyToken=null
2017-06-02 17:44:34.7397 [INFO] Torch: Executing directory: C:\Program Files (x86)\Steam\steamapps\common\SpaceEngineers\DedicatedServer64\
2017-06-02 17:44:34.7397 [INFO] Torch: Init server 'Torch' at 'C:\ProgramData\SpaceEngineersDedicated\WhiskeyAndCookies-PVE'
2017-06-02 17:45:41.9586 [INFO] Torch: Starting server.
2017-06-02 17:45:42.637: Bind IP : 0.0.0.0:27016
Setting breakpad minidump AppID = 244850
2017-06-02 17:45:47.026: Server successfully started
2017-06-02 17:45:47.026: Product name: Space Engineers
2017-06-02 17:45:47.026: Desc: Space Engineers
2017-06-02 17:45:47.026: Public IP: 34.206.227.163
2017-06-02 17:45:47.026: Steam ID: 90109071845200896
2017-06-02 17:45:52.591: Loading last session C:\ProgramData\SpaceEngineersDedicated\WhiskeyAndCookies-PVE\Saves\Whiskey And Cookies(PVE)
2017-06-02 17:45:53.939: Server connected to Steam
2017-06-02 17:45:53.941: Server PolicyResponse (1)
2017-06-02 17:45:54.511: Up to date mod:  id = 316190120
2017-06-02 17:45:54.511: Up to date mod:  id = 320125359
2017-06-02 17:45:54.511: Up to date mod:  id = 328494103
2017-06-02 17:45:54.512: Up to date mod:  id = 364731781
2017-06-02 17:45:54.512: Up to date mod:  id = 484504816
2017-06-02 17:45:54.513: Up to date mod:  id = 500818376
2017-06-02 17:45:54.513: Up to date mod:  id = 502782983
2017-06-02 17:45:54.513: Up to date mod:  id = 502784953
2017-06-02 17:45:54.514: Up to date mod:  id = 531851337
2017-06-02 17:45:54.514: Up to date mod:  id = 562591320
2017-06-02 17:45:54.515: Up to date mod:  id = 570766073
2017-06-02 17:45:54.515: Up to date mod:  id = 570767247
2017-06-02 17:45:54.515: Up to date mod:  id = 595665128
2017-06-02 17:45:54.516: Up to date mod:  id = 643820962
2017-06-02 17:45:54.516: Up to date mod:  id = 646084488
2017-06-02 17:45:54.516: Up to date mod:  id = 647256866
2017-06-02 17:45:54.517: Up to date mod:  id = 655922051
2017-06-02 17:45:54.517: Up to date mod:  id = 685986346
2017-06-02 17:45:54.518: Up to date mod:  id = 688819658
2017-06-02 17:45:54.518: Up to date mod:  id = 709189094
2017-06-02 17:45:54.518: Up to date mod:  id = 709997713
2017-06-02 17:45:54.519: Up to date mod:  id = 719015315
2017-06-02 17:45:54.519: Up to date mod:  id = 725801285
2017-06-02 17:45:54.520: Up to date mod:  id = 728555954
2017-06-02 17:45:54.520: Up to date mod:  id = 775214124
2017-06-02 17:45:54.520: Up to date mod:  id = 824449049
2017-06-02 17:45:54.521: Up to date mod:  id = 842998839
2017-06-02 17:45:54.521: Up to date mod:  id = 856019339
2017-06-02 17:45:54.521: Up to date mod:  id = 901545502
2017-06-02 17:45:54.586: Loading session: C:\ProgramData\SpaceEngineersDedicated\WhiskeyAndCookies-PVE\Saves\Whiskey And Cookies(PVE)
2017-06-02 17:48:13.401: Session loaded
2017-06-02 17:48:13.753: Logging off Steam...
2017-06-02 17:48:13.754: Shutting down server...
2017-06-02 17:48:13.781: Done
2017-06-02 17:48:13.820 [FATAL] Torch: System.Reflection.TargetInvocationExcept ion: Exception has been thrown by the target of an invocation. ---> System.InvalidCastException: Unable to cast object of type 'System.Collections.Generic.Dictionary`2[Sandbox.Engine.Multiplayer.MyTransportLayer+HandlerId,System.Action`1[VRage.MyPacket]]' to type 'System.Collections.Generic.Dictionary`2[Sandbox.Engine.Multiplayer.MyMessageId,System.Action`1[VRage.MyPacket]]'.
   at Torch.Managers.NetworkManager.Init()
   at Torch.TorchBase.Init(Object gameInstance)
   at Torch.Server.TorchServer.Init(Object gameInstance)
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashSc reen)
   at VRage.Dedicated.DedicatedServer.RunInternal()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments,  Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Objec t[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invoke  Attr, Binder binder, Object[] parameters, CultureInfo culture)
   at Torch.Server.TorchServer.Start()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionCo ntext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, C ontextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Mod List:**
901545502
856019339
842998839
824449049
775214124
728555954
725801285
719015315
709997713
709189094
688819658
685986346
655922051
647256866
646084488
643820962
595665128
570766073
570767247
562591320
531851337
502782983
502784953
500818376
484504816
364731781
328494103
320125359
316190120

**Comment by Jimmacle** [comment]
Keen made some major changes that broke the network intercept (again), this may take a while to fix.

**Comment by mccorkle** [comment]
Thank you for the follow up @Jimmacle -- get it fixed when you can and let me know when I can test the next release.

**Comment by Jimmacle** [comment]
Resolved c40b17ac30fa6d0b618c1962db407cd0350c607d

**Comment by mccorkle** [comment]
Awesome work @Jimmacle -- you save the day once again!

Tested and confirmed launch and simspeed 1.00

No other changes to server except for updating to 1.0.153.575.

* Torch 1.0.153.575
* SE 1.181.58
