### ISSUE TITLE
drop items bug

### ISSUE THREAD

**Issue by jusitnboggs** [TorchAPI/Torch#265]
- [ ] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [ ] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:** 1.3.0.81 **SE Version:** 1.188.25

### Expected Behavior
What did you expect to happen?

### Observed Behavior
What actually happened?
Happens when dropping a large number of items from inv
### Steps to Reproduce
1. How did this issue get triggered?
2. Write the steps here.

### Other Information
Provide links to game logs or saves here if necessary.

03:22:48.6444 [ERROR]  NetworkManager: Error processing network event!
System.InvalidOperationException: Nullable object must have a value.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at Sandbox.Game.MyInventory.DropItem_Implementation(MyFixedPoint amount, UInt32 itemIndex)
   at lambda_method(Closure , MyInventory , MyFixedPoint , UInt32 , DBNull , DBNull , DBNull , DBNull )
   at VRage.Network.CallSite`7.Invoke(BitStream stream, Object obj, Boolean validate)
   at VRage.Network.MyReplicationLayer.Invoke(CallSite callSite, BitStream stream, Object obj, EndpointId source, MyClientStateBase clientState, Boolean validate)
   at VRage.Network.MyReplicationServer.OnEvent(MyPacketDataBitStreamBase data, CallSite site, Object obj, IMyNetObject sendAs, Nullable`1 position, EndpointId source)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacketDataBitStreamBase data, NetworkId networkId, NetworkId blockedNetId, UInt32 eventId, EndpointId sender, Nullable`1 position)
   at VRage.Network.MyReplicationLayer.ProcessEvent(MyPacketDataBitStreamBase data, EndpointId sender)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacket packet)
   at Torch.Managers.NetworkManager.OnEvent(MyPacket packet) in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_master-MDSK25APJZH3CKHWQZDBKPUEFGHPIOFDYJGXZQ5Z5BITFXNFOV5A\Torch\Managers\NetworkManager\NetworkManager.cs:line 222
03:22:48.7665 [ERROR]  NetworkManager: System.InvalidOperationException: Nullable object must have a value.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at Sandbox.Game.MyInventory.DropItem_Implementation(MyFixedPoint amount, UInt32 itemIndex)
   at lambda_method(Closure , MyInventory , MyFixedPoint , UInt32 , DBNull , DBNull , DBNull , DBNull )
   at VRage.Network.CallSite`7.Invoke(BitStream stream, Object obj, Boolean validate)
   at VRage.Network.MyReplicationLayer.Invoke(CallSite callSite, BitStream stream, Object obj, EndpointId source, MyClientStateBase clientState, Boolean validate)
   at VRage.Network.MyReplicationServer.OnEvent(MyPacketDataBitStreamBase data, CallSite site, Object obj, IMyNetObject sendAs, Nullable`1 position, EndpointId source)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacketDataBitStreamBase data, NetworkId networkId, NetworkId blockedNetId, UInt32 eventId, EndpointId sender, Nullable`1 position)
   at VRage.Network.MyReplicationLayer.ProcessEvent(MyPacketDataBitStreamBase data, EndpointId sender)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacket packet)
   at Torch.Managers.NetworkManager.OnEvent(MyPacket packet) in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_master-MDSK25APJZH3CKHWQZDBKPUEFGHPIOFDYJGXZQ5Z5BITFXNFOV5A\Torch\Managers\NetworkManager\NetworkManager.cs:line 222
System.InvalidOperationException: Nullable object must have a value.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at Sandbox.Game.MyInventory.DropItem_Implementation(MyFixedPoint amount, UInt32 itemIndex)
   at lambda_method(Closure , MyInventory , MyFixedPoint , UInt32 , DBNull , DBNull , DBNull , DBNull )
   at VRage.Network.CallSite`7.Invoke(BitStream stream, Object obj, Boolean validate)
   at VRage.Network.MyReplicationLayer.Invoke(CallSite callSite, BitStream stream, Object obj, EndpointId source, MyClientStateBase clientState, Boolean validate)
   at VRage.Network.MyReplicationServer.OnEvent(MyPacketDataBitStreamBase data, CallSite site, Object obj, IMyNetObject sendAs, Nullable`1 position, EndpointId source)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacketDataBitStreamBase data, NetworkId networkId, NetworkId blockedNetId, UInt32 eventId, EndpointId sender, Nullable`1 position)
   at VRage.Network.MyReplicationLayer.ProcessEvent(MyPacketDataBitStreamBase data, EndpointId sender)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacket packet)
   at Torch.Managers.NetworkManager.OnEvent(MyPacket packet) in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_master-MDSK25APJZH3CKHWQZDBKPUEFGHPIOFDYJGXZQ5Z5BITFXNFOV5A\Torch\Managers\NetworkManager\NetworkManager.cs:line 222
03:22:48.7665 [ERROR]  Keen: System.InvalidOperationException: Nullable object must have a value.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at Sandbox.Game.MyInventory.DropItem_Implementation(MyFixedPoint amount, UInt32 itemIndex)
   at lambda_method(Closure , MyInventory , MyFixedPoint , UInt32 , DBNull , DBNull , DBNull , DBNull )
   at VRage.Network.CallSite`7.Invoke(BitStream stream, Object obj, Boolean validate)
   at VRage.Network.MyReplicationLayer.Invoke(CallSite callSite, BitStream stream, Object obj, EndpointId source, MyClientStateBase clientState, Boolean validate)
   at VRage.Network.MyReplicationServer.OnEvent(MyPacketDataBitStreamBase data, CallSite site, Object obj, IMyNetObject sendAs, Nullable`1 position, EndpointId source)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacketDataBitStreamBase data, NetworkId networkId, NetworkId blockedNetId, UInt32 eventId, EndpointId sender, Nullable`1 position)
   at VRage.Network.MyReplicationLayer.ProcessEvent(MyPacketDataBitStreamBase data, EndpointId sender)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacket packet)
   at Torch.Managers.NetworkManager.OnEvent(MyPacket packet) in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_master-MDSK25APJZH3CKHWQZDBKPUEFGHPIOFDYJGXZQ5Z5BITFXNFOV5A\Torch\Managers\NetworkManager\NetworkManager.cs:line 220
   at Sandbox.Engine.Multiplayer.MyTransportLayer.ProcessMessage(MyPacket p)
   at Sandbox.Engine.Multiplayer.MyTransportLayer.HandleMessage(MyPacket p)
   at Sandbox.Engine.Networking.MyReceiveQueue.Process(NetworkMessageDelegate handler)
System.InvalidOperationException: Nullable object must have a value.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at Sandbox.Game.MyInventory.DropItem_Implementation(MyFixedPoint amount, UInt32 itemIndex)
   at lambda_method(Closure , MyInventory , MyFixedPoint , UInt32 , DBNull , DBNull , DBNull , DBNull )
   at VRage.Network.CallSite`7.Invoke(BitStream stream, Object obj, Boolean validate)
   at VRage.Network.MyReplicationLayer.Invoke(CallSite callSite, BitStream stream, Object obj, EndpointId source, MyClientStateBase clientState, Boolean validate)
   at VRage.Network.MyReplicationServer.OnEvent(MyPacketDataBitStreamBase data, CallSite site, Object obj, IMyNetObject sendAs, Nullable`1 position, EndpointId source)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacketDataBitStreamBase data, NetworkId networkId, NetworkId blockedNetId, UInt32 eventId, EndpointId sender, Nullable`1 position)
   at VRage.Network.MyReplicationLayer.ProcessEvent(MyPacketDataBitStreamBase data, EndpointId sender)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacket packet)
   at Torch.Managers.NetworkManager.OnEvent(MyPacket packet) in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_master-MDSK25APJZH3CKHWQZDBKPUEFGHPIOFDYJGXZQ5Z5BITFXNFOV5A\Torch\Managers\NetworkManager\NetworkManager.cs:line 220
   at Sandbox.Engine.Multiplayer.MyTransportLayer.ProcessMessage(MyPacket p)
   at Sandbox.Engine.Multiplayer.MyTransportLayer.HandleMessage(MyPacket p)
   at Sandbox.Engine.Networking.MyReceiveQueue.Process(NetworkMessageDelegate handler)

**Comment by Jimmacle** [comment]
Not Torch related, vanilla SE has a ton of these types of network bugs
