### ISSUE TITLE
System.IndexOutOfRangeException immediately after Concealment: Revealing grids

### ISSUE THREAD

**Issue by mccorkle** [TorchAPI/Torch#27]
How to reproduce:
* Start a server
* have a few people log in
* wait

Versions:
Torch 1.0.153.575
SE 1.181.58
Windows Server 2012 R2

It looks like it happened at the end of a long list of "Revealing grids".  I will include the full torch.log as an attachment

**Exception from Torch.log**
2017-06-02 22:49:04.8767 [INFO] Concealment: Revealing grids: Static Grid 6164
2017-06-02 22:49:04.8767 [INFO] Concealment: Revealing grids: Military Minelayer
2017-06-02 22:49:04.9517 [FATAL] Torch: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at VRageMath.MyDynamicAABBTreeD.RemoveLeaf(Int32 leaf)
   at VRageMath.MyDynamicAABBTreeD.RemoveProxy(Int32 proxyId)
   at Concealment.ConcealmentPlugin.RevealGroup(ConcealGroup group)
   at Concealment.ConcealmentPlugin.<>c__DisplayClass21_0.<RevealSpawns>b__0()
   at Sandbox.MySandboxGame.ProcessInvoke()
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass1.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at VRage.Dedicated.DedicatedServer.RunInternal()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Torch.Server.TorchServer.Start()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**SpaceEngineersDedicated.log from around the same time**
2017-06-02 22:47:49.645 - Thread:  12 ->  GC Memory: 2,254,355,184 B
2017-06-02 22:48:19.654 - Thread:  12 ->  GC Memory: 2,285,648,824 B
2017-06-02 22:48:37.668 - Thread:  12 ->  Peer2Peer_SessionRequest 76561198067690153
2017-06-02 22:48:41.350 - Thread:  12 ->  OnConnectedClient SHO attempt
2017-06-02 22:48:41.653 - Thread:  12 ->  World request received: SHO
2017-06-02 22:48:41.653 - Thread:  12 ->  ...responding
2017-06-02 22:48:49.669 - Thread:  12 ->  GC Memory: 2,316,760,048 B
2017-06-02 22:49:04.729 - Thread:  12 ->  Network readers disposed
2017-06-02 22:49:04.733 - Thread:  12 ->  Logging off Steam...
2017-06-02 22:49:04.734 - Thread:  12 ->  Shutting down server...
2017-06-02 22:49:04.778 - Thread:  12 ->  Done
2017-06-02 22:53:41.448 - Thread:   1 ->  Saving world - START
2017-06-02 22:53:41.448 - Thread:   1 ->     Making world state snapshot.
2017-06-02 22:53:41.448 - Thread:   1 ->     Before snapshot.: GC Memory: 2,198,209,144 B

[SpaceEngineersDedicated.log.txt](https://github.com/TorchAPI/Torch/files/1049346/SpaceEngineersDedicated.log.txt)
[torch.log.txt](https://github.com/TorchAPI/Torch/files/1049347/torch.log.txt)

**Comment by mccorkle** [comment]
Keen updated SE today to 1.181.59:
* Torch 1.0.153.575
* SE 1.181.59 (upgraded from 58)
* Windows Server 2012 R2

Same class of error:
* Torch: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.

[Torch.log.txt](https://github.com/TorchAPI/Torch/files/1049648/Torch.log.txt)
[SpaceEngineersDedicated.log.txt](https://github.com/TorchAPI/Torch/files/1049647/SpaceEngineersDedicated.log.txt)

**Comment by mccorkle** [comment]
Possibly resolved by SE 1.181.61 -- still verifying.  Need more users doing user things to test.  Will update later today.

**Comment by mccorkle** [comment]
As of Torch 1.0.153.575 and SE 1.181.62, I am no longer seeing this error.  I am closing here and will re-open if the same crash happens again.

**Comment by mccorkle** [comment]
Crashed took about 30 minutes on a live server to reproduce, but it did happen again this morning.
* Torch 1.0.153.575
* SE 1.181.62

Attaching appropriate logs.  

[SpaceEngineersDedicated.log.txt](https://github.com/TorchAPI/Torch/files/1055658/SpaceEngineersDedicated.log.txt)
[Torch.log.txt](https://github.com/TorchAPI/Torch/files/1055659/Torch.log.txt)

**Comment by Jimmacle** [comment]
Looks like for some reason it is indeed trying to reveal a grid group twice. Pretty easy fix, I'll push it today.
