### ISSUE TITLE
Update error from Torch During update(SE Playtest)

### ISSUE THREAD

**Issue by flamepyro** [TorchAPI/Torch#271]
**Torch Version:** 1.3.0.92-176-g8b7a07f **SE Version:** 1.189.020 playtest

### Expected Behavior
Not error

### Observed Behavior
Errored during update but continued like normal

### Steps to Reproduce
1. How did this issue get triggered?
SE Playtest, Date: 1/17/19
2. Added the playtest to the Runscripts.txt and launched torch

### Other Information
11:01:09.7979 [ERROR]  Torch.Utils.ReflectedManager: Unable to fill Torch.Managers.ChatManager.ChatManagerClient#_hudChatMessageReceived. Unable to find instance method Multiplayer_ChatMessageReceived in type Sandbox.Game.Gui.MyHudChat with parameters UInt64, String
System.Data.NoNullAllowedException: Unable to find instance method Multiplayer_ChatMessageReceived in type Sandbox.Game.Gui.MyHudChat with parameters UInt64, String
   at Torch.Utils.ReflectedManager.ProcessReflectedMethod(FieldInfo field, ReflectedMethodAttribute attr) in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_master-MDSK25APJZH3CKHWQZDBKPUEFGHPIOFDYJGXZQ5Z5BITFXNFOV5A\Torch\Utils\Reflected\ReflectedManager.cs:line 189
   at Torch.Utils.ReflectedManager.Process(FieldInfo field) in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_master-MDSK25APJZH3CKHWQZDBKPUEFGHPIOFDYJGXZQ5Z5BITFXNFOV5A\Torch\Utils\Reflected\ReflectedManager.cs:line 101
   at Torch.Utils.ReflectedManager.Process(Type t) in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_master-MDSK25APJZH3CKHWQZDBKPUEFGHPIOFDYJGXZQ5Z5BITFXNFOV5A\Torch\Utils\Reflected\ReflectedManager.cs:line 62

**Comment by Jimmacle** [comment]
Looks like dead code from the old client version is the source of the error, it should be ignorable until we remove the offending code.

**Comment by Jimmacle** [comment]
Closing as this is fixed on the playtest branch.
