### ISSUE TITLE
Fatal error on torch start(SE Playtest 1/17/19)

### ISSUE THREAD

**Issue by flamepyro** [TorchAPI/Torch#272]
Torch Version: 1.3.0.92-176-g8b7a07f SE Version: 1.189.020 playtest

Expected Behavior
Normal Start

Observed Behavior
Fatal error when trying to start torch Server

Steps to Reproduce
How did this issue get triggered?
SE Playtest, Date: 1/17/19
Added the playtest to the Runscripts.txt and launched torch
Other Information
11:26:15.4864 [INFO]   SteamCMD: Checking for DS updates.
11:26:16.2344 [INFO]   SteamCMD: Steam Console Client (c) Valve Corporation
11:26:16.3354 [INFO]   SteamCMD: -- type 'quit' to exit --
11:26:16.4364 [INFO]   SteamCMD: Loading Steam API...OK.
11:26:16.5374 [INFO]   SteamCMD: 
11:26:17.0344 [INFO]   SteamCMD: Connecting anonymously to Steam Public...Logged in OK
11:26:17.1354 [INFO]   SteamCMD: Waiting for user info...OK
11:26:18.2824 [INFO]   SteamCMD: Success! App '298740' already up to date.
11:26:18.4514 [INFO]   SteamCMD: 
11:26:18.5524 [INFO]   Initializer: Loading config C:\Steam Servers\Space Engineers\33 Vega - Survival Playtest\Torch.cfg
11:26:18.6603 [ERROR]  Torch.Utils.ReflectedManager: Unable to fill Torch.Managers.ChatManager.ChatManagerClient#_hudChatMessageReceived. Unable to find instance method Multiplayer_ChatMessageReceived in type Sandbox.Game.Gui.MyHudChat with parameters UInt64, String
System.Data.NoNullAllowedException: Unable to find instance method Multiplayer_ChatMessageReceived in type Sandbox.Game.Gui.MyHudChat with parameters UInt64, String
   at Torch.Utils.ReflectedManager.ProcessReflectedMethod(FieldInfo field, ReflectedMethodAttribute attr) in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_master-MDSK25APJZH3CKHWQZDBKPUEFGHPIOFDYJGXZQ5Z5BITFXNFOV5A\Torch\Utils\Reflected\ReflectedManager.cs:line 189
   at Torch.Utils.ReflectedManager.Process(FieldInfo field) in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_master-MDSK25APJZH3CKHWQZDBKPUEFGHPIOFDYJGXZQ5Z5BITFXNFOV5A\Torch\Utils\Reflected\ReflectedManager.cs:line 101
   at Torch.Utils.ReflectedManager.Process(Type t) in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_master-MDSK25APJZH3CKHWQZDBKPUEFGHPIOFDYJGXZQ5Z5BITFXNFOV5A\Torch\Utils\Reflected\ReflectedManager.cs:line 62
11:26:18.6993 [INFO]   Torch.Managers.PatchManager.PatchManager: Patching begins...
11:26:18.8323 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 2/12.  (16%)
11:26:19.7263 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 3/12.  (25%)
11:26:19.7293 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 4/12.  (33%)
11:26:19.7293 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 5/12.  (41%)
11:26:19.7293 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 6/12.  (50%)
11:26:19.7293 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 8/12.  (66%)
11:26:19.7293 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 9/12.  (75%)
11:26:19.7293 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 10/12.  (83%)
11:26:19.7293 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 11/12.  (91%)
11:26:19.7293 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 12/12.  (100%)
11:26:19.7293 [INFO]   Torch.Managers.PatchManager.PatchManager: Patching done
11:26:19.8303 [INFO]   Initializer: Showing UI
11:26:19.8303 [INFO]   Torch: Initializing server
11:26:20.3153 [INFO]   Torch: RELEASE
11:26:20.3153 [INFO]   Torch: Torch Version: v1.3.0.92-176-g8b7a07f
11:26:20.3153 [INFO]   Torch: Game Version: 1.189.20
11:26:20.3153 [INFO]   Torch: Executing assembly: Torch.Server, Version=1.3.0.92, Culture=neutral, PublicKeyToken=null
11:26:20.3153 [INFO]   Torch: Executing directory: C:\Steam Servers\Space Engineers\33 Vega - Survival Playtest\
11:26:20.3153 [WARN]   Torch.Managers.PluginManager: Automatic plugin updates are disabled in this build of Torch while the system is reworked.
11:26:20.3153 [INFO]   Torch.Managers.PluginManager: Loading plugins...
11:26:20.3223 [INFO]   Torch.Managers.PluginManager: Loaded 0 plugins.
11:26:21.8023 [INFO]   Torch.VRageGame: Setting up serializers
11:26:23.7713 [INFO]   InstanceManager: Loading instance C:\Steam Servers\Space Engineers\33 Vega - Survival Playtest\Instance
11:26:23.8203 [INFO]   Torch.Server.Managers.WorldViewModel: Preloading checkpoint C:\Steam Servers\Space Engineers\33 Vega - Survival Playtest\Instance\Saves\33 Vega - Survival Playtest\Sandbox.sbc
11:26:24.4723 [INFO]   Torch: Initialized server 'Torch' at 'C:\Steam Servers\Space Engineers\33 Vega - Survival Playtest\Instance'
11:26:27.2713 [INFO]   InstanceManager: Saved dedicated config.
11:26:27.4593 [INFO]   InstanceManager: Saved world config.
11:26:27.4633 [INFO]   Torch: Starting server.
11:26:27.4893 [INFO]   Torch: Remote API started on port 8080
11:26:32.3853 [INFO]   Torch.Managers.PatchManager.PatchManager: Patching begins...
11:26:32.3853 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 1/3.  (33%)
11:26:32.3853 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 2/3.  (66%)
11:26:32.3853 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 3/3.  (100%)
11:26:32.3853 [INFO]   Torch.Managers.PatchManager.PatchManager: Patching done
11:26:32.4123 [INFO]   Torch.Managers.PatchManager.PatchManager: Patching begins...
11:26:32.4123 [INFO]   Torch.Managers.PatchManager.PatchManager: Patching done
11:26:39.0522 [INFO]   Torch.Session.TorchSessionManager: Starting new torch session for 33 Vega - Unoffical Survival Playtest
11:26:39.5562 [WARN]   Keen:    Missing definition MyObjectBuilder_DemoComponentDefinition/Default : for session component DemoComponent
11:26:42.6662 [INFO]   Torch.Server.Managers.MultiplayerManagerDedicated: Inserted steam authentication intercept
11:26:42.6662 [ERROR]  Torch.Session.TorchSessionManager: System.MissingMethodException: Method not found: 'Void Sandbox.Engine.Multiplayer.MyMultiplayerBase.add_ChatMessageReceived(System.Action`2<UInt64,System.String>)'.
   at Torch.Managers.ChatManager.ChatManagerServer.Attach()
   at Torch.Managers.DependencyManager.Attach() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_master-MDSK25APJZH3CKHWQZDBKPUEFGHPIOFDYJGXZQ5Z5BITFXNFOV5A\Torch\Managers\DependencyManager.cs:line 250
   at Torch.Session.TorchSessionManager.SessionLoaded() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_master-MDSK25APJZH3CKHWQZDBKPUEFGHPIOFDYJGXZQ5Z5BITFXNFOV5A\Torch\Session\TorchSessionManager.cs:line 100
System.MissingMethodException: Method not found: 'Void Sandbox.Engine.Multiplayer.MyMultiplayerBase.add_ChatMessageReceived(System.Action`2<UInt64,System.String>)'.
   at Torch.Managers.ChatManager.ChatManagerServer.Attach()
   at Torch.Managers.DependencyManager.Attach() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_master-MDSK25APJZH3CKHWQZDBKPUEFGHPIOFDYJGXZQ5Z5BITFXNFOV5A\Torch\Managers\DependencyManager.cs:line 250
   at Torch.Session.TorchSessionManager.SessionLoaded() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_master-MDSK25APJZH3CKHWQZDBKPUEFGHPIOFDYJGXZQ5Z5BITFXNFOV5A\Torch\Session\TorchSessionManager.cs:line 100
11:26:42.6662 [INFO]   Torch.Session.TorchSessionManager: Unloading torch session for 33 Vega - Unoffical Survival Playtest
11:26:42.6832 [ERROR]  Torch.Session.TorchSessionManager: System.MissingMethodException: Method not found: 'Void Sandbox.Engine.Multiplayer.MyMultiplayerBase.remove_ChatMessageReceived(System.Action`2<UInt64,System.String>)'.
   at Torch.Managers.ChatManager.ChatManagerServer.Detach()
   at Torch.Managers.DependencyManager.Detach() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_master-MDSK25APJZH3CKHWQZDBKPUEFGHPIOFDYJGXZQ5Z5BITFXNFOV5A\Torch\Managers\DependencyManager.cs:line 264
   at Torch.Session.TorchSessionManager.SessionUnloading() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_master-MDSK25APJZH3CKHWQZDBKPUEFGHPIOFDYJGXZQ5Z5BITFXNFOV5A\Torch\Session\TorchSessionManager.cs:line 121
System.MissingMethodException: Method not found: 'Void Sandbox.Engine.Multiplayer.MyMultiplayerBase.remove_ChatMessageReceived(System.Action`2<UInt64,System.String>)'.
   at Torch.Managers.ChatManager.ChatManagerServer.Detach()
   at Torch.Managers.DependencyManager.Detach() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_master-MDSK25APJZH3CKHWQZDBKPUEFGHPIOFDYJGXZQ5Z5BITFXNFOV5A\Torch\Managers\DependencyManager.cs:line 264
   at Torch.Session.TorchSessionManager.SessionUnloading() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_master-MDSK25APJZH3CKHWQZDBKPUEFGHPIOFDYJGXZQ5Z5BITFXNFOV5A\Torch\Session\TorchSessionManager.cs:line 121
11:26:42.6832 [FATAL]  Initializer: System.MissingMethodException: Method not found: 'Void Sandbox.Engine.Multiplayer.MyMultiplayerBase.remove_ChatMessageReceived(System.Action`2<UInt64,System.String>)'.
   at Torch.Managers.ChatManager.ChatManagerServer.Detach()
   at Torch.Managers.DependencyManager.Detach() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_master-MDSK25APJZH3CKHWQZDBKPUEFGHPIOFDYJGXZQ5Z5BITFXNFOV5A\Torch\Managers\DependencyManager.cs:line 264
   at Torch.Session.TorchSessionManager.SessionUnloading() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_master-MDSK25APJZH3CKHWQZDBKPUEFGHPIOFDYJGXZQ5Z5BITFXNFOV5A\Torch\Session\TorchSessionManager.cs:line 126
   at Sandbox.Game.World.MySession.Unload()
   at Sandbox.MySandboxGame.UnloadData_UpdateThread()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at Torch.VRageGame.DoStart() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_master-MDSK25APJZH3CKHWQZDBKPUEFGHPIOFDYJGXZQ5Z5BITFXNFOV5A\Torch\VRageGame.cs:line 241
   at Torch.VRageGame.Run() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_master-MDSK25APJZH3CKHWQZDBKPUEFGHPIOFDYJGXZQ5Z5BITFXNFOV5A\Torch\VRageGame.cs:line 118
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
System.MissingMethodException: Method not found: 'Void Sandbox.Engine.Multiplayer.MyMultiplayerBase.remove_ChatMessageReceived(System.Action`2<UInt64,System.String>)'.
   at Torch.Managers.ChatManager.ChatManagerServer.Detach()
   at Torch.Managers.DependencyManager.Detach() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_master-MDSK25APJZH3CKHWQZDBKPUEFGHPIOFDYJGXZQ5Z5BITFXNFOV5A\Torch\Managers\DependencyManager.cs:line 264
   at Torch.Session.TorchSessionManager.SessionUnloading() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_master-MDSK25APJZH3CKHWQZDBKPUEFGHPIOFDYJGXZQ5Z5BITFXNFOV5A\Torch\Session\TorchSessionManager.cs:line 126
   at Sandbox.Game.World.MySession.Unload()
   at Sandbox.MySandboxGame.UnloadData_UpdateThread()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at Torch.VRageGame.DoStart() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_master-MDSK25APJZH3CKHWQZDBKPUEFGHPIOFDYJGXZQ5Z5BITFXNFOV5A\Torch\VRageGame.cs:line 241
   at Torch.VRageGame.Run() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_master-MDSK25APJZH3CKHWQZDBKPUEFGHPIOFDYJGXZQ5Z5BITFXNFOV5A\Torch\VRageGame.cs:line 118
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
11:26:42.6832 [INFO]   Initializer: Generating minidump at C:\Steam Servers\Space Engineers\33 Vega - Survival Playtest\Instance\Minidump.dmp

MiniDump File:
https://1drv.ms/u/s!Aksp682vsaNnh79lBRumLyQ9v9RqtA
Torch Log:
https://1drv.ms/u/s!Aksp682vsaNnh79m0iOFkwX636Sk_A
Keen Log:
https://1drv.ms/u/s!Aksp682vsaNnh79nWcDdkI1IenTYQA

**Comment by Jimmacle** [comment]
Fixed on playtest branch
