### ISSUE TITLE
[ERROR]  NetworkManager: System.TypeLoadException: Could not load type 'Sandbox.Game.Entities.Character.MyPlayerChatHistory' from assembly 'Sandbox.Game, Version=0.1.6999.34332, Culture=neutral, PublicKeyToken=null

### ISSUE THREAD

**Issue by Alien6666** [TorchAPI/Torch#293]
**Torch Version:** 1.3.20.56 **SE Version:** 1.189.40

### Expected Behavior
Expected to be able to join the server.

### Observed Behavior
09:25:40.5974 [INFO]   SessionDownloadPatch: Preparing world for 76561198155829694...
09:25:40.6130 [ERROR]  NetworkManager: System.TypeLoadException: Could not load type 'Sandbox.Game.Entities.Character.MyPlayerChatHistory' from assembly 'Sandbox.Game, Version=0.1.6999.34332, Culture=neutral, PublicKeyToken=null'.
   at Essentials.Patches.SessionDownloadPatch.GetClientCheckpoint(UInt64 steamId)
   at Essentials.Patches.SessionDownloadPatch.GetClientWorld(EndpointId sender) in C:\jenkins\workspace\Torch_Essentials_master\Essentials\Patches\SessionDownloadPatch.cs:line 80
   at OnWorldRequest_0(Object , EndpointId )
   at Sandbox.Engine.Multiplayer.MyMultiplayerServerBase.WorldRequest()
   at VRage.Network.CallSite`7.Invoke(BitStream stream, Object obj, Boolean validate)
   at VRage.Network.MyReplicationLayer.Invoke(CallSite callSite, BitStream stream, Object obj, EndpointId source, MyClientStateBase clientState, Boolean validate)
   at VRage.Network.MyReplicationServer.OnEvent(MyPacketDataBitStreamBase data, CallSite site, Object obj, IMyNetObject sendAs, Nullable`1 position, EndpointId source)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacketDataBitStreamBase data, NetworkId networkId, NetworkId blockedNetId, UInt32 eventId, EndpointId sender, Nullable`1 position)
   at VRage.Network.MyReplicationLayer.ProcessEvent(MyPacketDataBitStreamBase data, EndpointId sender)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacket packet)
   at Torch.Managers.NetworkManager.OnEvent(MyPacket packet) in C:\jenkins\workspace\Torch_Torch_master\Torch\Managers\NetworkManager\NetworkManager_Deprecated.cs:line 268
System.TypeLoadException: Could not load type 'Sandbox.Game.Entities.Character.MyPlayerChatHistory' from assembly 'Sandbox.Game, Version=0.1.6999.34332, Culture=neutral, PublicKeyToken=null'.
   at Essentials.Patches.SessionDownloadPatch.GetClientCheckpoint(UInt64 steamId)
   at Essentials.Patches.SessionDownloadPatch.GetClientWorld(EndpointId sender) in C:\jenkins\workspace\Torch_Essentials_master\Essentials\Patches\SessionDownloadPatch.cs:line 80
   at OnWorldRequest_0(Object , EndpointId )
   at Sandbox.Engine.Multiplayer.MyMultiplayerServerBase.WorldRequest()
   at VRage.Network.CallSite`7.Invoke(BitStream stream, Object obj, Boolean validate)
   at VRage.Network.MyReplicationLayer.Invoke(CallSite callSite, BitStream stream, Object obj, EndpointId source, MyClientStateBase clientState, Boolean validate)
   at VRage.Network.MyReplicationServer.OnEvent(MyPacketDataBitStreamBase data, CallSite site, Object obj, IMyNetObject sendAs, Nullable`1 position, EndpointId source)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacketDataBitStreamBase data, NetworkId networkId, NetworkId blockedNetId, UInt32 eventId, EndpointId sender, Nullable`1 position)
   at VRage.Network.MyReplicationLayer.ProcessEvent(MyPacketDataBitStreamBase data, EndpointId sender)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacket packet)
   at Torch.Managers.NetworkManager.OnEvent(MyPacket packet) in C:\jenkins\workspace\Torch_Torch_master\Torch\Managers\NetworkManager\NetworkManager_Deprecated.cs:line 268
09:25:40.6286 [ERROR]  Keen: System.TypeLoadException: Could not load type 'Sandbox.Game.Entities.Character.MyPlayerChatHistory' from assembly 'Sandbox.Game, Version=0.1.6999.34332, Culture=neutral, PublicKeyToken=null'.
   at Essentials.Patches.SessionDownloadPatch.GetClientCheckpoint(UInt64 steamId)
   at Essentials.Patches.SessionDownloadPatch.GetClientWorld(EndpointId sender) in C:\jenkins\workspace\Torch_Essentials_master\Essentials\Patches\SessionDownloadPatch.cs:line 80
   at OnWorldRequest_0(Object , EndpointId )
   at Sandbox.Engine.Multiplayer.MyMultiplayerServerBase.WorldRequest()
   at VRage.Network.CallSite`7.Invoke(BitStream stream, Object obj, Boolean validate)
   at VRage.Network.MyReplicationLayer.Invoke(CallSite callSite, BitStream stream, Object obj, EndpointId source, MyClientStateBase clientState, Boolean validate)
   at VRage.Network.MyReplicationServer.OnEvent(MyPacketDataBitStreamBase data, CallSite site, Object obj, IMyNetObject sendAs, Nullable`1 position, EndpointId source)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacketDataBitStreamBase data, NetworkId networkId, NetworkId blockedNetId, UInt32 eventId, EndpointId sender, Nullable`1 position)
   at VRage.Network.MyReplicationLayer.ProcessEvent(MyPacketDataBitStreamBase data, EndpointId sender)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacket packet)
   at Torch.Managers.NetworkManager.OnEvent(MyPacket packet) in C:\jenkins\workspace\Torch_Torch_master\Torch\Managers\NetworkManager\NetworkManager_Deprecated.cs:line 279
   at Sandbox.Engine.Multiplayer.MyTransportLayer.ProcessMessage(MyPacket p)
   at Sandbox.Engine.Multiplayer.MyTransportLayer.HandleMessage(MyPacket p)
   at Sandbox.Engine.Networking.MyReceiveQueue.Process(NetworkMessageDelegate handler)
System.TypeLoadException: Could not load type 'Sandbox.Game.Entities.Character.MyPlayerChatHistory' from assembly 'Sandbox.Game, Version=0.1.6999.34332, Culture=neutral, PublicKeyToken=null'.
   at Essentials.Patches.SessionDownloadPatch.GetClientCheckpoint(UInt64 steamId)
   at Essentials.Patches.SessionDownloadPatch.GetClientWorld(EndpointId sender) in C:\jenkins\workspace\Torch_Essentials_master\Essentials\Patches\SessionDownloadPatch.cs:line 80
   at OnWorldRequest_0(Object , EndpointId )
   at Sandbox.Engine.Multiplayer.MyMultiplayerServerBase.WorldRequest()
   at VRage.Network.CallSite`7.Invoke(BitStream stream, Object obj, Boolean validate)
   at VRage.Network.MyReplicationLayer.Invoke(CallSite callSite, BitStream stream, Object obj, EndpointId source, MyClientStateBase clientState, Boolean validate)
   at VRage.Network.MyReplicationServer.OnEvent(MyPacketDataBitStreamBase data, CallSite site, Object obj, IMyNetObject sendAs, Nullable`1 position, EndpointId source)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacketDataBitStreamBase data, NetworkId networkId, NetworkId blockedNetId, UInt32 eventId, EndpointId sender, Nullable`1 position)
   at VRage.Network.MyReplicationLayer.ProcessEvent(MyPacketDataBitStreamBase data, EndpointId sender)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacket packet)
   at Torch.Managers.NetworkManager.OnEvent(MyPacket packet) in C:\jenkins\workspace\Torch_Torch_master\Torch\Managers\NetworkManager\NetworkManager_Deprecated.cs:line 279
   at Sandbox.Engine.Multiplayer.MyTransportLayer.ProcessMessage(MyPacket p)
   at Sandbox.Engine.Multiplayer.MyTransportLayer.HandleMessage(MyPacket p)
   at Sandbox.Engine.Networking.MyReceiveQueue.Process(NetworkMessageDelegate handler)

### Steps to Reproduce
1. Updated all to latest version.
2. Start torch server.
3. Try to join server.

### Other Information
Provide links to game logs or saves here if necessary.

**Comment by Jimmacle** [comment]
Update the Essentials plugin from the website.
