### ISSUE TITLE
New set up, fatal error on server start. 

### ISSUE THREAD

**Issue by LumberingTroll** [TorchAPI/Torch#328]
14:38:52.4581 [INFO]   Torch: Starting server.
14:39:00.6433 [INFO]   Keen:    Error binding server endpoint: The requested address is not valid in its context
14:39:00.6433 [FATAL]  Initializer: System.Exception: Fatal error during dedicated server init see log for more information.
   at .ctor_0(Object , String[] )
   at Torch.VRageGame.DoStart() in C:\jenkins\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 235
   at Torch.VRageGame.Run() in C:\jenkins\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 119
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
System.Exception: Fatal error during dedicated server init see log for more information.
   at .ctor_0(Object , String[] )
   at Torch.VRageGame.DoStart() in C:\jenkins\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 235
   at Torch.VRageGame.Run() in C:\jenkins\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 119
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
14:39:00.6593 [INFO]   Initializer: Generating minidump at P:\Torch\Instance\Minidump.dmp
14:39:00.6593 [ERROR]  Initializer: Keen broke the minidump, sorry.

[Keen-2019-07-08.log](https://github.com/TorchAPI/Torch/files/3369979/Keen-2019-07-08.log)
[Torch-2019-07-08.log](https://github.com/TorchAPI/Torch/files/3369980/Torch-2019-07-08.log)

**Comment by LumberingTroll** [comment]
No issue, just me not configuring it right. I needed to set the IP to the local IP, not my WAN IP.
