### ISSUE TITLE
Torch Fatal Error

### ISSUE THREAD

**Issue by ItzzGamma** [TorchAPI/Torch#333]
- [x] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [x] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:** v1.3.1.64-master **SE Version:** 1.191.108

### Expected Behavior
What did you expect to happen?
The menu for roles woud open

### Observed Behavior
What actually happened?
The client exited with a fatal error.

### Steps to Reproduce
1. How did this issue get triggered?
By me clicking Roles on configuration.
2. Write the steps here.
Opened Torch, went to configuration and clicked edit roles

### Other Information
Provide links to game logs or saves here if necessary.

06:22:15.8649 [INFO]   SteamCMD: Checking for DS updates.
06:22:19.3027 [INFO]   SteamCMD: Steam Console Client (c) Valve Corporation
06:22:19.4277 [INFO]   SteamCMD: -- type 'quit' to exit --
06:22:19.5371 [INFO]   SteamCMD: Loading Steam API...OK.
06:22:19.6464 [INFO]   SteamCMD: 
06:22:22.5342 [INFO]   SteamCMD: Connecting anonymously to Steam Public...Logged in OK
06:22:22.6436 [INFO]   SteamCMD: Waiting for user info...OK
06:22:24.0031 [INFO]   SteamCMD: Success! App '298740' already up to date.
06:22:24.3937 [INFO]   SteamCMD: force_install_dir ../
06:22:24.5031 [INFO]   Initializer: Loading config C:\Users\Administrator\Desktop\Torch\Torch.cfg
06:22:24.9094 [INFO]   Torch.Managers.PatchManager.PatchManager: Patching begins...
06:22:25.3156 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 2/12.  (16%)
06:22:27.3471 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 3/12.  (25%)
06:22:27.3471 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 4/12.  (33%)
06:22:27.3627 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 5/12.  (41%)
06:22:27.3627 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 6/12.  (50%)
06:22:27.3627 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 8/12.  (66%)
06:22:27.3627 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 9/12.  (75%)
06:22:27.3627 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 10/12.  (83%)
06:22:27.3627 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 11/12.  (91%)
06:22:27.3627 [INFO]   Torch.Managers.PatchManager.PatchManager: Patched 12/12.  (100%)
06:22:27.3627 [INFO]   Torch.Managers.PatchManager.PatchManager: Patching done
06:22:27.4565 [INFO]   Torch.Patches.PromotePatch: patching promote
06:22:27.5190 [INFO]   Initializer: Showing UI
06:22:27.5190 [INFO]   Torch: Initializing server
06:22:28.5503 [INFO]   Torch: RELEASE
06:22:28.5503 [INFO]   Torch: Torch Version: v1.3.1.64-master
06:22:28.5503 [INFO]   Torch: Game Version: 1.191.108
06:22:28.5503 [INFO]   Torch: Executing assembly: Torch.Server, Version=1.3.1.64, Culture=neutral, PublicKeyToken=null
06:22:28.5503 [INFO]   Torch: Executing directory: C:\Users\Administrator\Desktop\Torch\
06:22:28.5815 [INFO]   Torch.Managers.PluginManager: Checking for plugin updates...
06:22:28.5815 [INFO]   Torch.Managers.PluginManager: Updated 0 plugins.
06:22:28.5815 [INFO]   Torch.Managers.PluginManager: Loading plugins...
06:22:28.5972 [INFO]   Torch.Managers.PluginManager: Loaded 0 plugins.
06:22:30.4737 [INFO]   Torch.VRageGame: Setting up serializers
06:22:33.1927 [INFO]   InstanceManager: Loading instance C:\Users\Administrator\Desktop\Torch\Instance
06:22:33.3333 [WARN]   InstanceManager: No worlds found in the current instance C:\Users\Administrator\Desktop\Torch\Instance.
06:22:33.3333 [INFO]   Torch: Initialized server 'Torch' at 'C:\Users\Administrator\Desktop\Torch\Instance'
06:22:34.3178 [INFO]   Torch.Managers.UpdateManager: Torch is up to date.
06:22:52.4035 [FATAL]  Initializer: System.NullReferenceException: Object reference not set to an instance of an object.
   at Torch.Server.Views.ConfigControl.RoleEdit_Onlick(Object sender, RoutedEventArgs e) in C:\jenkins\workspace\Torch_Torch_master\Torch.Server\Views\ConfigControl.xaml.cs:line 132
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Window.ShowDialog()
   at Torch.Server.Initializer.Run() in C:\jenkins\workspace\Torch_Torch_master\Torch.Server\Initializer.cs:line 143
   at Torch.Server.Program.Main(String[] args) in C:\jenkins\workspace\Torch_Torch_master\Torch.Server\Program.cs:line 76
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssemblyByName(String assemblyName, String[] args)
   at Torch.Utils.TorchLauncher.Launch(String entryPoint, String[] args, String[] binaryPaths) in C:\jenkins\workspace\Torch_Torch_master\Torch\Utils\TorchLauncher.cs:line 38
   at Torch.Server.Program.Main(String[] args) in C:\jenkins\workspace\Torch_Torch_master\Torch.Server\Program.cs:line 76
System.NullReferenceException: Object reference not set to an instance of an object.
   at Torch.Server.Views.ConfigControl.RoleEdit_Onlick(Object sender, RoutedEventArgs e) in C:\jenkins\workspace\Torch_Torch_master\Torch.Server\Views\ConfigControl.xaml.cs:line 132
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Window.ShowDialog()
   at Torch.Server.Initializer.Run() in C:\jenkins\workspace\Torch_Torch_master\Torch.Server\Initializer.cs:line 143
   at Torch.Server.Program.Main(String[] args) in C:\jenkins\workspace\Torch_Torch_master\Torch.Server\Program.cs:line 76
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssemblyByName(String assemblyName, String[] args)
   at Torch.Utils.TorchLauncher.Launch(String entryPoint, String[] args, String[] binaryPaths) in C:\jenkins\workspace\Torch_Torch_master\Torch\Utils\TorchLauncher.cs:line 38
   at Torch.Server.Program.Main(String[] args) in C:\jenkins\workspace\Torch_Torch_master\Torch.Server\Program.cs:line 76
06:22:52.4348 [INFO]   Initializer: Generating minidump at C:\Users\Administrator\Desktop\Torch\Instance\Minidump.dmp
06:22:52.4348 [ERROR]  Initializer: Keen broke the minidump, sorry.

Windows Server 2012 R2

**Comment by N1Ran** [comment]
There's no world loaded. Check your instance path and settings via Torch.cfg
