### ISSUE TITLE
Failed to get thread indent

### ISSUE THREAD

**Issue by asaurytski-exadel** [TorchAPI/Torch#386]
Torch: Torch Version: v1.3.1.120-master
00:47:18.7546 [INFO]   Torch: Game Version: 1.194.207

### Expected Behavior
No bugs

### Observed Behavior
Exception in log

### Steps to Reproduce
1. Start Torch
2. see Keen log

Env :
i7 7700 , Win2012Server r2

### Other Information
 **Keen: Failed to get thread indent**
System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method(Closure , MyLog , Int32 )
   at Torch.Patches.KeenLogPatch.PrepareLog(MyLog log) in C:\jenkins\workspace\Torch_Torch_master\Torch\Patches\KeenLogPatch.cs:line 86
00:48:27.2824 [DEBUG]  Keen: MyFont.Ctor - START
00:48:27.2824 [DEBUG]  Keen: Failed to get thread indent
System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method(Closure , MyLog , Int32 )
   at Torch.Patches.KeenLogPatch.PrepareLog(MyLog log) in C:\jenkins\workspace\Torch_Torch_master\Torch\Patches\KeenLogPatch.cs:line 86
00:48:27.2824 [DEBUG]  Keen: Font filename: Fonts\white_shadow\FontDataPA.xml

120 repeats

**Comment by HijackHornet** [comment]
Getting this too
