### ISSUE TITLE
Torch fails to start on fresh install

### ISSUE THREAD

**Issue by bakedog417** [TorchAPI/Torch#391]
- [x] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [x] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:** v1.3.1.120-master **SE Version:** 1.195.18

### Expected Behavior
I expected it to start and run.

### Observed Behavior
Crashes with:

`19:39:30.8705 [FATAL]  Initializer: System.MissingMethodException: Method not found: 'Void Sandbox.MyInitializer.InvokeBeforeRun(UInt32, System.String, System.String, Boolean, Int32)'.
   at Torch.VRageGame.Create()
   at Torch.VRageGame.Run() in C:\jenkins\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 117
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
System.MissingMethodException: Method not found: 'Void Sandbox.MyInitializer.InvokeBeforeRun(UInt32, System.String, System.String, Boolean, Int32)'.
   at Torch.VRageGame.Create()
   at Torch.VRageGame.Run() in C:\jenkins\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 117
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
`

### Steps to Reproduce
1. Download latest bundle
2. Start Torch.Server

**Comment by Jimmacle** [comment]
Update your game per the announcement on the Discord server: https://discord.com/invite/kq2NFV

**Comment by bakedog417** [comment]
Updating does not fix this issue.  Steamcmd reports app is at the latest version.

**Comment by N1Ran** [comment]
Did you manually update Torch?
https://wiki.torchapi.net/index.php/Manually_updating

**Comment by Jimmacle** [comment]
The latest torch version is .121.

**Comment by bakedog417** [comment]
Thank you both.  That did the trick.
