### ISSUE TITLE
Torch doesn't create a full instance template.

### ISSUE THREAD

**Issue by bennextmitchell** [TorchAPI/Torch#40]
- [x] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [x] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:**Latest **SE Version:** Latest (04/07/2017) (UK)

### Expected Behavior
App open.

### Observed Behavior
App instantly crashes 

### Steps to Reproduce
1. How did this issue get triggered?
a: During the first run of the application
2. Write the steps here.
a: Double click to run app. Crash.

### Other Information
Log:

14:28:35.5342 [INFO] Torch: Generating default config at C:\Users\Administrator\Desktop\SE\TorchConfig.xml
14:28:35.5872 [WARN] Torch: Would you like to enable automatic updates? (Y/n):
14:28:38.7150 [INFO] Torch: Automatic updates enabled, updating server.
14:28:38.7210 [INFO] SteamCMD: Downloading SteamCMD.
14:28:38.9112 [INFO] SteamCMD: SteamCMD downloaded successfully!
14:28:38.9112 [INFO] SteamCMD: Checking for DS updates.
14:28:44.4604 [INFO] SteamCMD: Steam Console Client (c) Valve Corporation
14:28:44.5615 [INFO] SteamCMD: -- type 'quit' to exit --
14:28:44.6626 [INFO] SteamCMD: Loading Steam API...OK.
14:28:45.2329 [INFO] SteamCMD: 
14:28:47.5122 [INFO] SteamCMD: Connecting anonymously to Steam Public...Logged in OK
14:28:52.4742 [INFO] SteamCMD: Waiting for user info...OK
14:28:52.8656 [INFO] SteamCMD:  Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
14:28:54.0042 [INFO] SteamCMD:  Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
14:28:56.0016 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 0.23 (4194304 / 1803022067)
14:28:58.0017 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 1.37 (24744928 / 1803022067)
14:29:00.0252 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 1.37 (24744928 / 1803022067)
14:29:02.0184 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 1.37 (24744928 / 1803022067)
14:29:04.0156 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 1.37 (24744928 / 1803022067)
14:29:06.0161 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 1.37 (24744928 / 1803022067)
14:29:08.0181 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 1.37 (24744928 / 1803022067)
14:29:10.0120 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 4.95 (89220258 / 1803022067)
14:29:12.0159 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 14.39 (259431512 / 1803022067)
14:29:14.0078 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 22.09 (398280107 / 1803022067)
14:29:16.0197 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 32.55 (586872474 / 1803022067)
14:29:18.0251 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 43.50 (784390455 / 1803022067)
14:29:20.0070 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 53.43 (963438585 / 1803022067)
14:29:22.0171 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 55.24 (995957227 / 1803022067)
14:29:24.0196 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 56.23 (1013870714 / 1803022067)
14:29:26.0158 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 65.01 (1172190876 / 1803022067)
14:29:28.0245 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 66.16 (1192879766 / 1803022067)
14:29:30.0036 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 74.46 (1342610036 / 1803022067)
14:29:32.0156 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 77.29 (1393499826 / 1803022067)
14:29:34.0209 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 82.95 (1495680862 / 1803022067)
14:29:36.0158 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 86.76 (1564323772 / 1803022067)
14:29:38.0000 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 90.20 (1626384957 / 1803022067)
14:29:40.0031 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 94.48 (1703556752 / 1803022067)
14:29:42.0438 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 97.01 (1749070176 / 1803022067)
14:29:44.0164 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 98.19 (1770468770 / 1803022067)
14:29:46.0172 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 98.57 (1777299677 / 1803022067)
14:29:48.0142 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 98.57 (1777299677 / 1803022067)
14:29:50.0162 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 99.99 (1802895840 / 1803022067)
14:29:52.0148 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 99.99 (1802922176 / 1803022067)
14:29:54.0114 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 99.99 (1802922176 / 1803022067)
14:29:56.0024 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 99.99 (1802922176 / 1803022067)
14:29:58.0231 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 99.99 (1802922176 / 1803022067)
14:30:00.0202 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 99.99 (1802922176 / 1803022067)
14:30:02.0154 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 99.99 (1802922176 / 1803022067)
14:30:04.0099 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 99.99 (1802922176 / 1803022067)
14:30:06.0026 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 99.99 (1802922176 / 1803022067)
14:30:08.0224 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 99.99 (1802922176 / 1803022067)
14:30:10.0172 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 99.99 (1802922176 / 1803022067)
14:30:12.0110 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 99.99 (1802922176 / 1803022067)
14:30:14.0064 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 99.99 (1802922176 / 1803022067)
14:30:16.0001 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 99.99 (1802922176 / 1803022067)
14:30:18.0187 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 99.99 (1802922176 / 1803022067)
14:30:20.0163 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 99.99 (1802922176 / 1803022067)
14:30:22.0081 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 99.99 (1802922176 / 1803022067)
14:30:24.0044 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 99.99 (1802922176 / 1803022067)
14:30:26.0133 [INFO] SteamCMD:  Update state (0x101) committing, progress: 69.55 (1253948733 / 1803022067)
14:30:28.0160 [INFO] SteamCMD:  Update state (0x101) committing, progress: 84.42 (1522130976 / 1803022067)
14:30:29.3411 [INFO] SteamCMD: Success! App '298740' fully installed.
14:30:30.5949 [INFO] SteamCMD: Redirecting stderr to 'C:\Users\Administrator\Desktop\SE\steamcmd\logs\stderr.txt'
14:30:30.7313 [INFO] SteamCMD: Checking for DS updates.
14:30:31.4337 [INFO] SteamCMD: Steam Console Client (c) Valve Corporation
14:30:31.5358 [INFO] SteamCMD: -- type 'quit' to exit --
14:30:31.6379 [INFO] SteamCMD: Loading Steam API...OK.
14:30:31.7400 [INFO] SteamCMD: 
14:30:33.8425 [INFO] SteamCMD: Connecting anonymously to Steam Public...Logged in OK
14:30:33.9449 [INFO] SteamCMD: Waiting for user info...OK
14:30:34.8744 [INFO] SteamCMD: Success! App '298740' already up to date.
14:30:35.5900 [INFO] SteamCMD: 
14:30:36.0404 [INFO] Torch: RELEASE
14:30:36.0404 [INFO] Torch: Torch 1.0.182.329, SE 1.181.401
14:30:36.0404 [INFO] Torch: Executing assembly: Torch.Server, Version=1.0.182.329, Culture=neutral, PublicKeyToken=null
14:30:36.0404 [INFO] Torch: Executing directory: C:\Users\Administrator\Desktop\SE\
14:30:36.0404 [INFO] Torch: Init server 'Torch' at 'C:\Users\Administrator\Desktop\SE\Instance'
14:30:36.5859 [FATAL] Torch: System.InvalidOperationException: Error creating XML serializer for type MyObjectBuilder_TriggerAggregate ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Administrator\AppData\Local\Temp\2\2odncwvv.tmp'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at System.CodeDom.Compiler.TempFileCollection.EnsureTempNameCreated()
   at System.CodeDom.Compiler.TempFileCollection.AddExtension(String fileExtension, Boolean keepFile)
   at Microsoft.CSharp.CSharpCodeGenerator.FromSourceBatch(CompilerParameters options, String[] sources)
   at Microsoft.CSharp.CSharpCodeGenerator.System.CodeDom.Compiler.ICodeCompiler.CompileAssemblyFromSourceBatch(CompilerParameters options, String[] sources)
   at System.Xml.Serialization.Compiler.Compile(Assembly parent, String ns, XmlSerializerCompilerParameters xmlParameters, Evidence evidence)
   at System.Xml.Serialization.TempAssembly.GenerateAssembly(XmlMapping[] xmlMappings, Type[] types, String defaultNamespace, Evidence evidence, XmlSerializerCompilerParameters parameters, Assembly assembly, Hashtable assemblies)
   at System.Xml.Serialization.TempAssembly..ctor(XmlMapping[] xmlMappings, Type[] types, String defaultNamespace, String location, Evidence evidence)
   at System.Xml.Serialization.XmlSerializer.GenerateTempAssembly(XmlMapping xmlMapping, Type type, String defaultNamespace)
   at System.Xml.Serialization.XmlSerializer..ctor(Type type, String defaultNamespace)
   at VRage.MyXmlSerializerManager.RegisterType(Type type, Boolean forceRegister, Boolean checkAttributes)
   at VRage.MyXmlSerializerManager.RegisterFromAssembly(Assembly assembly)
   --- End of inner exception stack trace ---
   at VRage.MyXmlSerializerManager.RegisterFromAssembly(Assembly assembly)
   at VRage.Game.ObjectBuilder.MyGlobalTypeMetadata.RegisterAssembly(Assembly assembly)
   at VRage.Game.ObjectBuilder.MyGlobalTypeMetadata.Init()
   at Torch.Server.TorchServer.Init()
   at Torch.Server.Program.RunServer(TorchConfig options, TorchCli cli)
   at Torch.Server.Program.Main(String[] args)
14:31:58.1835 [INFO] Torch: Loading config C:\Users\Administrator\Desktop\SE\TorchConfig.xml
14:31:58.2876 [INFO] SteamCMD: Checking for DS updates.
14:31:59.0205 [INFO] SteamCMD: Steam Console Client (c) Valve Corporation
14:31:59.1226 [INFO] SteamCMD: -- type 'quit' to exit --
14:31:59.2237 [INFO] SteamCMD: Loading Steam API...OK.
14:31:59.3248 [INFO] SteamCMD: 
14:32:01.4352 [INFO] SteamCMD: Connecting anonymously to Steam Public...Logged in OK
14:32:01.5363 [INFO] SteamCMD: Waiting for user info...OK
14:32:02.3953 [INFO] SteamCMD: Success! App '298740' already up to date.
14:32:03.1760 [INFO] SteamCMD: 
14:32:03.6055 [INFO] Torch: RELEASE
14:32:03.6055 [INFO] Torch: Torch 1.0.182.329, SE 1.181.401
14:32:03.6055 [INFO] Torch: Executing assembly: Torch.Server, Version=1.0.182.329, Culture=neutral, PublicKeyToken=null
14:32:03.6055 [INFO] Torch: Executing directory: C:\Users\Administrator\Desktop\SE\
14:32:03.6105 [INFO] Torch: Init server 'Torch' at 'C:\Users\Administrator\Desktop\SE\Instance'
14:32:04.1010 [FATAL] Torch: System.InvalidOperationException: Error creating XML serializer for type MyObjectBuilder_TriggerAggregate ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Administrator\AppData\Local\Temp\2\2ocqiu0s.tmp'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at System.CodeDom.Compiler.TempFileCollection.EnsureTempNameCreated()
   at System.CodeDom.Compiler.TempFileCollection.AddExtension(String fileExtension, Boolean keepFile)
   at Microsoft.CSharp.CSharpCodeGenerator.FromSourceBatch(CompilerParameters options, String[] sources)
   at Microsoft.CSharp.CSharpCodeGenerator.System.CodeDom.Compiler.ICodeCompiler.CompileAssemblyFromSourceBatch(CompilerParameters options, String[] sources)
   at System.Xml.Serialization.Compiler.Compile(Assembly parent, String ns, XmlSerializerCompilerParameters xmlParameters, Evidence evidence)
   at System.Xml.Serialization.TempAssembly.GenerateAssembly(XmlMapping[] xmlMappings, Type[] types, String defaultNamespace, Evidence evidence, XmlSerializerCompilerParameters parameters, Assembly assembly, Hashtable assemblies)
   at System.Xml.Serialization.TempAssembly..ctor(XmlMapping[] xmlMappings, Type[] types, String defaultNamespace, String location, Evidence evidence)
   at System.Xml.Serialization.XmlSerializer.GenerateTempAssembly(XmlMapping xmlMapping, Type type, String defaultNamespace)
   at System.Xml.Serialization.XmlSerializer..ctor(Type type, String defaultNamespace)
   at VRage.MyXmlSerializerManager.RegisterType(Type type, Boolean forceRegister, Boolean checkAttributes)
   at VRage.MyXmlSerializerManager.RegisterFromAssembly(Assembly assembly)
   --- End of inner exception stack trace ---
   at VRage.MyXmlSerializerManager.RegisterFromAssembly(Assembly assembly)
   at VRage.Game.ObjectBuilder.MyGlobalTypeMetadata.RegisterAssembly(Assembly assembly)
   at VRage.Game.ObjectBuilder.MyGlobalTypeMetadata.Init()
   at Torch.Server.TorchServer.Init()
   at Torch.Server.Program.RunServer(TorchConfig options, TorchCli cli)
   at Torch.Server.Program.Main(String[] args)

**Comment by bennextmitchell** [comment]
After purging all Steam and Space Engineers files from my server i managed to get a launch, However this is what happened when i pressed 'Save Config'

15:46:20.7555 [INFO] Torch: Generating default config at E:\Steam\TorchConfig.xml
15:46:20.8180 [WARN] Torch: Would you like to enable automatic updates? (Y/n):
15:46:23.7960 [INFO] Torch: Automatic updates enabled, updating server.
15:46:23.7960 [INFO] SteamCMD: Downloading SteamCMD.
15:46:24.1554 [INFO] SteamCMD: SteamCMD downloaded successfully!
15:46:24.1554 [INFO] SteamCMD: Checking for DS updates.
15:46:28.9625 [INFO] SteamCMD: Steam Console Client (c) Valve Corporation
15:46:29.0784 [INFO] SteamCMD: -- type 'quit' to exit --
15:46:29.2670 [INFO] SteamCMD: Loading Steam API...OK.
15:46:29.3764 [INFO] SteamCMD: 
15:46:32.2110 [INFO] SteamCMD: Connecting anonymously to Steam Public...Logged in OK
15:46:37.3052 [INFO] SteamCMD: Waiting for user info...OK
15:46:37.7427 [INFO] SteamCMD:  Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
15:46:39.0241 [INFO] SteamCMD:  Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
15:46:41.0299 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 0.52 (9437184 / 1803022067)
15:46:43.0175 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 4.23 (76243665 / 1803022067)
15:46:45.0020 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 9.30 (167682160 / 1803022067)
15:46:47.0021 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 22.10 (398491764 / 1803022067)
15:46:49.0179 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 44.79 (807543674 / 1803022067)
15:46:51.0181 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 49.63 (894783446 / 1803022067)
15:46:53.0218 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 53.63 (967022544 / 1803022067)
15:46:55.0040 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 55.67 (1003798110 / 1803022067)
15:46:57.0198 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 65.46 (1180262210 / 1803022067)
15:46:59.0006 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 66.89 (1206069324 / 1803022067)
15:47:01.0182 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 70.30 (1267534710 / 1803022067)
15:47:03.0184 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 82.55 (1488342073 / 1803022067)
15:47:05.0185 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 88.37 (1593362739 / 1803022067)
15:47:07.0213 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 89.23 (1608823496 / 1803022067)
15:47:09.0214 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 93.14 (1679387409 / 1803022067)
15:47:11.0059 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 96.38 (1737679279 / 1803022067)
15:47:13.0174 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 97.79 (1763187822 / 1803022067)
15:47:15.0167 [INFO] SteamCMD:  Update state (0x61) downloading, progress: 99.94 (1801944023 / 1803022067)
15:47:17.0293 [INFO] SteamCMD:  Update state (0x101) committing, progress: 69.73 (1257263437 / 1803022067)
15:47:18.3141 [INFO] SteamCMD: Success! App '298740' fully installed.
15:47:19.6817 [INFO] SteamCMD: Redirecting stderr to 'E:\Steam\steamcmd\logs\stderr.txt'
15:47:19.8379 [INFO] SteamCMD: Checking for DS updates.
15:47:20.5907 [INFO] SteamCMD: Steam Console Client (c) Valve Corporation
15:47:20.7000 [INFO] SteamCMD: -- type 'quit' to exit --
15:47:20.8094 [INFO] SteamCMD: Loading Steam API...OK.
15:47:20.9188 [INFO] SteamCMD: 
15:47:22.8346 [INFO] SteamCMD: Connecting anonymously to Steam Public...Logged in OK
15:47:22.9439 [INFO] SteamCMD: Waiting for user info...OK
15:47:24.0323 [INFO] SteamCMD: Success! App '298740' already up to date.
15:47:24.8360 [INFO] SteamCMD: 
15:47:25.4212 [INFO] Torch: RELEASE
15:47:25.4212 [INFO] Torch: Torch 1.0.182.329, SE 1.181.401
15:47:25.4212 [INFO] Torch: Executing assembly: Torch.Server, Version=1.0.182.329, Culture=neutral, PublicKeyToken=null
15:47:25.4212 [INFO] Torch: Executing directory: E:\Steam\
15:47:25.4212 [INFO] Torch: Init server 'Torch' at 'E:\Steam\Instance'
15:47:27.5549 [ERROR] Config: Failed to load dedicated config at E:\Steam\Instance\SpaceEngineers-Dedicated.cfg
15:47:27.5549 [ERROR] Config: Failed to load dedicated config at E:\Steam\Instance\SpaceEngineers-Dedicated.cfg
15:48:15.3415 [FATAL] Torch: System.NullReferenceException: Object reference not set to an instance of an object.
   at Torch.Server.Views.ConfigControl.SaveConfig()
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Window.ShowDialog()
   at Torch.Server.Program.RunServer(TorchConfig options, TorchCli cli)
   at Torch.Server.Program.Main(String[] args)

**Comment by Jimmacle** [comment]
The first one looks like it may have failed to download the DS properly, second one is because Torch doesn't currently create a full instance on its own. You'll have to copy an existing instance in, specifically the SpaceEngineers-Dedicated.cfg. This will be fixed in the next update.

**Comment by bennextmitchell** [comment]
Ah that fixed it thanks!
