### ISSUE TITLE
Fatal Error with really common Mods - every time exactly the same erroremessage

### ISSUE THREAD

**Issue by Hansglanzkopf** [TorchAPI/Torch#407]
- [x] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [x] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:** 1.3.1.129 **SE Version:** 1.196.016

### Expected Behavior
//What did you expect to happen?
I can play the game with these Mods without Error

### Observed Behavior
//What actually happened?
After a couple of seconds, minutes, or maybe one hour, the Server crashes with exactly the same errormessage every time.
After one of these crashes occur it is not a solution to delete the mods out of the config.sbc file. The error stays the same. 

The game works perfect without the mods.

### Steps to Reproduce
1. Install Torch
2. Install a couple of given Plugins (after deleting all Plugins, the Error stays the same)
![Plugins_Screenshot](https://user-images.githubusercontent.com/68276979/94807330-c90be880-03ef-11eb-9aa1-4645ad49c1e3.png)
3. Put... 

"Modular Encounters Spawner"
1521905890

"NPC Programming Extender"
1400364273

"Corruption PvE Combat">
914369510

"Defense Shields"
1365616918

...in your Sandbox_config.sbc file
4. Play a short time and look how it crashs

### Other Information
[Logs.zip](https://github.com/TorchAPI/Torch/files/5310246/Logs.zip)
[Sandbox_config.zip](https://github.com/TorchAPI/Torch/files/5312244/Sandbox_config.zip)

In the .zip are all logs from torch. 

**---------------------------------------------------------------------------------------------------**
Here is the fatal error itself:

09:05:00.1321 [INFO]   Backup: Backing up completed!
09:13:53.2778 [FATAL]  Initializer: System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.Game.Multiplayer.MyPlayerCollection.SetIdentityGridBlocksBuilt(MyGridLimitData limits, Int32 pcu, Int32 pcuBuilt, Int32 blocksBuilt, Int32 transferedDelta)
   at VRage.Network.MyReplicationLayerBase.InvokeLocally[T1,T2,T3,T4,T5,T6,T7](CallSite`7 site, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7)
   at VRage.Network.MyReplicationLayer.DispatchEvent[T1,T2,T3,T4,T5,T6,T7,T8](CallSite callSite, EndpointId recipient, Nullable`1 position, T1& arg1, T2& arg2, T3& arg3, T4& arg4, T5& arg5, T6& arg6, T7& arg7, T8& arg8)
   at VRage.Network.MyReplicationLayerBase.RaiseEvent[T1,T2,T3,T4,T5,T6,T7](T1 arg1, T7 arg7, Func`2 action, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, EndpointId endpointId, Nullable`1 position)
   at Sandbox.Game.Multiplayer.MyPlayerCollection.SendDirtyBlockLimit(MyBlockLimits blockLimit, List`1 playersToSendTo)
   at Sandbox.Game.Multiplayer.MyPlayerCollection.SendDirtyBlockLimits()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Patched_Sandbox.Engine.Platform.GameRunSingleFrame_0(Object )
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at Torch.VRageGame.DoStart() in C:\jenkins\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 246
   at Torch.VRageGame.Run() in C:\jenkins\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 125
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.Game.Multiplayer.MyPlayerCollection.SetIdentityGridBlocksBuilt(MyGridLimitData limits, Int32 pcu, Int32 pcuBuilt, Int32 blocksBuilt, Int32 transferedDelta)
   at VRage.Network.MyReplicationLayerBase.InvokeLocally[T1,T2,T3,T4,T5,T6,T7](CallSite`7 site, T1 arg1, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, T7 arg7)
   at VRage.Network.MyReplicationLayer.DispatchEvent[T1,T2,T3,T4,T5,T6,T7,T8](CallSite callSite, EndpointId recipient, Nullable`1 position, T1& arg1, T2& arg2, T3& arg3, T4& arg4, T5& arg5, T6& arg6, T7& arg7, T8& arg8)
   at VRage.Network.MyReplicationLayerBase.RaiseEvent[T1,T2,T3,T4,T5,T6,T7](T1 arg1, T7 arg7, Func`2 action, T2 arg2, T3 arg3, T4 arg4, T5 arg5, T6 arg6, EndpointId endpointId, Nullable`1 position)
   at Sandbox.Game.Multiplayer.MyPlayerCollection.SendDirtyBlockLimit(MyBlockLimits blockLimit, List`1 playersToSendTo)
   at Sandbox.Game.Multiplayer.MyPlayerCollection.SendDirtyBlockLimits()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Patched_Sandbox.Engine.Platform.GameRunSingleFrame_0(Object )
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass11_0.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at Torch.VRageGame.DoStart() in C:\jenkins\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 246
   at Torch.VRageGame.Run() in C:\jenkins\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 125
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
09:13:53.2778 [INFO]   Initializer: Generating minidump at C:\space-DS public\Instance\Minidump.dmp
09:13:53.2778 [ERROR]  Initializer: Keen broke the minidump, sorry.
09:28:01.7524 [INFO]   SteamCMD: Checking for DS updates.

**Comment by storpapa** [comment]
Getting the same error Torch runs fine and then Essentials plugin starts a maintenance cycle, ending in a hung Torch server and 
[FATAL]  Initializer: System.NullReferenceException: Object reference not set to an instance of an object.
...
minidump message
