### ISSUE TITLE
System crash on connect - log appears to indicate issue with turret targeting.

### ISSUE THREAD

**Issue by kurazarrh** [TorchAPI/Torch#41]
**Torch Version:** 1.0.182.329 **SE Version:** 1.181.401

### Expected Behavior
User should have been able to log in and begin playing on the server.

### Observed Behavior
Client bumped user back to Space Engineers title screen with "Server host has left the game" message. Server attempted to restart but failed.

### Steps to Reproduce
1) Server admin started server via the "Start" button in the Torch GUI.
2) Client attempted to log on.

### Other Information
I don't think this is a vanilla issue, as I have tested this today and last night with a mix of Torch, SESE, and vanilla DS with the same world. Only Torch throws the exception pasted below:

12:36:49.9806 [FATAL] Torch: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.Game.EntityComponents.MyGridTargeting.Scan()
   at Sandbox.Game.EntityComponents.MyGridTargeting.RescanIfNeeded()
   at Sandbox.Game.Weapons.MyLargeTurretBase.CheckAndSelectNearTargetsParallel()
   at Sandbox.Game.Weapons.MyLargeTurretBase.UpdateAfterSimulation10()
   at Sandbox.Game.Entities.MyEntities.<UpdateAfterSimulation>b__e(MyEntity x)
   at VRage.Collections.MyDistributedUpdater`2.Iterate(Action`1 p)
   at Sandbox.Game.Entities.MyEntities.UpdateAfterSimulation()
   at Sandbox.Game.World.MySector.UpdateAfterSimulation()
   at Sandbox.Game.World.MySession.UpdateComponents()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass1.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at VRage.Dedicated.DedicatedServer.RunInternal()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Torch.Server.TorchServer.Start()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by Jimmacle** [comment]
I believe this is an erratic vanilla issue given the reports on [Keen's forum](https://forum.keenswh.com/search/8431938/?q=mygridtargeting.scan&o=date), maybe you're just getting unlucky and it's only getting triggered when you're testing Torch. If you're absolutely sure let me know and I'll take a closer look.

**Comment by kurazarrh** [comment]
Will do. I've been running the server constantly but have only seen this on Torch (and have only tested this on vanilla; the majority of the server's uptime has been on SESE).

Here's a question--aside from the fact that it looks to also be an issue in vanilla, could there be complications arising due to migrating from SESE to Torch that might cause this?

**Comment by Jimmacle** [comment]
There shouldn't be any conflict between SESE and Torch, just make sure that you remove NewEssentials from your world because Torch doesn't use it and could interfere with chat commands.

**Comment by Jimmacle** [comment]
Reopening this issue, another user has tracked the problem down to concealment.

**Comment by Jimmacle** [comment]
Haven't seen this issue reoccur for a long time, closing.
