### ISSUE TITLE
Torch crashing after trying to initialize workshop support

### ISSUE THREAD

**Issue by jbullock-bit** [TorchAPI/Torch#424]
- [ ] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [x] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:** 1.3.1.138-master **SE Version:** 1.xxx.xxx

### Expected Behavior
it to run

### Observed Behavior
it crashes saying "torch encountered a fatal error and needs to close. please check the logs for details"

The log behind that window says the following;
12:41:24.5527 [INFO]   Keen:    Error initializing workshop support.
12:41:24.5527 [FATAL]  Initializer: System.Exception: Fatal error during dedicated server init see log for more information.
   at Patched_Sandbox.MySandboxGame.ctor_0(Object windowHandle, String[] , IntPtr )
   at SpaceEngineers.Game.SpaceEngineersGame..ctor(String[] commandlineArgs)
   at Torch.VRageGame.DoStart() in C:\build\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 246
   at Torch.VRageGame.Run() in C:\build\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 120
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
System.Exception: Fatal error during dedicated server init see log for more information.
   at Patched_Sandbox.MySandboxGame.ctor_0(Object windowHandle, String[] , IntPtr )
   at SpaceEngineers.Game.SpaceEngineersGame..ctor(String[] commandlineArgs)
   at Torch.VRageGame.DoStart() in C:\build\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 246
   at Torch.VRageGame.Run() in C:\build\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 120
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

but not sure how to fix it. 
### Steps to Reproduce
1. How did this issue get triggered?
I had an internet outage yesterday, since then it's been happening
2. Write the steps here.

### Other Information
Provide links to game logs or saves here if necessary.

**Comment by steviee** [comment]
Same problem here. Right after updating SE.

**Comment by xXPinkFloyd92Xx** [comment]
after Hotfix - 1.197.074 I have the same issues

**Comment by dpwlt** [comment]
Same problem, after update unable to launch server

**Comment by YannMCX** [comment]
Same problem here...

**Comment by usurpine** [comment]
same problem here. I have checked all mods, all plugins, setup a new server, updated a running server and after the latest update all have the same problem. its definitly a torch problem.

**Comment by xXPinkFloyd92Xx** [comment]
They updated this with a fix if you go into dedicatedserver64 copy your steamworks.NET.dll then paste that in the torch root folder.

**Comment by Jimmacle** [comment]
v1.3.1.139-master should fix the issue for now. There's a problem with the build server including files in the Torch zip file that it shouldn't that I need to fix properly later.

**Comment by jbullock-bit** [comment]
Thanks. My work around has been to use the dedicatedserver from SE within the torch folder. Not as nice to use but did "everything" that I needed to get running again at least temporarily.
