### ISSUE TITLE
Torch encounters Unhandled Exception

### ISSUE THREAD

**Issue by celestialorb** [TorchAPI/Torch#427]
- [x] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [x] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:** 1.3.1.139-master **SE Version:** 1.xxx.xxx

### Expected Behavior
I expected the Torch Server to launch without issue, as it did yesterday.

### Observed Behavior
The Torch Server throws an Unhandled Exception error when starting.
```
System.MissingMethodException: Method not found: 'Void ModItem..ctor(UInt64)'.
   at Torch.Session.TorchSessionManager..ctor(ITorchBase torchInstance)
   at Torch.TorchBase..ctor() in C:\build\workspace\Torch_Torch_master\Torch\TorchBase.cs:line 158
   at Torch.Server.TorchServer..ctor(TorchConfig config) in C:\build\workspace\Torch_Torch_master\Torch.Server\TorchServer.cs:line 62
   at Torch.Server.Initializer.Run() in C:\build\workspace\Torch_Torch_master\Torch.Server\Initializer.cs:line 127
   at Torch.Server.Program.Main(String[] args) in C:\build\workspace\Torch_Torch_master\Torch.Server\Program.cs:line 75
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssemblyByName(String assemblyName, String[] args)
   at Torch.Utils.TorchLauncher.Launch(String entryPoint, String[] args, String[] binaryPaths) in C:\build\workspace\Torch_Torch_master\Torch\Utils\TorchLauncher.cs:line 38
   at Torch.Server.Program.Main(String[] args) in C:\build\workspace\Torch_Torch_master\Torch.Server\Program.cs:line 75
```

Happens to me on a fresh install of the Torch Server as well. Is there some redistributable package or dependency my system needs?

### Steps to Reproduce
1. Start the Torch.Server.exe file.
2. Wait for it to crash.

### Other Information
Provide links to game logs or saves here if necessary.

**Comment by JoshuaCalhoun** [comment]
I'd like to second this, I'm now getting the exact same error when I try to reboot my server.
Originally I was having problems getting my world to load (mods weren't downloading correctly)
so I restarted and removed all mods, world booted, then shutdown, readded mods. I then restarted my client one more time and I started receiving this error as well.
Performed an update via the steps on [here](https://wiki.torchapi.net/index.php/Basic_Getting_Started_Guide) and issue persists.
Started about 9:30EST for me.

**Comment by ZilgornZeypher** [comment]
Same here. Shut down torch to update space engineers patch today. Server refuses to come back up and torch crashes.

**Comment by steviee** [comment]
https://github.com/TorchAPI/Torch/pull/428 might fix it for us.

**Comment by nuclrhorseradish** [comment]
For whatever its worth seeing this behavior myself today around 10A Eastern. Identical abort string from OP.

**Comment by dpwlt** [comment]
Can confirm same issue:

Unhandled Exception: System.MissingMethodException: Method not found: 'Void ModItem..ctor(UInt64)'.
   at Torch.Session.TorchSessionManager..ctor(ITorchBase torchInstance)
   at Torch.TorchBase..ctor() in C:\build\workspace\Torch_Torch_master\Torch\TorchBase.cs:line 158
   at Torch.Server.TorchServer..ctor(TorchConfig config) in C:\build\workspace\Torch_Torch_master\Torch.Server\TorchServer.cs:line 62
   at Torch.Server.Initializer.Run() in C:\build\workspace\Torch_Torch_master\Torch.Server\Initializer.cs:line 127
   at Torch.Server.Program.Main(String[] args) in C:\build\workspace\Torch_Torch_master\Torch.Server\Program.cs:line 75
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssemblyByName(String assemblyName, String[] args)
   at Torch.Utils.TorchLauncher.Launch(String entryPoint, String[] args, String[] binaryPaths) in C:\build\workspace\Torch_Torch_master\Torch\Utils\TorchLauncher.cs:line 38
   at Torch.Server.Program.Main(String[] args) in C:\build\workspace\Torch_Torch_master\Torch.Server\Program.cs:line 75

**Comment by AHrubik** [comment]
Adding on. Getting this with the latest release as of 2/11/2021 @ 1227 CST.

**Comment by McxCZE** [comment]
Same over here. :/

**Comment by 22SAS-Mazing** [comment]
Same for me.

**Comment by ZephyrFerret** [comment]
im getting this same error. I was currently hosting a server but had to restart it to apply the space engineers update. i also had to update windows in the process, so I went ahead and did that as well. logging back in after the update and torch crashes on startup with this exact same exception. I tried loading a fresh instance of torch (the most recent version) with no configurations, no worlds, and it still crashes.

could it be a windows update? or part of the space engineers hosting client?

**Comment by 22SAS-Mazing** [comment]
The new Space Engineers update caused it.

**Comment by JoshuaCalhoun** [comment]
Just tested the latest download pushed out on 2-11, appears to be working as intended now. Thanks guys!

**Comment by HammerWare** [comment]
> Just tested the latest download pushed out on 2-11, appears to be working for opening the server console, but I still seem to be having trouble getting mods to work, looking into this now and testing if its a particular mod or not. Thanks ya'll

Having The same issue maybe they updated how mods are retrieved when connecting to servers due to the fact xbox is now included.

**Comment by 22SAS-Mazing** [comment]
> 
> 
> Just tested the latest download pushed out on 2-11, appears to be working for opening the server console, but I still seem to be having trouble getting mods to work, looking into this now and testing if its a particular mod or not. Thanks ya'll

Is it just a problem downloading mods or is it affecting mods already installed too?

**Comment by JoshuaCalhoun** [comment]
> > Just tested the latest download pushed out on 2-11, appears to be working for opening the server console, but I still seem to be having trouble getting mods to work, looking into this now and testing if its a particular mod or not. Thanks ya'll
> 
> Is it just a problem downloading mods or is it affecting mods already installed too?

From what I could tell yesterday, its all mods, both current and new. But I'm wondering if it has somethign to do with the new cross play functionality with xbox. I've been seeing others state problems with mods on worlds now too so I figured I'd give it a day or two and see if Keen pushes a new server update to address. 
Thats my speculation at least...

**Comment by celestialorb** [comment]
I was able to get it to download mods, though I had to clear out the folder that it downloaded them to first.

Closing this issue as the latest version of Torch works for me now.
