### ISSUE TITLE
Console log shows System.MissingMethodException: Method not found: 'Void PlayerId..ctor(UInt64)' after each login attempt

### ISSUE THREAD

**Issue by ZephyrFerret** [TorchAPI/Torch#430]
- [x] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [x] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:** v1.3.1.141 **SE Version:** 1.197.168

### Expected Behavior
What did you expect to happen?
- To log in normally without any problems

### Observed Behavior
What actually happened?
- Observed players were not able to connect to the server after inputting the password, after testing myself I also could not log in. Console log shows System.MissingMethodException: Method not found: 'Void PlayerId..ctor(UInt64)' after each login attempt.

### Steps to Reproduce
1.  Download the latest torch client v1.3.1.141-master
2.  Extract to its own folder (i just used the downloads folder)
3.  Run program for the first time for its update
4. Close Torch client
5. Run Space Engineers and create a new public save
6. Exit Space Engineers
7.  Move saved game from %Appdata%\Roaming\SpaceEngineers\Saves\"YourSteamID"\ to Downloads\torch-server\Instance\Saves
8. Launch Torch client
9.  Start SE server and wait for everything to finish loading
10.  Attempt to join game in Space Engineers using a separate PC 

### Other Information
![image](https://user-images.githubusercontent.com/78930149/107729176-fbcec300-6ca4-11eb-959f-f01445a407f8.png)

This seems to have been a problem after updating the torch client from v1.3.1.139 to v1.3.1.141 following space engineers update.

This also works on a fresh installation of both client and SE world. No mods were included, and the only plugin I use is Essentials v1.7.1.73-142-gf3be02c through the Torch.api website.

**Comment by ZilgornZeypher** [comment]
Seeing the same thing
`22:45:25.0210 [ERROR]  Keen: System.MissingMethodException: Method not found: 'Void PlayerId..ctor(UInt64)'.
   at Essentials.Patches.SessionDownloadPatch.GetClientCheckpoint(UInt64 steamId)
   at Essentials.Patches.SessionDownloadPatch.GetClientWorld(EndpointId sender) in C:\jenkins\workspace\Torch_Essentials_master\Essentials\Patches\SessionDownloadPatch.cs:line 125
   at Essentials.Patches.SessionDownloadPatch.PatchGetWorld(EndpointId sender) in C:\jenkins\workspace\Torch_Essentials_master\Essentials\Patches\SessionDownloadPatch.cs:line 276
   at Patched_Sandbox.Engine.Multiplayer.MyMultiplayerServerBaseOnWorldRequest_0(Object , EndpointId )
   at Sandbox.Engine.Multiplayer.MyMultiplayerServerBase.WorldRequest(Int32 appVersion)
   at VRage.Network.CallSite`7.Invoke(BitStream stream, Object obj, Boolean validate)
   at VRage.Network.MyReplicationLayer.Invoke(CallSite callSite, BitStream stream, Object obj, EndpointId source, MyClientStateBase clientState, Boolean validate)
   at VRage.Network.MyReplicationServer.OnEvent(MyPacketDataBitStreamBase data, CallSite site, Object obj, IMyNetObject sendAs, Nullable`1 position, EndpointId source)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacketDataBitStreamBase data, NetworkId networkId, NetworkId blockedNetId, UInt32 eventId, EndpointId sender, Nullable`1 position)
   at VRage.Network.MyReplicationLayer.ProcessEvent(MyPacketDataBitStreamBase data, EndpointId sender)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacket packet)
   at Sandbox.Engine.Multiplayer.MyTransportLayer.ProcessMessage(MyPacket p)
   at Sandbox.Engine.Multiplayer.MyTransportLayer.HandleMessage(MyPacket p)
   at Sandbox.Engine.Networking.MyReceiveQueue.Process(NetworkMessageDelegate handler)
System.MissingMethodException: Method not found: 'Void PlayerId..ctor(UInt64)'.
   at Essentials.Patches.SessionDownloadPatch.GetClientCheckpoint(UInt64 steamId)
   at Essentials.Patches.SessionDownloadPatch.GetClientWorld(EndpointId sender) in C:\jenkins\workspace\Torch_Essentials_master\Essentials\Patches\SessionDownloadPatch.cs:line 125
   at Essentials.Patches.SessionDownloadPatch.PatchGetWorld(EndpointId sender) in C:\jenkins\workspace\Torch_Essentials_master\Essentials\Patches\SessionDownloadPatch.cs:line 276
   at Patched_Sandbox.Engine.Multiplayer.MyMultiplayerServerBaseOnWorldRequest_0(Object , EndpointId )
   at Sandbox.Engine.Multiplayer.MyMultiplayerServerBase.WorldRequest(Int32 appVersion)
   at VRage.Network.CallSite`7.Invoke(BitStream stream, Object obj, Boolean validate)
   at VRage.Network.MyReplicationLayer.Invoke(CallSite callSite, BitStream stream, Object obj, EndpointId source, MyClientStateBase clientState, Boolean validate)
   at VRage.Network.MyReplicationServer.OnEvent(MyPacketDataBitStreamBase data, CallSite site, Object obj, IMyNetObject sendAs, Nullable`1 position, EndpointId source)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacketDataBitStreamBase data, NetworkId networkId, NetworkId blockedNetId, UInt32 eventId, EndpointId sender, Nullable`1 position)
   at VRage.Network.MyReplicationLayer.ProcessEvent(MyPacketDataBitStreamBase data, EndpointId sender)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacket packet)
   at Sandbox.Engine.Multiplayer.MyTransportLayer.ProcessMessage(MyPacket p)
   at Sandbox.Engine.Multiplayer.MyTransportLayer.HandleMessage(MyPacket p)
   at Sandbox.Engine.Networking.MyReceiveQueue.Process(NetworkMessageDelegate handler)`

**Comment by wardude202** [comment]
Yea im getting the identical error, ran a new world, tried a bunch of things, cant figure it out.

**Comment by 22SAS-Mazing** [comment]
Same here.

**Comment by jpa77** [comment]
![image](https://user-images.githubusercontent.com/44015685/107782990-6984f880-6d52-11eb-8d4b-eb831be0ef79.png)
Same here, connecting from LAN, no info from players over internet yet.

**Comment by wardude202** [comment]
Seems like a universal problem

**Comment by MathewMantas** [comment]
It's just the update that broke torchapi

**Comment by JoshuaCalhoun** [comment]
I'm getting the same problem on Torch v1.3.1.142

`16:16:54.1895 [ERROR]  Keen: System.MissingMethodException: Method not found: 'Void PlayerId..ctor(UInt64)'.
   at Essentials.Patches.SessionDownloadPatch.GetClientCheckpoint(UInt64 steamId)
   at Essentials.Patches.SessionDownloadPatch.GetClientWorld(EndpointId sender) in C:\jenkins\workspace\Torch_Essentials_master\Essentials\Patches\SessionDownloadPatch.cs:line 125
   at Essentials.Patches.SessionDownloadPatch.PatchGetWorld(EndpointId sender) in C:\jenkins\workspace\Torch_Essentials_master\Essentials\Patches\SessionDownloadPatch.cs:line 276
   at Patched_Sandbox.Engine.Multiplayer.MyMultiplayerServerBaseOnWorldRequest_0(Object , EndpointId )
   at Sandbox.Engine.Multiplayer.MyMultiplayerServerBase.WorldRequest(Int32 appVersion)
   at VRage.Network.CallSite`7.Invoke(BitStream stream, Object obj, Boolean validate)
   at VRage.Network.MyReplicationLayer.Invoke(CallSite callSite, BitStream stream, Object obj, EndpointId source, MyClientStateBase clientState, Boolean validate)
   at VRage.Network.MyReplicationServer.OnEvent(MyPacketDataBitStreamBase data, CallSite site, Object obj, IMyNetObject sendAs, Nullable`1 position, EndpointId source)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacketDataBitStreamBase data, NetworkId networkId, NetworkId blockedNetId, UInt32 eventId, EndpointId sender, Nullable`1 position)
   at VRage.Network.MyReplicationLayer.ProcessEvent(MyPacketDataBitStreamBase data, EndpointId sender)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacket packet)
   at Sandbox.Engine.Multiplayer.MyTransportLayer.ProcessMessage(MyPacket p)
   at Sandbox.Engine.Multiplayer.MyTransportLayer.HandleMessage(MyPacket p)
   at Sandbox.Engine.Networking.MyReceiveQueue.Process(NetworkMessageDelegate handler)
System.MissingMethodException: Method not found: 'Void PlayerId..ctor(UInt64)'.
   at Essentials.Patches.SessionDownloadPatch.GetClientCheckpoint(UInt64 steamId)
   at Essentials.Patches.SessionDownloadPatch.GetClientWorld(EndpointId sender) in C:\jenkins\workspace\Torch_Essentials_master\Essentials\Patches\SessionDownloadPatch.cs:line 125
   at Essentials.Patches.SessionDownloadPatch.PatchGetWorld(EndpointId sender) in C:\jenkins\workspace\Torch_Essentials_master\Essentials\Patches\SessionDownloadPatch.cs:line 276
   at Patched_Sandbox.Engine.Multiplayer.MyMultiplayerServerBaseOnWorldRequest_0(Object , EndpointId )
   at Sandbox.Engine.Multiplayer.MyMultiplayerServerBase.WorldRequest(Int32 appVersion)
   at VRage.Network.CallSite`7.Invoke(BitStream stream, Object obj, Boolean validate)
   at VRage.Network.MyReplicationLayer.Invoke(CallSite callSite, BitStream stream, Object obj, EndpointId source, MyClientStateBase clientState, Boolean validate)
   at VRage.Network.MyReplicationServer.OnEvent(MyPacketDataBitStreamBase data, CallSite site, Object obj, IMyNetObject sendAs, Nullable`1 position, EndpointId source)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacketDataBitStreamBase data, NetworkId networkId, NetworkId blockedNetId, UInt32 eventId, EndpointId sender, Nullable`1 position)
   at VRage.Network.MyReplicationLayer.ProcessEvent(MyPacketDataBitStreamBase data, EndpointId sender)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacket packet)
   at Sandbox.Engine.Multiplayer.MyTransportLayer.ProcessMessage(MyPacket p)
   at Sandbox.Engine.Multiplayer.MyTransportLayer.HandleMessage(MyPacket p)
   at Sandbox.Engine.Networking.MyReceiveQueue.Process(NetworkMessageDelegate handler)`

**Comment by wardude202** [comment]
Download torch  v1.3.1.143 and it should all be fixed

**Comment by 22SAS-Mazing** [comment]
> 
> 
> Download torch v1.3.1.143 and it should all be fixed

Nope. Still happening for me. :(

**Comment by 22SAS-Mazing** [comment]
Any update on the issue?

**Comment by JoshuaCalhoun** [comment]
> Any update on the issue?

As of last night, installing torch v1.3.1.143 fixed the issue for me, we are now able to log into my server with our normal modlist.

**Comment by 22SAS-Mazing** [comment]
Oh ok. This is what I'm getting. I'm assuming it's the same issue.

Torch Version: v1.3.1.143-master
Game Version: 1.197.168

`[ERROR]  Keen: System.MissingMethodException: Method not found: 'Void PlayerId..ctor(UInt64)'.
   at Essentials.Patches.SessionDownloadPatch.GetClientCheckpoint(UInt64 steamId)
   at Essentials.Patches.SessionDownloadPatch.GetClientWorld(EndpointId sender) in C:\jenkins\workspace\Torch_Essentials_master\Essentials\Patches\SessionDownloadPatch.cs:line 125
   at Essentials.Patches.SessionDownloadPatch.PatchGetWorld(EndpointId sender) in C:\jenkins\workspace\Torch_Essentials_master\Essentials\Patches\SessionDownloadPatch.cs:line 276
   at Patched_Sandbox.Engine.Multiplayer.MyMultiplayerServerBaseOnWorldRequest_0(Object , EndpointId )
   at Sandbox.Engine.Multiplayer.MyMultiplayerServerBase.WorldRequest(Int32 appVersion)
   at VRage.Network.CallSite`7.Invoke(BitStream stream, Object obj, Boolean validate)
   at VRage.Network.MyReplicationLayer.Invoke(CallSite callSite, BitStream stream, Object obj, EndpointId source, MyClientStateBase clientState, Boolean validate)
   at VRage.Network.MyReplicationServer.OnEvent(MyPacketDataBitStreamBase data, CallSite site, Object obj, IMyNetObject sendAs, Nullable`1 position, EndpointId source)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacketDataBitStreamBase data, NetworkId networkId, NetworkId blockedNetId, UInt32 eventId, EndpointId sender, Nullable`1 position)
   at VRage.Network.MyReplicationLayer.ProcessEvent(MyPacketDataBitStreamBase data, EndpointId sender)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacket packet)
   at Sandbox.Engine.Multiplayer.MyTransportLayer.ProcessMessage(MyPacket p)
   at Sandbox.Engine.Multiplayer.MyTransportLayer.HandleMessage(MyPacket p)
   at Sandbox.Engine.Networking.MyReceiveQueue.Process(NetworkMessageDelegate handler)
System.MissingMethodException: Method not found: 'Void PlayerId..ctor(UInt64)'.
   at Essentials.Patches.SessionDownloadPatch.GetClientCheckpoint(UInt64 steamId)
   at Essentials.Patches.SessionDownloadPatch.GetClientWorld(EndpointId sender) in C:\jenkins\workspace\Torch_Essentials_master\Essentials\Patches\SessionDownloadPatch.cs:line 125
   at Essentials.Patches.SessionDownloadPatch.PatchGetWorld(EndpointId sender) in C:\jenkins\workspace\Torch_Essentials_master\Essentials\Patches\SessionDownloadPatch.cs:line 276
   at Patched_Sandbox.Engine.Multiplayer.MyMultiplayerServerBaseOnWorldRequest_0(Object , EndpointId )
   at Sandbox.Engine.Multiplayer.MyMultiplayerServerBase.WorldRequest(Int32 appVersion)
   at VRage.Network.CallSite`7.Invoke(BitStream stream, Object obj, Boolean validate)
   at VRage.Network.MyReplicationLayer.Invoke(CallSite callSite, BitStream stream, Object obj, EndpointId source, MyClientStateBase clientState, Boolean validate)
   at VRage.Network.MyReplicationServer.OnEvent(MyPacketDataBitStreamBase data, CallSite site, Object obj, IMyNetObject sendAs, Nullable`1 position, EndpointId source)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacketDataBitStreamBase data, NetworkId networkId, NetworkId blockedNetId, UInt32 eventId, EndpointId sender, Nullable`1 position)
   at VRage.Network.MyReplicationLayer.ProcessEvent(MyPacketDataBitStreamBase data, EndpointId sender)
   at VRage.Network.MyReplicationLayer.OnEvent(MyPacket packet)
   at Sandbox.Engine.Multiplayer.MyTransportLayer.ProcessMessage(MyPacket p)
   at Sandbox.Engine.Multiplayer.MyTransportLayer.HandleMessage(MyPacket p)
   at Sandbox.Engine.Networking.MyReceiveQueue.Process(NetworkMessageDelegate handler)`

**Comment by 22SAS-Mazing** [comment]
A complete reinstall fixed it.
