### ISSUE TITLE
Crash on Save load

### ISSUE THREAD

**Issue by ZilgornZeypher** [TorchAPI/Torch#434]
- [  ] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [  ] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:** 1.3.1.144**SE Version:** 1.197.170

### Expected Behavior
What did you expect to happen?
Server to start normally
### Observed Behavior
What actually happened?
Server did it's thing up until the save load or loading the fresh world and would crash out with the following error.
18:03:09.6954 [INFO]   Keen:    Experimental mode reason: ExperimentalMode, BlockLimitsEnabled, EnableIngameScripts, Mods
18:03:09.6954 [INFO]   Keen:    Console compatibility: No
18:03:30.5630 [INFO]   Keen:    Exception while loading world: An exception(s) was thrown while executing a task.
18:03:30.5710 [INFO]   Keen: Plugin Init: Torch.Server.TorchServer
18:03:30.5710 [INFO]   Keen: Exiting..
18:03:30.5710 [WARN]   TorchSessionManager: Session unloading event occurred when we don't have a session.
18:03:30.6031 [INFO]   Keen: Autosave in unload
 [ERROR]  Keen: System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.Game.World.MySession.GetCheckpoint(String saveName, Boolean isClientRequest)
   at Sandbox.Game.World.MySession.Save(MySessionSnapshot& snapshot, String customSaveName)
System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.Game.World.MySession.GetCheckpoint(String saveName, Boolean isClientRequest)
   at Sandbox.Game.World.MySession.Save(MySessionSnapshot& snapshot, String customSaveName)

### Steps to Reproduce
1. How did this issue get triggered
Starting a modded world or a fresh unmodded world results in crash.
2. Write the steps here.

### Other Information
Provide links to game logs or saves here if necessary.
Gasme log for clean save load attempt.
https://pastebin.com/km0EzzGH

**Comment by ZilgornZeypher** [comment]
Issue was my side nothing to do with Torch please ignore
