### ISSUE TITLE
Failed to compare two elements in the array

### ISSUE THREAD

**Issue by asaurytski-exadel** [TorchAPI/Torch#435]
- [x ] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [ ] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:** 1.144 SE Version:** 1.170

### Expected Behavior
Exception maybe

### Observed Behavior
Torch CRASHED

### Steps to Reproduce
LOG  only - 
21:50:13.8958 [INFO]   Keen: OnEntityInitialized removed entity '86560197786217151:Small Grid 7151' with entity id '86560197786217151'
21:50:16.7790 [INFO]   Keen: OnEntityInitialized removed entity '138875148561018190:Small Grid 8190' with entity id '138875148561018190'
21:50:17.4622 [INFO]   Keen: OnEntityInitialized removed entity '125431049179312717:Small Grid 2717' with entity id '125431049179312717'
21:50:18.1286 [INFO]   Keen: OnEntityInitialized removed entity '124905901012265036:Small Grid 5036' with entity id '124905901012265036'
21:50:18.4960 [INFO]   Keen: OnEntityInitialized removed entity '96116350032862869:Small Grid 2869' with entity id '96116350032862869'
21:50:19.0121 [INFO]   Keen: OnEntityInitialized removed entity '93991583279034949:Small Grid 4949' with entity id '93991583279034949'
21:50:19.4954 [INFO]   Keen: OnEntityInitialized removed entity '105031971707080685:Small Grid 685' with entity id '105031971707080685'
21:50:19.9789 [INFO]   Keen: OnEntityInitialized removed entity '96040373454343489:Small Grid 3489' with entity id '96040373454343489'
21:50:20.8292 [INFO]   Keen: OnEntityInitialized removed entity '89803708629561877:Small Grid 1877' with entity id '89803708629561877'
21:50:22.5121 [INFO]   Keen: OnEntityInitialized removed entity '102451995495553149:Small Grid 3149' with entity id '102451995495553149'
21:50:23.1785 [INFO]   Keen: OnEntityInitialized removed entity '82845863939601862:Small Grid 1862' with entity id '82845863939601862'
21:50:23.4785 [INFO]   Keen: OnEntityInitialized removed entity '102799179533186463:Small Grid 6463' with entity id '102799179533186463'
21:50:25.5285 [INFO]   Keen: OnEntityInitialized removed entity '101428947323287224:Small Grid 7224' with entity id '101428947323287224'
21:50:25.8618 [INFO]   Keen: OnEntityInitialized removed entity '143881907314738866:Small Grid 8866' with entity id '143881907314738866'
21:50:26.3958 [INFO]   Keen: OnEntityInitialized removed entity '107958141647426966:Small Grid 6966' with entity id '107958141647426966'
21:50:27.0118 [INFO]   Keen: OnEntityInitialized removed entity '84443797981307703:Small Grid 7703' with entity id '84443797981307703'
21:50:29.1450 [INFO]   Keen: OnEntityInitialized removed entity '111303895326160502:Small Grid 502' with entity id '111303895326160502'

### Other Information
21:50:25.4344 [FATAL]  Initializer: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Failed to compare two elements in the array. ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Torch.Utils.MiscExtensions.GetGridOwnerName(MyCubeGrid grid) in C:\build\workspace\Torch_Torch_master\Torch\Utils\MiscExtensions.cs:line 65
   at Torch.Server.ViewModels.Entities.EntityViewModel.CompareToSort(EntityViewModel other, SortEnum sort) in C:\build\workspace\Torch_Torch_master\Torch.Server\ViewModels\Entities\EntityViewModel.cs:line 126
   at System.Collections.Generic.ArraySortHelper`1.PickPivotAndPartition(T[] keys, Int32 lo, Int32 hi, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(T[] keys, Int32 lo, Int32 hi, Int32 depthLimit, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(T[] keys, Int32 left, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   --- End of inner exception stack trace ---
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.List`1.Sort(Int32 index, Int32 count, IComparer`1 comparer)
   at Torch.Collections.SortedView`1.Sort(IComparer`1 comparer) in C:\build\workspace\Torch_Torch_master\Torch\Collections\SortedView.cs:line 116
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Window.ShowDialog()
   at Torch.Server.Initializer.Run() in C:\build\workspace\Torch_Torch_master\Torch.Server\Initializer.cs:line 161
   at Torch.Server.Program.Main(String[] args) in C:\build\workspace\Torch_Torch_master\Torch.Server\Program.cs:line 75
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssemblyByName(String assemblyName, String[] args)
   at Torch.Utils.TorchLauncher.Launch(String entryPoint, String[] args, String[] binaryPaths) in C:\build\workspace\Torch_Torch_master\Torch\Utils\TorchLauncher.cs:line 38
   at Torch.Server.Program.Main(String[] args) in C:\build\workspace\Torch_Torch_master\Torch.Server\Program.cs:line 75
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Failed to compare two elements in the array. ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Torch.Utils.MiscExtensions.GetGridOwnerName(MyCubeGrid grid) in C:\build\workspace\Torch_Torch_master\Torch\Utils\MiscExtensions.cs:line 65
   at Torch.Server.ViewModels.Entities.EntityViewModel.CompareToSort(EntityViewModel other, SortEnum sort) in C:\build\workspace\Torch_Torch_master\Torch.Server\ViewModels\Entities\EntityViewModel.cs:line 126
   at System.Collections.Generic.ArraySortHelper`1.PickPivotAndPartition(T[] keys, Int32 lo, Int32 hi, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(T[] keys, Int32 lo, Int32 hi, Int32 depthLimit, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(T[] keys, Int32 left, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   --- End of inner exception stack trace ---
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.List`1.Sort(Int32 index, Int32 count, IComparer`1 comparer)
   at Torch.Collections.SortedView`1.Sort(IComparer`1 comparer) in C:\build\workspace\Torch_Torch_master\Torch\Collections\SortedView.cs:line 116
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Window.ShowDialog()
   at Torch.Server.Initializer.Run() in C:\build\workspace\Torch_Torch_master\Torch.Server\Initializer.cs:line 161
   at Torch.Server.Program.Main(String[] args) in C:\build\workspace\Torch_Torch_master\Torch.Server\Program.cs:line 75
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssemblyByName(String assemblyName, String[] args)
   at Torch.Utils.TorchLauncher.Launch(String entryPoint, String[] args, String[] binaryPaths) in C:\build\workspace\Torch_Torch_master\Torch\Utils\TorchLauncher.cs:line 38
   at Torch.Server.Program.Main(String[] args) in C:\build\workspace\Torch_Torch_master\Torch.Server\Program.cs:line 75
21:50:25.4474 [FATAL]  Initializer: System.InvalidOperationException: Failed to compare two elements in the array. ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Torch.Utils.MiscExtensions.GetGridOwnerName(MyCubeGrid grid) in C:\build\workspace\Torch_Torch_master\Torch\Utils\MiscExtensions.cs:line 65
   at Torch.Server.ViewModels.Entities.EntityViewModel.CompareToSort(EntityViewModel other, SortEnum sort) in C:\build\workspace\Torch_Torch_master\Torch.Server\ViewModels\Entities\EntityViewModel.cs:line 126
   at System.Collections.Generic.ArraySortHelper`1.PickPivotAndPartition(T[] keys, Int32 lo, Int32 hi, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(T[] keys, Int32 lo, Int32 hi, Int32 depthLimit, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(T[] keys, Int32 left, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   --- End of inner exception stack trace ---
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.List`1.Sort(Int32 index, Int32 count, IComparer`1 comparer)
   at Torch.Collections.SortedView`1.Sort(IComparer`1 comparer) in C:\build\workspace\Torch_Torch_master\Torch\Collections\SortedView.cs:line 116
System.InvalidOperationException: Failed to compare two elements in the array. ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Torch.Utils.MiscExtensions.GetGridOwnerName(MyCubeGrid grid) in C:\build\workspace\Torch_Torch_master\Torch\Utils\MiscExtensions.cs:line 65
   at Torch.Server.ViewModels.Entities.EntityViewModel.CompareToSort(EntityViewModel other, SortEnum sort) in C:\build\workspace\Torch_Torch_master\Torch.Server\ViewModels\Entities\EntityViewModel.cs:line 126
   at System.Collections.Generic.ArraySortHelper`1.PickPivotAndPartition(T[] keys, Int32 lo, Int32 hi, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(T[] keys, Int32 lo, Int32 hi, Int32 depthLimit, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(T[] keys, Int32 left, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   --- End of inner exception stack trace ---
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.List`1.Sort(Int32 index, Int32 count, IComparer`1 comparer)
   at Torch.Collections.SortedView`1.Sort(IComparer`1 comparer) in C:\build\workspace\Torch_Torch_master\Torch\Collections\SortedView.cs:line 116
21:50:25.4474 [FATAL]  Initializer: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Torch.Utils.MiscExtensions.GetGridOwnerName(MyCubeGrid grid) in C:\build\workspace\Torch_Torch_master\Torch\Utils\MiscExtensions.cs:line 65
   at Torch.Server.ViewModels.Entities.EntityViewModel.CompareToSort(EntityViewModel other, SortEnum sort) in C:\build\workspace\Torch_Torch_master\Torch.Server\ViewModels\Entities\EntityViewModel.cs:line 126
   at System.Collections.Generic.ArraySortHelper`1.PickPivotAndPartition(T[] keys, Int32 lo, Int32 hi, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(T[] keys, Int32 lo, Int32 hi, Int32 depthLimit, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(T[] keys, Int32 left, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at Torch.Utils.MiscExtensions.GetGridOwnerName(MyCubeGrid grid) in C:\build\workspace\Torch_Torch_master\Torch\Utils\MiscExtensions.cs:line 65
   at Torch.Server.ViewModels.Entities.EntityViewModel.CompareToSort(EntityViewModel other, SortEnum sort) in C:\build\workspace\Torch_Torch_master\Torch.Server\ViewModels\Entities\EntityViewModel.cs:line 126
   at System.Collections.Generic.ArraySortHelper`1.PickPivotAndPartition(T[] keys, Int32 lo, Int32 hi, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(T[] keys, Int32 lo, Int32 hi, Int32 depthLimit, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(T[] keys, Int32 left, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
21:50:25.4474 [INFO]   Initializer: Generating minidump at c:\SERVER-2\torch-server\Instance\Minidump.dmp
21:50:25.4474 [ERROR]  Initializer: Keen broke the minidump, sorry.

**Comment by Bishbash777** [comment]
Please report crashes in the discord #help section
