### ISSUE TITLE
Method not found (EOS related)

### ISSUE THREAD

**Issue by astravexton** [TorchAPI/Torch#439]
**Torch Version:** 1.3.1.146 **SE Version:** 1.197.181

I was running the Torch server for a few hours and restarted it, now when I try to run it it just spits out this into the log file. I've tried a fresh install of Torch too and still get the same error

```
[FATAL]  Initializer: System.MissingMethodException: Method not found: 'Void VRage.EOS.MyEOSService.InitNetworking(Boolean, System.String, VRage.GameServices.IMyGameService, System.String, System.String, System.String, System.String, System.String, System.String, VRage.EOS.IMyEOSPlatform, Boolean, System.String, System.Collections.Generic.IEnumerable`1<System.String>, VRage.GameServices.MyServerDiscoveryAggregator)'.
   at Torch.VRageGame.Create()
   at Torch.VRageGame.Run() in C:\build\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 122
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
System.MissingMethodException: Method not found: 'Void VRage.EOS.MyEOSService.InitNetworking(Boolean, System.String, VRage.GameServices.IMyGameService, System.String, System.String, System.String, System.String, System.String, System.String, VRage.EOS.IMyEOSPlatform, Boolean, System.String, System.Collections.Generic.IEnumerable`1<System.String>, VRage.GameServices.MyServerDiscoveryAggregator)'.
   at Torch.VRageGame.Create()
   at Torch.VRageGame.Run() in C:\build\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 122
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by KenionX** [comment]
get the same issue, after the update

**Comment by dpwlt** [comment]
Same here

**Comment by Belixius** [comment]
Go to https://torchapi.net/download and download the latest version v1.3.1.147-master from yesterday and replace the files with the one in your root folder, had the same error before and it's now working again with this version.
