### ISSUE TITLE
Fetal Error Upon Boot

### ISSUE THREAD

**Issue by tadavispmd040507** [TorchAPI/Torch#445]
- [ Yes ] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [ Yes ] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ No ] Is this a suggestion?

**Torch Version:** 1.3.1.149 **SE Version:** 1.198.31

### Expected Behavior
What did you expect to happen?

Start the server with no errors...

### Observed Behavior
What actually happened?

Server fetal errors upon boot

```
21:53:16.5825 [FATAL]  Initializer: System.Exception: Fatal error during dedicated server init see log for more information.
   at Patched_Sandbox.MySandboxGame.ctor_0(Object windowHandle, String[] , IntPtr )
   at SpaceEngineers.Game.SpaceEngineersGame..ctor(String[] commandlineArgs)
   at Torch.VRageGame.DoStart() in C:\build\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 291
   at Torch.VRageGame.Run() in C:\build\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 123
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
System.Exception: Fatal error during dedicated server init see log for more information.
   at Patched_Sandbox.MySandboxGame.ctor_0(Object windowHandle, String[] , IntPtr )
   at SpaceEngineers.Game.SpaceEngineersGame..ctor(String[] commandlineArgs)
   at Torch.VRageGame.DoStart() in C:\build\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 291
   at Torch.VRageGame.Run() in C:\build\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 123
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

### Steps to Reproduce
1. Setup new server with Torch
2. Start Server and wait for Red Text.

### Other Information
Log: https://drive.google.com/file/d/1pDKYe3dywZJb44Qwkd60XQU3jt9rPsq_/view?usp=sharing

This happens on 2 different servers any help would be much appreciated.

**Comment by tadavispmd040507** [comment]
Fixed

**Comment by StakManOne** [comment]
Do you remember how did you solve it?
