### ISSUE TITLE
Unable to run Torch.Server.exe

### ISSUE THREAD

**Issue by astravexton** [TorchAPI/Torch#447]
- [X] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [x] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:** 1.3.1.149-master **SE Version:** N/A

### Expected Behavior
Torch.Server.exe should download what it needs and show the UI

### Observed Behavior
This is thrown in the console and it closes almost right away without launching
```
Unhandled Exception: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Astra\Downloads\torch-server\DedicatedServer64\steam_api64.dll'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at Torch.Server.Initializer.Initialize(String[] args) in C:\build\workspace\Torch_Torch_master\Torch.Server\Initializer.cs:line 79
   at Torch.Server.Program.Main(String[] args) in C:\build\workspace\Torch_Torch_master\Torch.Server\Program.cs:line 71
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssemblyByName(String assemblyName, String[] args)
   at Torch.Utils.TorchLauncher.Launch(String entryPoint, String[] args, String[] binaryPaths) in C:\build\workspace\Torch_Torch_master\Torch\Utils\TorchLauncher.cs:line 38
   at Torch.Server.Program.Main(String[] args) in C:\build\workspace\Torch_Torch_master\Torch.Server\Program.cs:line 75
```

### Steps to Reproduce
1. Download 1.3.1.149-master from https://torchapi.net/download/Torch
2. Extract all files to any directory
3. Run Torch.Server.exe and wait

**Comment by maximd88** [comment]
same issue here.
Clean new Windows 10 build 21H1

**Comment by RhythmNz** [comment]
same like that https://github.com/TorchAPI/Torch/issues/446

**Comment by astravexton** [comment]
Closed as fixed in https://github.com/ValveSoftware/steam-for-linux/issues/7843
