### ISSUE TITLE
Server crashing on launch

### ISSUE THREAD

**Issue by Rosted420** [TorchAPI/Torch#461]
Im not certain what is crashing the immediate launch of the server.

I simply get this error msg 

19:44:27.7734 [FATAL]  Initializer: System.Exception: Fatal error during dedicated server init see log for more information.
   at Patched_Sandbox.MySandboxGame.ctor_0(Object windowHandle, String[] , IntPtr )
   at SpaceEngineers.Game.SpaceEngineersGame..ctor(String[] commandlineArgs)
   at Torch.VRageGame.DoStart() in C:\build\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 307
   at Torch.VRageGame.Run() in C:\build\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 123
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
System.Exception: Fatal error during dedicated server init see log for more information.
   at Patched_Sandbox.MySandboxGame.ctor_0(Object windowHandle, String[] , IntPtr )
   at SpaceEngineers.Game.SpaceEngineersGame..ctor(String[] commandlineArgs)
   at Torch.VRageGame.DoStart() in C:\build\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 307
   at Torch.VRageGame.Run() in C:\build\workspace\Torch_Torch_master\Torch\VRageGame.cs:line 123
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by Bishbash777** [comment]
Not an issue with torch, please join our discord for help debugging this issue
