### ISSUE TITLE
Concealment Plugin - Sub-grids (wheels, rotors, pistons) detach, explode, and/or go physics crazy on Reveal action

### ISSUE THREAD

**Issue by kurazarrh** [TorchAPI/Torch#50]
**Torch Version:** 1.1.207.007 **SE Version:** 1.182.019

### Expected Behavior
Sub-grids should remain attached to their parent grids and remain stable when grids are revealed, such as on client log in. This is particularly noticeable in planet gravity, since there is a force acting on the subgrids even if the parent grid is stationary.

### Observed Behavior
In my case, logging on to my server would cause my piston gantry to explode and my carrier (with a rotor-based ramp) to take a cruise to the center of the earth. Most vehicles with wheels also would lose their wheels.

The carrier was actually my first medbay in the list, and it got thrown so far and so fast that the server would never stream it to me, and I could not spawn at that medbay.

### Steps to Reproduce
1. Create any sort of planetary base that includes sub-grids, especially with piston heads hanging down with plenty of weight on them (though it doesn't seem to discriminate too much), as well as ships with rotors.
2. Log off the server.
3. Turn Concealment on.
4. Verify that the station has been concealed.
5. Log on.
6. Inspect the locations where subgrids presumably used to be.

### Other Information
GitHub apparently hates me and won't let me upload a zipped world. Let me know if you need one and I can explore other upload options.

**Comment by Varaxian** [comment]
Potentially confirmed. I've been experiencing these, but didn't align it with Torch

**Comment by kurazarrh** [comment]
@Varaxian It's not quite specific to Torch, but to the Concealment plugin. I asked on the Discord server where I should put Concealment-related bugs (here or on the empty Concealment bug tracker), but no one replied. Try it with Concealment enabled and disabled; it makes a world of difference.

**Comment by Varaxian** [comment]
I had all folders, files and permissions set to administrator, followed by
running as admin. World wouldn't save and lots of other errors.
Compatibility tool automatically sorts permissions. It's likely that is
your issue. I would suggest trying it before discounting it as a
possibility. But yes, could be a bug. Nobody else is experiencing it that
I've heard of.

**Comment by Jimmacle** [comment]
It's probably due to physics being reactivated which puts us at the mercy of Clang (read: Keen fixing their own physics issues). I'll leave the issue open but the plugin already does as much as it can to mitigate physics problems.

**Comment by kurazarrh** [comment]
@Jimmacle I haven't had a chance to test this lately, but could this be a load-order issue? Granted, while this could be caused in part by how Keen does physics, the application probably isn't built to expect a feature like Concealment. Could this issue (if it's still around, I'll have to fiddle with it tonight) be resolved by having Concealment identify all attached grids/subgrids and wait to reveal any of the grids until all of them are ready to be revealed, and suspend physics on all of them until the reveal process is complete for all attached sub/grids?

**Comment by Equinox-** [comment]
I've identified a possible fix.  (Keen now allows you to reactive physics objects in batches)  However I haven't been able to reproduce this myself, so a world would be helpful @kurazarrh

**Comment by kurazarrh** [comment]
@Equinox- take a look at the attached world file. I've included the .cfg file in case you need it to load up. Note that, while there are mods associated with this save file, this has been tested both with mods on and off.

You may need to edit the world to allow yourself to spawn at one of the medbays on the planet owned by the IND / Inertial Derpeners faction. Let me know if you need anything further from me. I can possibly also test/recreate this again tonight and capture some video footage if need be.

[PlanetPunchers.zip](https://github.com/TorchAPI/Torch/files/1245545/PlanetPunchers.zip)

**Comment by Varaxian** [comment]
Semi related, Jim. I'm receiving reports that land gear are causing a
concealment related crash. I haven't verified it myself. Talk @Baur and see
if he can get you any logs.

**Comment by Equinox-** [comment]
@kurazarrh Try out this patch, let me know if it works for you.  [Jenkins](http://server.torchapi.net:8080/job/Torch/job/Concealment/job/patch-50/1/artifact/)

**Comment by kurazarrh** [comment]
@Equinox- I'm getting the error pasted below. However, from our Discord discussion, I understand this might just have to wait. Hope this is still useful, though.

12:12:39.9220 [FATAL] Torch: System.MissingMethodException: Method not found: 'Void Torch.API.Plugins.PluginAttribute..ctor(System.String, System.Type, System.String)'.
   at System.ModuleHandle.ResolveMethod(RuntimeModule module, Int32 methodToken, IntPtr* typeInstArgs, Int32 typeInstCount, IntPtr* methodInstArgs, Int32 methodInstCount)
   at System.ModuleHandle.ResolveMethodHandleInternalCore(RuntimeModule module, Int32 methodToken, IntPtr[] typeInstantiationContext, Int32 typeInstCount, IntPtr[] methodInstantiationContext, Int32 methodInstCount)
   at System.ModuleHandle.ResolveMethodHandleInternal(RuntimeModule module, Int32 methodToken, RuntimeTypeHandle[] typeInstantiationContext, RuntimeTypeHandle[] methodInstantiationContext)
   at System.Reflection.CustomAttribute.FilterCustomAttributeRecord(CustomAttributeRecord caRecord, MetadataImport scope, Assembly& lastAptcaOkAssembly, RuntimeModule decoratedModule, MetadataToken decoratedToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, Object[] attributes, IList derivedAttributes, RuntimeType& attributeType, IRuntimeMethodInfo& ctor, Boolean& ctorHasParameters, Boolean& isVarArg)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType, Boolean mustBeInheritable, IList derivedAttributes, Boolean isDecoratedTargetSecurityTransparent)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeType type, RuntimeType caType, Boolean inherit)
   at System.Attribute.GetCustomAttributes(MemberInfo element, Type type, Boolean inherit)
   at System.Attribute.GetCustomAttribute(MemberInfo element, Type attributeType, Boolean inherit)
   at System.Reflection.CustomAttributeExtensions.GetCustomAttribute[T](MemberInfo element)
   at Torch.Managers.PluginManager.LoadPlugins() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_master-MDSK25APJZH3CKHWQZDBKPUEFGHPIOFDYJGXZQ5Z5BITFXNFOV5A\Torch\Managers\PluginManager.cs:line 109
   at Torch.Server.TorchServer.Init() in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_master-MDSK25APJZH3CKHWQZDBKPUEFGHPIOFDYJGXZQ5Z5BITFXNFOV5A\Torch.Server\TorchServer.cs:line 94
   at Torch.Server.Program.RunServer(TorchConfig config) in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_master-MDSK25APJZH3CKHWQZDBKPUEFGHPIOFDYJGXZQ5Z5BITFXNFOV5A\Torch.Server\Program.cs:line 253
   at Torch.Server.Program.Main(String[] args) in C:\Program Files (x86)\Jenkins\workspace\Torch_Torch_master-MDSK25APJZH3CKHWQZDBKPUEFGHPIOFDYJGXZQ5Z5BITFXNFOV5A\Torch.Server\Program.cs:line 104

**Comment by Equinox-** [comment]
That's from not using Torch staging.  Currently you have to use Torch
staging regardless.
