### ISSUE TITLE
Server crashing on launch after Windows Update

### ISSUE THREAD

**Issue by StakManOne** [TorchAPI/Torch#517]
I have managed to set up a server that worked ok for the better part of the day.
The PC even went to sleep and when I woke it back up, the server was still up and running, my friends got kicked out, but once it woke back up, they managed to reconnect and no progress was lost during this time.
After everyone online left, I closed it and proceeded to close the host PC and let Windows (10) perform the latest updates.
The next day, I tried launching the server and this is the error messages that I received:

13:50:25.1568 [INFO]   Torch: Starting server.
13:50:29.0115 [FATAL]  Initializer: System.Exception: Fatal error during dedicated server init see log for more information.
   at Patched_Sandbox.MySandboxGame.ctor_0(Object windowHandle, String[] , IntPtr )
   at SpaceEngineers.Game.SpaceEngineersGame..ctor(String[] commandlineArgs)
   at Torch.VRageGame.DoStart() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\VRageGame.cs:line 307
   at Torch.VRageGame.Run() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\VRageGame.cs:line 123
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
System.Exception: Fatal error during dedicated server init see log for more information.
   at Patched_Sandbox.MySandboxGame.ctor_0(Object windowHandle, String[] , IntPtr )
   at SpaceEngineers.Game.SpaceEngineersGame..ctor(String[] commandlineArgs)
   at Torch.VRageGame.DoStart() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\VRageGame.cs:line 307
   at Torch.VRageGame.Run() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\VRageGame.cs:line 123
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)[Logs.zip](https://github.com/TorchAPI/Torch/files/10077677/Logs.zip)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
13:50:29.0115 [INFO]   Initializer: Generating minidump at Logs\MiniDumpT15-2022-11-23 13-50-29.dmp

Tried using a different save file, to rule out if the previous save was corrupt. Issue persisted.

**Torch Version:** v1.3.1.212-master **SE Version:** 1.201.013

**Comment by StakManOne** [comment]
Started the latest Torch version on another PC with the original save file.
It launched without any issues.

**Comment by Bishbash777** [comment]
Closing. 

The port is already in use... See keen log

Bind IP : 0.0.0.0:27016
13:36:20.1418 [INFO]   Keen:    Error binding server endpoint: Only one usage of each socket address (protocol/network address/port) is normally permitted
