### ISSUE TITLE
Torch API Server Dialog Fails to Start

### ISSUE THREAD

**Issue by SCBionicle** [TorchAPI/Torch#540]
- [x] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [x] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:** 1.3.1.223 (latest downloadable from Torchapi.com) **SE Version:** 1.202.066

### Expected Behavior
What did you expect to happen?
Server dialog begin to load world configuration.

### Observed Behavior
What actually happened?
When Torch reaches initialize server step, it will show an error message and then CTD.

### Steps to Reproduce
1. Update to the latest version of Space Engineers
2. Launch Torch Server

### Other Information
Provide links to game logs or saves here if necessary.
`13:33:47.0920 [INFO]   MessageSizeLimitPatch: Patched MessageSizeLimit
13:33:47.0920 [INFO]   PatchManager: Patching begins...
13:33:47.1560 [INFO]   PatchManager: Patched 2/14.  (14%)
13:33:47.1560 [INFO]   PatchManager: Patched 3/14.  (21%)
13:33:47.1605 [INFO]   PatchManager: Patched 5/14.  (35%)
13:33:47.1605 [INFO]   PatchManager: Patched 6/14.  (42%)
13:33:47.1605 [INFO]   PatchManager: Patched 7/14.  (50%)
13:33:47.1605 [INFO]   PatchManager: Patched 9/14.  (64%)
13:33:47.1605 [INFO]   PatchManager: Patched 10/14.  (71%)
13:33:47.1605 [INFO]   PatchManager: Patched 12/14.  (85%)
13:33:47.1740 [INFO]   PatchManager: Patched 13/14.  (92%)
13:33:47.1740 [INFO]   PatchManager: Patched 14/14.  (100%)
13:33:47.1740 [INFO]   PatchManager: Patching done
13:33:47.1740 [INFO]   ModsDownloadingPatch: Patching mods downloading
13:33:47.1955 [INFO]   PromotePatch: patching promote
13:33:47.1955 [INFO]   ServerResponsePatch: Patching Steam response polling
13:33:47.1955 [INFO]   SteamLoginPatch: Applied custom WaitStart timeout
13:33:47.2125 [INFO]   Torch: Initializing server
13:33:47.7025 [FATAL]  Initializer: System.NullReferenceException: Object reference not set to an instance of an object.
   at Torch.Patches.ObjectFactoryInitPatch.ComponentTypeFactory_AddIdSafe(Type type, MyStringId id) in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\Patches\ObjectFactoryInitPatch.cs:line 135
   at Torch.Patches.ObjectFactoryInitPatch.ComponentTypeFactory_RegisterFromAssemblySafe(Assembly assembly) in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\Patches\ObjectFactoryInitPatch.cs:line 121
   at Torch.Patches.ObjectFactoryInitPatch.ForceRegisterAssemblies() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\Patches\ObjectFactoryInitPatch.cs:line 58
   at Torch.TorchBase.Init() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\TorchBase.cs:line 315
   at Torch.Server.TorchServer.Init() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch.Server\TorchServer.cs:line 145
   at Torch.Server.Initializer.<Run>b__23_0() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch.Server\Initializer.cs:line 156
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
System.NullReferenceException: Object reference not set to an instance of an object.
   at Torch.Patches.ObjectFactoryInitPatch.ComponentTypeFactory_AddIdSafe(Type type, MyStringId id) in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\Patches\ObjectFactoryInitPatch.cs:line 135
   at Torch.Patches.ObjectFactoryInitPatch.ComponentTypeFactory_RegisterFromAssemblySafe(Assembly assembly) in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\Patches\ObjectFactoryInitPatch.cs:line 121
   at Torch.Patches.ObjectFactoryInitPatch.ForceRegisterAssemblies() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\Patches\ObjectFactoryInitPatch.cs:line 58
   at Torch.TorchBase.Init() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\TorchBase.cs:line 315
   at Torch.Server.TorchServer.Init() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch.Server\TorchServer.cs:line 145
   at Torch.Server.Initializer.<Run>b__23_0() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch.Server\Initializer.cs:line 156
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
13:33:47.7110 [INFO]   Initializer: Generating minidump at Logs\MiniDumpT5-2023-04-13 13-33-47.dmp`

[MiniDumpT5-2023-04-13 13-33-47.dmp](https://github.com/TorchAPI/Torch/files/11225502/MiniDumpT5-2023-04-13.13-33-47.zip)

**Comment by WTFSajuuk** [comment]
Got the same issue
Attached my logs as well if needed
[Torch-2023-04-13.log](https://github.com/TorchAPI/Torch/files/11225849/Torch-2023-04-13.log)

**Comment by Neshfi** [comment]
I can confirm that I had the same issue. Seems that the auto update it broken after merging https://github.com/TorchAPI/Torch/pull/538.

@WTFSajuuk @SCBionicle A workaround for now is to manually update your server by downloading the latest Release (https://build.torchapi.com/job/Torch/job/master/lastSuccessfulBuild/artifact/bin/torch-server.zip) and place those files in your torch server, replacing the old ones.

**Comment by WTFSajuuk** [comment]
> I can confirm that I had the same issue. Seems that the auto update it broken after merging #538.
> 
> @WTFSajuuk @SCBionicle A workaround for now is to manually update your server by downloading the latest successful build (https://build.torchapi.com/job/Torch/job/master/lastSuccessfulBuild/artifact/bin/torch-server.zip) and place those files in your torch server, replacing the old ones.

This fixed the issue for me thank you for the quick update

**Comment by joepizuro** [comment]
> I can confirm that I had the same issue. Seems that the auto update it broken after merging #538.
> 
> @WTFSajuuk @SCBionicle A workaround for now is to manually update your server by downloading the latest successful build (https://build.torchapi.com/job/Torch/job/master/lastSuccessfulBuild/artifact/bin/torch-server.zip) and place those files in your torch server, replacing the old ones.

This fixed my issue aswell! Thank you.
