### ISSUE TITLE
Unable to launch Torch today, Was working Yesterday

### ISSUE THREAD

**Issue by SunsetStationuser** [TorchAPI/Torch#550]
- [1 ] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [ 1] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:** 1.x.xxx.xxx **SE Version:** 1.xxx.xxx

### Expected Behavior
What did you expect to happen? 
Expected to launch server from Torch EXE

### Observed Behavior
What actually happened? Torch crashes shortly after launching.

### Steps to Reproduce
1. Launch Server, Proceed to be unable to play
2. Download fresh install of latest sucessful build, attempt to launch.

### Other Information
11:11:30.0624 [INFO]   Torch: Executing directory: C:\Users\Administrator\Desktop\Torch Server Newest\
11:11:30.0684 [INFO]   PluginManager: Loading plugins...
11:11:30.0684 [INFO]   PluginManager: Loaded 0 plugins.
11:11:30.0874 [FATAL]  Initializer: System.MissingMethodException: Method not found: 'Void Sandbox.MyInitializer.InvokeBeforeRun(UInt32, System.String, System.String, Boolean, Int32, System.Action)'.
   at Torch.VRageGame.Create()
   at Torch.VRageGame.Run() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\VRageGame.cs:line 122
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
System.MissingMethodException: Method not found: 'Void Sandbox.MyInitializer.InvokeBeforeRun(UInt32, System.String, System.String, Boolean, Int32, System.Action)'.
   at Torch.VRageGame.Create()
   at Torch.VRageGame.Run() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\VRageGame.cs:line 122
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
11:11:30.1254 [INFO]   Initializer: Generating minidump at Logs\MiniDumpT16-2023-05-11 11-11-30.dmp

**Comment by three7s** [comment]
Same on our server. New SE update broke the torch server manager load process.
right after loading with or without plugins.

**Comment by KeeperOfPurgatory** [comment]
Confirming same issue. This was right after receiving a message on logging off from game that a new Space Engineers version was available and updating. Re-downloaded Torch from Git and problem persists. 

There is also no c:\programdata\Jenkins.jenkins folder, or a C:\Program Files (x86)\Jenkins directory does not exist.

Snap of errors:
14:21:58.0481 [FATAL]  Initializer: System.MissingMethodException: Method not found: 'Void Sandbox.MyInitializer.InvokeBeforeRun(UInt32, System.String, System.String, Boolean, Int32, System.Action)'.
   at Torch.VRageGame.Create()
   at Torch.VRageGame.Run() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\VRageGame.cs:line 122
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
System.MissingMethodException: Method not found: 'Void Sandbox.MyInitializer.InvokeBeforeRun(UInt32, System.String, System.String, Boolean, Int32, System.Action)'.
   at Torch.VRageGame.Create()
   at Torch.VRageGame.Run() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\VRageGame.cs:line 122
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
14:21:58.0721 [INFO]   Initializer: Generating minidump at Logs\MiniDumpT5-2023-05-11 14-21-58.dmp

**Comment by MacAttack-UK** [comment]
I'm also having the same issue with same error as above, Keen done broke it :)

**Comment by JJSeventies** [comment]
Confirming same issue.

**Comment by three7s** [comment]
> I'm also having the same issue with same error as above, Keen done broke it :)

Again...

**Comment by JJSeventies** [comment]
I'm relatively new to torch, does anyone have any idea how fast turnaround times are on here?  is it worth me checking back hourly, daily, weekly etc?  Not pushing, the devs will do it when they can, just curious to let my players know...

**Comment by three7s** [comment]
Can't say I've seen "this" kind of error. So it's hard to say when the Torch devs will see our issue ticket.

**Comment by SunsetStationuser** [comment]
Wow.. Thanks Guys.. The confirmations are nice to see, Based on the activity, I would expect we should receive an update within a week or so. Thanks again to the Dev's for their hard work.

**Comment by SunsetStationuser** [comment]
ok wow nice, should see something within a day or two then

**Comment by michi84o** [comment]
Just checked out the sourcecode myself.
They added a new argument to SandBox.MyInitializer.InvokeBeforeRun(), called "rootPath" which wasn't there before:

`public static void InvokeBeforeRun(uint appId, string appName, string rootPath, string userDataPath, bool addDateToLog = false, int maxLogAge = -1, Action onConfigChangedCallback = null)`

If you fix that the next error is a new argument called "useEOSLobbyDiscovery" at MyEOSService.InitNetworking().
If yout fix that it shows a missing argument for MyModIoService.Create().
This pattern will probably continue. Looks like they changed a lot.

Figuring out what the new arguments for these methods do and fixing them will probably take a while, so I wouldn't expect a quick fix.

**Comment by etilley** [comment]
Im still pretty new at using Torch. is there an easy way to launch the server without torch until they get this fixed?

**Comment by JJSeventies** [comment]
> Im still pretty new at using Torch. is there an easy way to launch the server without torch until they get this fixed?

Great question....

**Comment by three7s** [comment]
Re-download the torch sever zip and copy file to torch directory. Started up after the new update.

**Comment by etilley** [comment]
> Re-download the torch sever zip and copy file to torch directory. Started up after the new update.

yep working again!

**Comment by coolfarmer** [comment]
Damn, why didn't I come across this thread before updating my server.
It feels like getting out of your car without taking the keys first...

**Comment by SunsetStationuser** [comment]
Can close this as resolved, as mentioned previously this has been fixed
