### ISSUE TITLE
Torch CTD on UI Launch

### ISSUE THREAD

**Issue by SCBionicle** [TorchAPI/Torch#551]
- [x] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [x] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:** 1.3.1.228 **SE Version:** 1.202.112

### Expected Behavior
What did you expect to happen?
Not crashing to desktop on launch.
### Observed Behavior
What actually happened?
Fatal error occurred and needs to close. Same error occurs without the plugins installed.
### Steps to Reproduce
1. Launch Torch
2. Wait for error

### Other Information
Provide links to game logs or saves here if necessary.
`12:53:00.4663 [INFO]   MessageSizeLimitPatch: Patched MessageSizeLimit
12:53:00.4663 [INFO]   PatchManager: Patching begins...
12:53:00.5269 [INFO]   PatchManager: Patched 2/14.  (14%)
12:53:00.5269 [INFO]   PatchManager: Patched 3/14.  (21%)
12:53:00.5269 [INFO]   PatchManager: Patched 5/14.  (35%)
12:53:00.5269 [INFO]   PatchManager: Patched 6/14.  (42%)
12:53:00.5269 [INFO]   PatchManager: Patched 7/14.  (50%)
12:53:00.5269 [INFO]   PatchManager: Patched 9/14.  (64%)
12:53:00.5269 [INFO]   PatchManager: Patched 10/14.  (71%)
12:53:00.5269 [INFO]   PatchManager: Patched 12/14.  (85%)
12:53:00.5472 [INFO]   PatchManager: Patched 13/14.  (92%)
12:53:00.5472 [INFO]   PatchManager: Patched 14/14.  (100%)
12:53:00.5472 [INFO]   PatchManager: Patching done
12:53:00.5472 [INFO]   ModsDownloadingPatch: Patching mods downloading
12:53:00.5656 [INFO]   PromotePatch: patching promote
12:53:00.5656 [INFO]   ServerResponsePatch: Patching Steam response polling
12:53:00.5656 [INFO]   SteamLoginPatch: Applied custom WaitStart timeout
12:53:00.5810 [INFO]   Torch: Initializing server
12:53:00.7136 [INFO]   Torch: RELEASE
12:53:00.7136 [INFO]   Torch: Torch Version: v1.3.1.228-master
12:53:00.7136 [INFO]   Torch: Game Version: 1.202.112
12:53:00.7136 [INFO]   Torch: Executing assembly: Torch.Server, Version=1.3.1.228, Culture=neutral, PublicKeyToken=null
12:53:00.7136 [INFO]   Torch: Executing directory: C:\SE Server\
12:53:00.7166 [INFO]   PluginManager: Loading plugins...
12:53:00.7409 [INFO]   PluginManager: Checking for plugin updates...
12:53:02.3715 [INFO]   PluginManager: Updated 0 plugins.
12:53:02.4276 [INFO]   PluginManager: Loading plugin at ALE_DeleteTracker.DeleteTrackerPlugin
12:53:02.4276 [INFO]   PluginManager: Loading plugin 'ALE DeleteTracker' (v1.0.2.4)
12:53:02.5016 [INFO]   PluginManager: Loading plugin at ALE_GridBackup.GridBackupPlugin
12:53:02.5016 [INFO]   PluginManager: Loading plugin 'ALE Grid Backup' (v1.0.5.6)
12:53:02.5528 [INFO]   PluginManager: Loading plugin at ALE_RespawnFix.RespawnFixPlugin
12:53:02.5528 [INFO]   PluginManager: Loading plugin 'ALE RespawnFix' (v1.0.2.1)
12:53:02.6000 [INFO]   PluginManager: Loading plugin at ALE_ShipFixer.ShipFixerPlugin
12:53:02.6000 [INFO]   PluginManager: Loading plugin 'ALE ShipFixer' (v1.0.9.3)
12:53:02.6516 [INFO]   PluginManager: Loading plugin at Concealment.ConcealmentPlugin
12:53:02.6516 [INFO]   PluginManager: Loading plugin 'Concealment' (v1.4.1.24-23-g3049d87)
12:53:02.7490 [INFO]   PluginManager: Loading plugin at DePatch.DePatchPlugin
12:53:02.7490 [INFO]   PluginManager: Loading plugin 'DePatch' (1.20.05)
12:53:02.9332 [INFO]   ChatMessagePatch: Patched OnChatMessageReceived_Server!
12:53:02.9332 [INFO]   PluginManager: Loading plugin at Essentials.EssentialsPlugin
12:53:02.9332 [INFO]   PluginManager: Loading plugin 'Essentials' (v1.7.1.178-001-55b53d6)
12:53:02.9655 [INFO]   PluginManager: Loading plugin at GridSplitNameKeeper.PluginCore
12:53:02.9655 [INFO]   PluginManager: Loading plugin 'GridSplitNameKeeper' (v1.1.605-25c4d229)
12:53:03.0733 [INFO]   PluginManager: Loading plugin at MultigridProjectorServer.MultigridProjectorPlugin
12:53:03.0733 [INFO]   PluginManager: Loading plugin 'Multigrid Projector' (v0.4.16)
12:53:03.1418 [INFO]   PluginManager: Loading plugin at TorchPlugin.Plugin
12:53:03.1418 [INFO]   PluginManager: Loading plugin 'PerformanceImprovements' (v1.10.8.0)
12:53:03.1418 [INFO]   Plugin: IsMessageSpam Patched Successfully!
12:53:03.1418 [INFO]   PluginManager: Loading plugin at PrivatizeSpamMessage.Plugin
12:53:03.1418 [INFO]   PluginManager: Loading plugin 'PrivatizeSpamMessage' (v1.0.0)
12:53:03.1925 [INFO]   ModAdditionPatch: Patch()
12:53:03.1925 [INFO]   PluginManager: Loading plugin at Profiler.ProfilerPlugin
12:53:03.1925 [INFO]   PluginManager: Loading plugin 'Profiler' (v3.1.8432.28870)
12:53:03.3092 [INFO]   PluginManager: Loading plugin at QuantumHangar.Hangar
12:53:03.3092 [INFO]   PluginManager: Loading plugin 'Quantum Hangar' (v3.2.29)
12:53:03.3609 [INFO]   PluginManager: Loading plugin at SearchCommand.SearchCommandPlugin
12:53:03.3609 [INFO]   PluginManager: Loading plugin 'Torch Search' (v1.0.7928.42274)
12:53:03.3778 [INFO]   PluginManager: Loading plugin at VoxelDefender.DefenderPlugin
12:53:03.3778 [INFO]   PluginManager: Loading plugin 'VoxelDefender' (1.0.0.4)
12:53:03.4180 [INFO]   Hangar: Starting plugin WITHOUT the Hangar Market!
12:53:03.4508 [INFO]   DefenderPlugin: Attempting to load config from C:\SE Server\Instance\Defender.cfg
12:53:03.4508 [INFO]   PerformanceImprovements: Init
12:53:04.5986 [INFO]   Essentials: Attempting to load config from C:\SE Server\Instance\Essentials.cfg
12:53:04.6448 [INFO]   DePatchPlugin: Mod Loader Complete overriding
12:53:04.7004 [INFO]   Multigrid Projector: : Loaded server plugin
12:53:04.7004 [INFO]   FileLoggingConfigurator: Reconfigured; pattern=ProfilerPlugin.*, wpf=True, minlevel=Info
12:53:04.7227 [INFO]   PluginManager: Loaded 15 plugins.
12:53:04.7227 [FATAL]  Initializer: System.MissingMethodException: Method not found: 'Void Sandbox.MyInitializer.InvokeBeforeRun(UInt32, System.String, System.String, Boolean, Int32, System.Action)'.
   at Torch.VRageGame.Create()
   at Torch.VRageGame.Run() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\VRageGame.cs:line 122
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
System.MissingMethodException: Method not found: 'Void Sandbox.MyInitializer.InvokeBeforeRun(UInt32, System.String, System.String, Boolean, Int32, System.Action)'.
   at Torch.VRageGame.Create()
   at Torch.VRageGame.Run() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\VRageGame.cs:line 122
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
12:53:04.7302 [INFO]   Initializer: Generating minidump at Logs\MiniDumpT35-2023-05-12 12-53-04.dmp`

**Comment by SCBionicle** [comment]
Manually update to the latest version based on #550 fix this.
