### ISSUE TITLE
Unhandled Exeption on Torch startup

### ISSUE THREAD

**Issue by crazyduck33** [TorchAPI/Torch#554]
I get this Error after i launch Torch, it happens during the regular Torch startup before the Server itself is startet.

If i remove this Plugin the same Error show up with another Plugin, if i remove that too Error shows up again with another Plugin so it stay this error for all Plugins.

Reinstalling Plugins and torch did not help.

15:12:42.6086 [ERROR]  Persistent`1: System.InvalidOperationException: There is an error in XML document (5, 4). ---> System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderLightningManagerConfig.Read3_LightningManagerConfig(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderLightningManagerConfig.Read4_LightningManagerConfig()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at Torch.Persistent`1.Load(String path, Boolean saveIfNew) in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\Persistent.cs:line 88
System.InvalidOperationException: There is an error in XML document (5, 4). ---> System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderLightningManagerConfig.Read3_LightningManagerConfig(Boolean isNullable, Boolean checkType)
   at Microsoft.Xml.Serialization.GeneratedAssembly.XmlSerializationReaderLightningManagerConfig.Read4_LightningManagerConfig()
   --- End of inner exception stack trace ---
   at System.Xml.Serialization.XmlSerializer.Deserialize(XmlReader xmlReader, String encodingStyle, XmlDeserializationEvents events)
   at System.Xml.Serialization.XmlSerializer.Deserialize(TextReader textReader)
   at Torch.Persistent`1.Load(String path, Boolean saveIfNew) in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\Persistent.cs:line 88

**Comment by Bishbash777** [comment]
Error in your world file.
