### ISSUE TITLE
error after trying to start server (S.E)

### ISSUE THREAD

**Issue by klen-ghost** [TorchAPI/Torch#555]
- [ ] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [ ] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:** 1.3.1.23 **SE Version:** 1.202.117

### Expected Behavior
What did you expect to happen? 
boot up the dedicated server

### Observed Behavior
a purple tekst in the log window and then a bunch of red error text..

until 11:27:06.6208 it is white . then the [WARN] a purpple line of text . then all becomes red

11:25:15.7627 [INFO]   MessageSizeLimitPatch: Patched MessageSizeLimit
11:25:15.7627 [INFO]   PatchManager: Patching begins...
11:25:16.7414 [INFO]   PatchManager: Patched 2/14.  (14%)
11:25:16.7414 [INFO]   PatchManager: Patched 3/14.  (21%)
11:25:16.7803 [INFO]   PatchManager: Patched 5/14.  (35%)
11:25:16.7803 [INFO]   PatchManager: Patched 6/14.  (42%)
11:25:16.7803 [INFO]   PatchManager: Patched 7/14.  (50%)
11:25:16.7803 [INFO]   PatchManager: Patched 9/14.  (64%)
11:25:16.7803 [INFO]   PatchManager: Patched 10/14.  (71%)
11:25:16.7803 [INFO]   PatchManager: Patched 12/14.  (85%)
11:25:16.8033 [INFO]   PatchManager: Patched 13/14.  (92%)
11:25:16.8033 [INFO]   PatchManager: Patched 14/14.  (100%)
11:25:16.8033 [INFO]   PatchManager: Patching done
11:25:16.8033 [INFO]   ModsDownloadingPatch: Patching mods downloading
11:25:19.4607 [INFO]   PromotePatch: patching promote
11:25:19.4607 [INFO]   ServerResponsePatch: Patching Steam response polling
11:25:19.4607 [INFO]   SteamLoginPatch: Applied custom WaitStart timeout
11:25:19.4857 [INFO]   UpdateManager: Checking for Torch Update...
11:25:19.7114 [INFO]   Torch: Initializing server
11:25:20.0774 [INFO]   UpdateManager: Torch is up to date.
11:25:23.2989 [INFO]   Torch: RELEASE
11:25:23.2989 [INFO]   Torch: Torch Version: v1.3.1.234-master
11:25:23.2989 [INFO]   Torch: Game Version: 1.202.117
11:25:23.2989 [INFO]   Torch: Executing assembly: Torch.Server, Version=1.3.1.234, Culture=neutral, PublicKeyToken=null
11:25:23.2989 [INFO]   Torch: Executing directory: D:\torch game servers\
11:25:23.3039 [INFO]   PluginManager: Loading plugins...
11:25:23.3039 [INFO]   PluginManager: Checking for plugin updates...
11:25:23.3039 [INFO]   PluginManager: Updated 0 plugins.
11:25:23.3179 [INFO]   PluginManager: Loaded 0 plugins.
11:25:30.9956 [INFO]   Keen: App Version: 01_202_117
11:25:31.0086 [INFO]   Keen: Is official: True [NO][NIS][NAMP]
11:25:31.0086 [INFO]   Keen: Environment.ProcessorCount: 4
11:25:31.3671 [INFO]   Keen: Environment.OSVersion: Microsoft Windows 10 Pro (Microsoft Windows NT 6.2.9200.0)
11:25:31.3671 [INFO]   Keen: Environment.CommandLine: "D:\torch game servers\Torch.Server.exe" 
11:25:31.3671 [INFO]   Keen: Environment.Is64BitProcess: True
11:25:31.3671 [INFO]   Keen: Environment.Is64BitOperatingSystem: True
11:25:31.3671 [INFO]   Keen: Environment.Version: .NET Framework 4.8.4614.0
11:25:31.3671 [INFO]   Keen: Environment.CurrentDirectory: D:\torch game servers
11:25:31.5337 [INFO]   Keen: CPU Info: Intel(R) Core(TM) i5-4670S CPU @ 3.10GHz
11:25:31.5386 [INFO]   VRageGame: Loading Dedicated Config
11:25:31.7498 [INFO]   VRageGame: Initializing network services
11:25:31.7647 [INFO]   VRageGame: Initializing services
11:25:31.7647 [INFO]   VRageGame: Services initialized
11:25:31.8846 [INFO]   VRageGame: Setting up serializers
11:25:37.3077 [INFO]   InstanceManager: Loading instance D:\torch game servers\Instance
11:25:42.5308 [INFO]   ModListControl: Instance loaded.
11:25:42.5308 [INFO]   Torch: Initialized server 'Instance' at 'D:\torch game servers\Instance'
11:25:47.9955 [INFO]   ConfigDedicatedViewModel: Mods Info successfully retrieved!
11:25:48.0796 [INFO]   ConfigDedicatedViewModel: Mods Info successfully retrieved!
11:26:27.1680 [INFO]   InstanceManager: Saved dedicated config.
11:26:27.9155 [INFO]   InstanceManager: Saved world config.
11:26:27.9155 [INFO]   PatchManager: Patching begins...
11:26:27.9305 [INFO]   PatchManager: Patched 2/11.  (18%)
11:26:27.9305 [INFO]   PatchManager: Patched 3/11.  (27%)
11:26:27.9305 [INFO]   PatchManager: Patched 4/11.  (36%)
11:26:27.9975 [INFO]   PatchManager: Patched 5/11.  (45%)
11:26:27.9975 [INFO]   ServerResponsePatch: Patching Steam response timeout to 5 seconds
11:26:28.0085 [INFO]   PatchManager: Patched 6/11.  (54%)
11:26:28.0085 [INFO]   PatchManager: Patched 7/11.  (63%)
11:26:28.0085 [INFO]   PatchManager: Patched 8/11.  (72%)
11:26:28.0194 [INFO]   PatchManager: Patched 9/11.  (81%)
11:26:28.0194 [INFO]   PatchManager: Patched 10/11.  (90%)
11:26:28.0194 [INFO]   PatchManager: Patched 11/11.  (100%)
11:26:28.0194 [INFO]   PatchManager: Patching done
11:26:28.0194 [INFO]   Torch: Starting server.
11:26:28.1322 [INFO]   ConfigDedicatedViewModel: Mods Info successfully retrieved!
11:26:55.2396 [INFO]   Keen:    Networking service: Steam
11:26:55.2396 [INFO]   Keen:    Server successfully started
11:26:55.2396 [INFO]   Keen:    Product name: Space Engineers
11:26:55.2396 [INFO]   Keen:    Desc: Space Engineers
11:26:55.2396 [INFO]   Keen:    Public IP: 81.206.235.26
11:26:55.2396 [INFO]   Keen:    User ID: [009...545]
11:26:55.2396 [INFO]   Keen:    Server connected to Steam
11:26:55.7969 [INFO]   PatchManager: Patching begins...
11:26:55.7969 [INFO]   PatchManager: Patching done
11:26:55.7969 [INFO]   PatchManager: Patching begins...
11:26:55.7969 [INFO]   PatchManager: Patching done
11:26:55.8209 [INFO]   RemoteAPIManager: Remote API started on port 8080
11:26:55.8209 [INFO]   Keen: Remote Server Listener started. Listening on port 8080
11:27:04.3737 [INFO]   Keen:    Loading last session D:\torch game servers\Instance\Saves\franks wereld
11:27:05.0044 [INFO]   Keen:    Loading Sandbox world configuration file D:\torch game servers\Instance\Saves\franks wereld\Sandbox_config.sbc
11:27:05.0044 [INFO]   Keen:    Sandbox world configuration file found, overriding checkpoint settings.
11:27:05.0044 [INFO]   Keen:    Server PolicyResponse (1)
11:27:05.0044 [INFO]   Keen: Downloading world mods - START
11:27:06.2395 [INFO]   Keen:    Reference issue detected (circular reference or wrong order) for mod Steam:758597413
11:27:06.6208 [INFO]   Keen: Downloading world mods - END
11:27:06.6208 [WARN]   ModsDownloadingPatch: Missing Mods:
11:27:07.2013 [FATAL]  Initializer: System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at Torch.Patches.ModsDownloadingPatch.Postfix(ResultData __result, List`1 mods) in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\Patches\ModsDownloadingPatch.cs:line 39
   at Patched_Sandbox.Engine.Networking.MyWorkshopDownloadWorldModsBlocking_0(List`1 cancelToken, CancelToken )
   at Patched_Sandbox.MySandboxGameInitQuickLaunch_0(Object )
   at Patched_Sandbox.MySandboxGameInitialize_0(Object )
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at Torch.VRageGame.DoStart() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\VRageGame.cs:line 325
   at Torch.VRageGame.Run() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\VRageGame.cs:line 125
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at Torch.Patches.ModsDownloadingPatch.Postfix(ResultData __result, List`1 mods) in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\Patches\ModsDownloadingPatch.cs:line 39
   at Patched_Sandbox.Engine.Networking.MyWorkshopDownloadWorldModsBlocking_0(List`1 cancelToken, CancelToken )
   at Patched_Sandbox.MySandboxGameInitQuickLaunch_0(Object )
   at Patched_Sandbox.MySandboxGameInitialize_0(Object )
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at Torch.VRageGame.DoStart() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\VRageGame.cs:line 325
   at Torch.VRageGame.Run() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\VRageGame.cs:line 125
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
11:27:07.3234 [INFO]   Initializer: Generating minidump at Logs\MiniDumpT16-2023-05-27 11-27-07.dmp 

i've atached the minidump 

### Steps to Reproduce
1. How did this issue get triggered? starting up a server that worked before
2. Write the steps here.
3. start up torch, let the program load and then i press start button for the s.e. server. 
[Torch-2023-05-27.log](https://github.com/TorchAPI/Torch/files/11581437/Torch-2023-05-27.log)

### Other Information
Provide links to game logs or saves here if necessary.

**Comment by Bishbash777** [comment]
Mod no longer on workshop, closing
