### ISSUE TITLE
Crash 28/07/2017

### ISSUE THREAD

**Issue by MrBenFTW** [TorchAPI/Torch#56]
0:54:49.8392 [FATAL] Torch: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Essentials.EssentialsPlugin.Dispose()
   at Torch.Managers.PluginManager.DisposePlugins()
   at VRage.Plugins.MyPlugins.Unload()
   at Sandbox.MySandboxGame.Dispose()
   at VRage.Dedicated.DedicatedServer.RunInternal()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Torch.Server.TorchServer.Start()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by MrBenFTW** [comment]
This is an essentials issue sorry.
