### ISSUE TITLE
System.NullReferenceException

### ISSUE THREAD

**Issue by smhguler** [TorchAPI/Torch#571]
**Torch Version:** 1.3.0.260 **SE Version:** 1.203.505

### Expected Behavior
I expected the game to run without errors.

### Observed Behavior
Instead, I encountered the following error:

```plaintext
13:20:48.3979 [FATAL]  Initializer: System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.Game.EntityComponents.MyResourceSinkComponent.Update()
   at System.Action.Invoke()
   at System.DelegateExtensions.InvokeIfNotNull(Action handler)
   at Sandbox.Game.Entities.MyComponentStack.set_Integrity(Single value)
   ...
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at Torch.VRageGame.DoStart() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\VRageGame.cs:line 326
   at Torch.VRageGame.Run() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\VRageGame.cs:line 133
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by smhguler** [comment]
[Logs.zip](https://github.com/TorchAPI/Torch/files/13335259/Logs.zip)

**Comment by Bishbash777** [comment]
Closing -> game issue
