### ISSUE TITLE
The ability to crash a torch server by loading a blueprint into a projector or pasting it into the world.

### ISSUE THREAD

**Issue by daddydante88** [TorchAPI/Torch#589]
- [ ] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [ ] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:** 1.3.1.302 master  **SE Version:** 1.204

It's easier to explain by demonstrating so I took a video. Shorthand something contained in se toolbox blueprints bug a server bringing it down. Video and copy of the log follows.

https://youtu.be/odeqKEqsroI

23:46:54.6425 [FATAL]  Initializer: System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.Game.Entities.MyCubeGrid.PasteGridData.Callback()
   at ParallelTasks.Parallel.RunCallbacks()
   at Patched_Sandbox.Game.World.MySessionUpdate_0(Object , MyTimeSpan )
   at Sandbox.MySandboxGame.Update()
   at Patched_Sandbox.Engine.Platform.GameUpdateInternal_0(Object )
   at Patched_Sandbox.Engine.Platform.GameRunSingleFrame_0(Object )
   at Patched_Sandbox.Engine.Platform.FixedLoop+<>c__DisplayClass11_0<Run>b__0_0(Object )
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at Torch.VRageGame.DoStart() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\VRageGame.cs:line 326
   at Torch.VRageGame.Run() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\VRageGame.cs:line 133
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.Game.Entities.MyCubeGrid.PasteGridData.Callback()
   at ParallelTasks.Parallel.RunCallbacks()
   at Patched_Sandbox.Game.World.MySessionUpdate_0(Object , MyTimeSpan )
   at Sandbox.MySandboxGame.Update()
   at Patched_Sandbox.Engine.Platform.GameUpdateInternal_0(Object )
   at Patched_Sandbox.Engine.Platform.GameRunSingleFrame_0(Object )
   at Patched_Sandbox.Engine.Platform.FixedLoop+<>c__DisplayClass11_0<Run>b__0_0(Object )
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at Torch.VRageGame.DoStart() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\VRageGame.cs:line 326
   at Torch.VRageGame.Run() in C:\ProgramData\Jenkins\.jenkins\workspace\Torch_master\Torch\VRageGame.cs:line 133
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
23:46:54.6425 [INFO]   Initializer: Generating minidump at Logs\MiniDumpT39-2024-09-23 23-46-54.dmp

**Comment by Prozon** [comment]
Hey @daddydante88 do you know if this is still relevant? If so, can you send me a grid to test with?
