### ISSUE TITLE
[Bug report] -  Torch 1.1.207.7, SE 1.182.103, Essentials 1.5.1 (Command Features)

### ISSUE THREAD

**Issue by zMOFOz** [TorchAPI/Torch#59]
- [ ] Verify that this issue is related to Torch and not a Torch plugin or the vanilla game
- [ ] Ensure that the issue is reproducible for testing (provide a link to a test world if necessary)
- [ ] Is this a suggestion?

**Torch Version:** 1.x.xxx.xxx **SE Version:** 1.xxx.xxx
 Torch 1.1.207.7, SE 1.182.103,Essentials **1.5.1**
### Expected Behavior
Add Command To Essentials

### Observed Behavior
Crash

### Steps to Reproduce
1. Fresh Install - Only Used Your exe to install SE DS
2. Moved Save Game Instance
3. Downloaded Essentials and Moved to Plugins Folder
3. Started Server
4. Clicked Plugins
5. Clicked Essentials (1.5.1) In Plugins Tab
6. Clicked Add
7. DBL Clicked Command

(PROGRAM EXITS AFTER THAT)

### Other Information
The Log Window

11:05:32.3984 [INFO] SteamCMD: Checking for DS updates.
11:05:33.2057 [INFO] SteamCMD: Steam Console Client (c) Valve Corporation
11:05:33.3227 [INFO] SteamCMD: -- type 'quit' to exit --
11:05:33.4402 [INFO] SteamCMD: Loading Steam API...OK.
11:05:33.5526 [INFO] SteamCMD: 
11:05:34.6527 [INFO] SteamCMD: Connecting anonymously to Steam Public...Logged in OK
11:05:34.7791 [INFO] SteamCMD: Waiting for user info...OK
11:05:35.7243 [INFO] SteamCMD: Success! App '298740' already up to date.
11:05:35.8877 [INFO] SteamCMD: 
11:05:35.9989 [INFO] Torch: Loading config C:\Torch\Torch.cfg
11:05:36.1404 [INFO] Torch: Init server 'Torch' at 'C:\Torch\Instance'
11:05:36.3735 [INFO] Torch: RELEASE
11:05:36.3735 [INFO] Torch: Torch - Torch 1.1.207.7, SE 1.182.103
11:05:36.3890 [INFO] Torch: Executing assembly: Torch.Server, Version=1.1.207.7, Culture=neutral, PublicKeyToken=null
11:05:36.3890 [INFO] Torch: Executing directory: C:\Torch\
11:05:36.4635 [INFO] CommandManager: Registering command 'help'
11:05:36.4710 [INFO] CommandManager: Registering command 'longhelp'
11:05:36.4710 [INFO] CommandManager: Registering command 'ver'
11:05:36.4810 [INFO] CommandManager: Registering command 'plugins'
11:05:36.4810 [INFO] CommandManager: Registering command 'stop'
11:05:36.4810 [INFO] CommandManager: Registering command 'restart'
11:05:36.4810 [INFO] CommandManager: Registering command 'save'
11:05:36.7594 [INFO] UpdateManager: Torch is up to date.
11:05:38.3916 [INFO] UpdateManager: TorchAPI/Essentials is up to date. (1.5.1)
11:05:38.3916 [INFO] PluginManager: Loading plugins
11:05:38.4061 [INFO] PluginManager: Loading plugin Essentials (1.5.1)
11:05:38.4061 [INFO] CommandManager: Registering command 'entities.refresh'
11:05:38.4226 [INFO] CommandManager: Registering command 'entities.stop'
11:05:38.4226 [INFO] CommandManager: Registering command 'entities.delete'
11:05:38.4371 [INFO] CommandManager: Registering command 'entities.find'
11:05:38.4371 [INFO] CommandManager: Registering command 'grids.setowner'
11:05:38.4371 [INFO] CommandManager: Registering command 'grids.static.large'
11:05:38.4541 [INFO] CommandManager: Registering command 'grids.list'
11:05:38.4541 [INFO] CommandManager: Registering command 'say'
11:05:38.4671 [INFO] CommandManager: Registering command 'tp'
11:05:38.4671 [INFO] CommandManager: Registering command 'w'
11:05:38.4671 [INFO] CommandManager: Registering command 'kick'
11:05:38.4671 [INFO] CommandManager: Registering command 'ban'
11:05:38.4826 [INFO] CommandManager: Registering command 'unban'
11:05:38.4826 [INFO] CommandManager: Registering command 'motd'
11:05:38.4826 [INFO] CommandManager: Registering command 'blocks.on.type'
11:05:38.4956 [INFO] CommandManager: Registering command 'blocks.on.subtype'
11:05:38.4956 [INFO] CommandManager: Registering command 'blocks.off.type'
11:05:38.4956 [INFO] CommandManager: Registering command 'blocks.off.subtype'
11:05:38.4956 [INFO] CommandManager: Registering command 'cleanup.scan'
11:05:38.5147 [INFO] CommandManager: Registering command 'cleanup.delete'
11:05:38.5147 [INFO] CommandManager: Registering command 'voxels.reset.all'
11:05:38.5147 [INFO] CommandManager: Registering command 'identity.clean'
11:05:38.5272 [INFO] CommandManager: Registering command 'identity.purge'
11:05:38.5872 [INFO] InstanceManager: Saved dedicated config.
11:05:40.2934 [INFO] InstanceManager: Saved world config.
11:05:40.2934 [INFO] Torch: Starting server.
2017-07-30 11:05:41.069: Bind IP : 0.0.0.0:27020
2017-07-30 11:05:45.587: Server successfully started
2017-07-30 11:05:45.587: Product name: Space Engineers
2017-07-30 11:05:45.587: Desc: Space Engineers
2017-07-30 11:05:45.587: Public IP: (EDIT OUT)
2017-07-30 11:05:45.587: Steam ID: 90110253926925315
2017-07-30 11:05:47.891: Loading last session C:\Torch\Instance\Saves\SomeGame
2017-07-30 11:05:48.189: Loading session: C:\Torch\Instance\Saves\SomeGame
11:05:58.9145 [INFO] MultiplayerManager: Initializing Steam auth
11:05:58.9245 [INFO] MultiplayerManager: Steam auth initialized
2017-07-30 11:05:58.932: Session loaded
2017-07-30 11:05:59.116: Server connected to Steam
2017-07-30 11:05:59.117: Server PolicyResponse (1)
11:05:59.6974 [INFO] Torch: Starting server watchdog.
2017-07-30 11:05:59.846: Game ready... Press Ctrl+C to exit
11:06:10.4324 [FATAL] Torch: System.InvalidOperationException: 'EditItem' is not allowed for this view.
   at System.Windows.Controls.ItemCollection.System.ComponentModel.IEditableCollectionView.EditItem(Object item)
   at System.Windows.Controls.DataGrid.EditRowItem(Object rowItem)
   at System.Windows.Controls.DataGrid.OnExecutedBeginEdit(ExecutedRoutedEventArgs e)
   at System.Windows.Input.CommandBinding.OnExecuted(Object sender, ExecutedRoutedEventArgs e)
   at System.Windows.Input.CommandManager.ExecuteCommandBinding(Object sender, ExecutedRoutedEventArgs e, CommandBinding commandBinding)
   at System.Windows.Input.CommandManager.FindCommandBinding(Object sender, RoutedEventArgs e, ICommand command, Boolean execute)
   at System.Windows.Input.CommandManager.OnExecuted(Object sender, ExecutedRoutedEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Input.RoutedCommand.ExecuteImpl(Object parameter, IInputElement target, Boolean userInitiated)
   at System.Windows.Controls.DataGrid.BeginEdit(RoutedEventArgs editingEventArgs)
   at System.Windows.Controls.DataGridColumn.BeginEdit(InputEventArgs e, Boolean handled)
   at System.Windows.Controls.DataGridCell.OnTextInput(TextCompositionEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.TextCompositionManager.PostProcessInput(Object sender, ProcessInputEventArgs e)
   at System.Windows.Input.InputManager.RaiseProcessInputEventHandlers(ProcessInputEventHandler postProcessInput, ProcessInputEventArgs processInputEventArgs)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.TextCompositionManager.PostProcessInput(Object sender, ProcessInputEventArgs e)
   at System.Windows.Input.InputManager.RaiseProcessInputEventHandlers(ProcessInputEventHandler postProcessInput, ProcessInputEventArgs processInputEventArgs)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessTextInputAction(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at System.Windows.Threading.Dispatcher.Invoke(DispatcherPriority priority, Delegate method, Object arg)
   at System.Windows.Interop.HwndSource.OnPreprocessMessageThunk(MSG& msg, Boolean& handled)
   at System.Windows.Interop.ComponentDispatcherThread.RaiseThreadMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Window.ShowDialog()
   at Torch.Server.Program.RunServer(TorchConfig config)
   at Torch.Server.Program.Main(String[] args)
Exiting in 5 seconds.

**Comment by zMOFOz** [comment]
13 days and still no fix this is sad

**Comment by Jimmacle** [comment]
It's open source, you can fix it if you're getting impatient.

**Comment by XeroCreator** [comment]
Workaround is to add commands manually. 

Example thanks to Zataralee
<?xml version="1.0"?>
<EssentialsConfig xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <AutoCommands>
    <AutoCommand>
      <Enabled>true</Enabled>
      <Command>!say Welcome to Pathfinders! /MOTD is off line. Rules and limits can be found on SpokaneSurvival.com</Command>
      <DueTime>1</DueTime>
      <Period>600</Period>
    </AutoCommand>
    <AutoCommand>
      <Enabled>true</Enabled>
      <Command>!say Visit SpokaneSurvival.com/Patron to place your vote on the best NEST pirate ship!</Command>
      <DueTime>1</DueTime>
      <Period>120</Period>
    </AutoCommand>
    <AutoCommand>
      <Enabled>true</Enabled>
      <Command>!say Server Restarting in 15 Minutes!</Command>
      <DueTime>1</DueTime>
      <Period>14400</Period>
    </AutoCommand>
    <AutoCommand>
      <Enabled>true</Enabled>
      <Command>!restart</Command>
      <DueTime>1</DueTime>
      <Period>15300</Period>
    </AutoCommand>
  </AutoCommands>
</EssentialsConfig>

I have used a similar setup myself, just edit to your liking. If you can't edit it, you probably shouldn't be running a server :)

**Comment by TheAmazingTaco** [comment]
Where does the config go?

**Comment by zMOFOz** [comment]
XeroCreator - I always known about the work around I explained how to in discord a while back. I was only saying how it was sad because its a major issue and you get stupid people like yourself who cant figure it out. Oh yeah btw nice workaround that you never found out, thanks to Zataralee your dumb ass can run your server.

**Comment by Jimmacle** [comment]
@zMOFOz I have blocked you from contributing to the Torch repositories, this is unacceptable behavior. It's not a major issue because I'm going to replace this feature and the people you're insulting have helped me with Torch development far more than your inappropriate comments.
