### ISSUE TITLE
[BUG] Connector bug vs Concealment

### ISSUE THREAD

**Issue by Varaxian** [TorchAPI/Torch#63]
**Potentially a KEEN related bug being exacerbated by concealment: 
04:50:02.5219 [FATAL] Torch: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance 
 of an object.**

**Torch Version:** 1.1.213.390 **SE Version:** 1.182.103

### Summary
An issue arose while testing a candidate build fixing world-save issues. This issue persists in 1.1.213.390.
In short, when connectors are concealed, there is a FATAL error (as shown above, and full login attached) that crashes the server.  This issue has been double-confirmed and will be explained further in REPRO.

### Expected Behavior
Launch torch with concealment on, excluding no types. Torch launches server and server is operational.

### Observed Behavior
When connectors are concealed at start, a fatal error regarding System.Reflection.TargetInvocationException is thrown.
Server crashes as a result

### Steps to Reproduce
1. With no concealment exceptions set to connectors, Launch torch with a heavily populated worldfile.
2. Upon 1st character login, after grids have been revealed for that character, a FATAL error occurs and the server crashes.

### Repro Verification
1. Launch torch but do not start
2. Set concealment exceptions for the following: ShipConnector, Connector, ConnectorSmall
3. Start the server
4. Session will load, 1st character will login and no crash. 

### Workaround
1. Following the steps in **Repro Verification**, launch torch and start the server
2. Load the first character into the world
3. Open TORCH GUI, remove connector exceptions and Manual reveal
4. Sim speed returns, server becomes stable.

### Log excerpt
02:49:40.5871 [FATAL] Torch: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Sandbox.Game.Entities.Cube.MyShipConnector.CreateBodyConstraint(MyPhysicsBody body, HkFixedConstraintData& constraintData, HkConstraint& constraint)
   at Sandbox.Game.Entities.Cube.MyShipConnector.CreateBodyConstraint()
   at Sandbox.Game.Entities.Cube.MyShipConnector.UpdateOnceBeforeFrame()
   at Sandbox.Game.Entities.MyEntities.UpdateOnceBeforeFrame()
   at Sandbox.Game.Entities.MyEntities.UpdateBeforeSimulation()
   at Sandbox.Game.World.MySector.UpdateBeforeSimulation()
   at Sandbox.Game.World.MySession.UpdateComponents()
   at Sandbox.Game.World.MySession.Update(MyTimeSpan updateTime)
   at Sandbox.MySandboxGame.Update()
   at Sandbox.Engine.Platform.Game.UpdateInternal()
   at Sandbox.Engine.Platform.Game.RunSingleFrame()
   at Sandbox.Engine.Platform.FixedLoop.<>c__DisplayClass1.<Run>b__0()
   at Sandbox.Engine.Platform.GenericLoop.Run(VoidAction tickCallback)
   at Sandbox.Engine.Platform.Game.RunLoop()
   at Sandbox.MySandboxGame.Run(Boolean customRenderLoop, Action disposeSplashScreen)
   at VRage.Dedicated.DedicatedServer.RunInternal()
   --- End of inner exception stack trace ---

**Comment by Varaxian** [comment]
UPDATE:

Error is caused by an illegal termination of TORCH (crash or closing the console instead of the server stopping as designed).

Temporary Workaround when the error is experienced is ACTUALLY:
- Disable Autostart if enabled
- Start Torch
- Disable Concealment
- Start Server
- Once game ready, enable concealment and trigger the concealment command.

**Comment by kamikaze0310** [comment]
@Varaxian this is strange...I have over 150 grids and I don't have this issue...I know there plenty in there with connectors

**Comment by Varaxian** [comment]
I have over 600 and I've verified reproduction, unfortunately.

More or less, if concealment isn't finished at crash, its in an error state and you have to disable concealment to launch the server.

I can actually reproduce it on demand now
